### ISSUE TITLE
[Unreal] Unreal example plugin breaks in Shipping Builds

### ISSUE THREAD

**Issue by oreyg** [discordapp/discord-rpc#107]
It does not include in build.cs
RuntimeDependencies.Add(*path to discordPrcLibrary*)
and settings are incorrect in .uplugin, should be
`"Modules": [
		{
			"Name": "discordrpc",
			"Type": "Runtime",
			"LoadingPhase": "PreDefault"
		}
	]`

**Comment by msciotti** [comment]
Thanks for the note, I've added a to-do card. We also welcome PRs!

**Comment by oreyg** [comment]
I actually recreated the plugin, using your code as a reference, to make it work in release builds.
[DiscordAPI.zip](https://github.com/discordapp/discord-rpc/files/1639909/DiscordAPI.zip)
Its uses statically linked lib.

**Comment by oreyg** [comment]
Made a PR
https://github.com/discordapp/discord-rpc/pull/112
