### ISSUE TITLE
Discord does not detect my game.

### ISSUE THREAD

**Issue by oreyg** [discordapp/discord-rpc#108]
Discord does not detect my game, even through it successfully connects and receives Rich Presence messages.
I'm sending SteamID (as numeric string) and AutoRegister is set to true.
What steps I should follow to ensure that Discord will successfully detect my game?

**Comment by msciotti** [comment]
Discord will detect your game once you push a `Discord_UpdatePresence()` call. `Discord_Initialize()` opens the connection, but you haven't sent any presence data yet, so we won't show your game as running.

Please let me know if your game still is not showing once you've pushed a presence update!

**Comment by oreyg** [comment]
Its still not showing, even through I call Discord_UpdatePresence, I will post a video soon.

**Comment by oreyg** [comment]
It successfully runs through Discord_RegisterSteamGame -> Discord_Register -> Discord_RegisterW, and creates keys in registry. It seems the problem is not in the discord-rpc.

**Comment by msciotti** [comment]
Received the video. There should be no reason why it's not auto-detected when you push a presence and why you had to manually add the game. Seems like a bug. Can you do the following for me:

1. Open your game and push an `UpdatePresence()` call WITHOUT manually adding your game
2. Open the Discord console with `control + shift + i`
3. See if there are `SET_ACTIVITY`
4. See if any of those `SET_ACTIVITY` calls have errors. If so, post a screenshot here
5. Look for `runninggamesstore` logs and post a screenshot of them here to see if there are any errors

**Comment by oreyg** [comment]
No errors, but hidden: true
![hidden_true](https://user-images.githubusercontent.com/13616895/35117403-c1fbdb04-fcb8-11e7-8f26-402031540bf2.png)

**Comment by crmarsh** [comment]
I added that hidden thing for games that are on Steam but not published yet; you have to manually add the game if you want it to show up before it is published.

**Comment by msciotti** [comment]
Oh, yes, that is an important thing to note. If your game has not released on Steam we won't autodetect. Thanks @crmarsh !

**Comment by oreyg** [comment]
This was a headache for me. It will appear for users right after we publish, including those that had game installed before release, is that correct?

**Comment by msciotti** [comment]
Yes, once you publish it'll show. Might take maybe an hour or two to be "noticed" as launched in our system, but it will just work.

**Comment by msciotti** [comment]
@oreyg may I mark this issue as closed? Now that we've figured out the cause of the problem.

**Comment by oreyg** [comment]
Yep, just add a little note in docs, please.

**Comment by msciotti** [comment]
Noted here: https://discordapp.com/developers/docs/rich-presence/how-to#a-note-on-testing-and-game-detection

**Comment by StrikerTheHedgefox** [comment]
You seriously need to have your game published on steam to be detected as a game? Why hasn't anyone told me this in all the previous reports? I guess guys working on Open Source projects are just fucked, then.

**Comment by crmarsh** [comment]
It's been a while since I worked there, so take this with a grain of salt, but no, Discord detects lots of games that are not on Steam. The above was about blocking games that are on Steam but not flagged as published yet.

**Comment by StrikerTheHedgefox** [comment]
Strange. It's been years since my two apps (EDuke32-OldMP, and the Discord Matchmaking tool for it) have been properly detected as games. The rich presence works, of course, but invites and launching doesn't work, and nobody can get discord to detect them as games. It just, stopped one day, for good, with no action on my part, when it worked before.

**Comment by EuangamingYT** [comment]
my discord is saying i am playing roblox but im not pls help me
