### ISSUE TITLE
Web API

### ISSUE THREAD

**Issue by rafaelcastrocouto** [discordapp/discord-rpc#11]
Hi there;

First of all, great project!
I have an online game (foda.gq), it has a nodejs back-end 
so it's 100% javascript - well there's also the css and html ;D
I would like to integrate it with Discord Rich Presence.
Is that possible? Can I help making it possible, how?

Thanks a lot!

**Comment by crmarsh** [comment]
That could be cool, but I'd worry a bit about it becoming a vector for ads/malware to allow arbitrary websites to set users' status there 🤔

**Comment by 45Green** [comment]
@crmarsh OAuth 2.0 for online games?
![image](https://user-images.githubusercontent.com/17544723/32639454-00f7121a-c5ff-11e7-998e-3b1f2bbee848.png)

**Comment by JoeZwet** [comment]
try building discord-rpc then following this: http://www.benfarrell.com/2013/01/03/c-and-node-js-an-unholy-combination-but-oh-so-right/ idk if it will work but its worth a try

**Comment by cthpw103** [comment]
That should be kindof easy with the WebSocket object, but maybe OAuth? 🤔

**Comment by Cl1608Ho** [comment]
I can't say a thing about it's quality, but there is this plugin for discord.js: [devsnek/discord-rpc](https://github.com/devsnek/discord-rpc)

**Comment by crmarsh** [comment]
Yeah, OAuth kinda deal would be the way to go here for web games, but it also loses some of the magic of this just showing up. I wonder if there is some non security hole middle ground.

**Comment by morpig** [comment]
Maybe game developers should submit their Game/Web URLs (like rpc_origins) to Discord, so no authentication is required for Rich Presence (using websockets). Unless the developers needed other stuffs, then they need the rpc and rpc.api scope.

**Comment by Cl1608Ho** [comment]
Well.

Its no different in standalone games as it is in web apps I guess. What you would need in order to bypass the rpc authorization popup is an rpc token which is handed out afaik only to Gamebridge apps.

Dunno tho, this was what I remember.

**Comment by Fades** [comment]
While already considering adding GameBridge to our web game, OAuth isn't an issue for us and we'd kill to be able to implement Rich Presence as well.

**Comment by boynedmaster** [comment]
Hi. I'm using an engine where the only feasible way of using RPC is with HTTP requests (don't ask about this). Would love to see an HTTP API.

**Comment by FireController1847** [comment]
Hey! I've been wanting to make a Google Chrome extension to do this for a while but I can't (because so called "JavaScript" library doesn't work with Browserify), so I +1 this request as I would absolutely love this.

**Comment by msciotti** [comment]
@rafaelcastrocouto, Mr. Devsnek was kind enough to wrap Rich Presence for javascript with b9f9b08. Happy coding!

**Comment by boynedmaster** [comment]
Er, that isn't entirely good enough for everyone @msciotti. Like others and future developers, I don't want a *JavaScript* API. I want an *HTTP* API. There is no alternative.

**Comment by Dragas** [comment]
Both the issue title and the opening statement are misleading. NodeJS backend does not mean web, nor does web mean javascript/nodejs. @boynedmaster raises a valid point.

**Comment by msciotti** [comment]
Sure, @boynedmaster does raise a valid point. This issue was opened by someone who was requesting a wrapper they could use with their web application that has a nodejs backend. One now exists, so I'm closing this issue as we have resolved it in scope.

If you would like to open another issue specifically requesting HTTP support, that would be the proper next steps.

That being said, the entire structure of Rich Presence is based on a socket connection. So, I unfortunately don't think pure HTTP support will happen, but I'm willing to keep an issue open as the official feature request.

**Comment by FireController1847** [comment]
@msciotti But isn't a WebSocket connection requiring you to be whitelisted? We were thinking a _public_ HTTP api, but WebSockets do do the job. The issue is, afaik, they're not public.

**Comment by morpig** [comment]
I think Public HTTP API wont work for this kind of use case. How will you know that a user requested to spectate/join the game? I prefer WebSocket for this kind of use case.

**Comment by boynedmaster** [comment]
@morpig HTTP RPC could have the downside of not letting people spectate or join your games.

**Comment by rafaelcastrocouto** [comment]
First of all, thanks a lot Mr. Devsnek!

Second, although the wrapper could solve my issue, 
it would require that I coded the whole webClient x nodeServer x discordRPC stuff.

It would be way better if we had a way to implement this directly (webClient x discordRPC).
As mentioned, we could not achieve this with HTTP since polling is not suitable.

So, should I make a new issue asking for a Public Socket Javascript API 
or can we keep this chat over here?

**Comment by devsnek** [comment]
technically you can use rpc over websockets already (and rpc.api allows you to make HTTP api calls), but you'll need to be whitelisted as part of the gamebridge program to use these features. check out https://discordapp.com/gamebridge and https://discordapi.com/topics/rpc#connecting-to-the-rpc-server

**Comment by Cl1608Ho** [comment]
@devsnek actually, you don't need a Gamebridge contract with discord in order to use rpc. It's only required for using the sdk, for accessing the rpc server within the sdk and for accessing the discord client's rpc without confirmation.
