### ISSUE TITLE
[Feature Request] Allow developers to control Game Activity's hidden parameter

### ISSUE THREAD

**Issue by oreyg** [discordapp/discord-rpc#110]
At the moment the system works so that games, that are not released in Steam do not appear in the profile. This is good, because in this way you can hide the fact that the game is in development. However, if the game is not tied to a Steam, then it's not possible to hide it. Therefore, it would be better if the developer had option to explicitly set visibility of the game.

**Comment by Vatuu** [comment]
A non-steam game, if it's not registered in the discord-executationpath-tied-to-application thingy, would need to be manually registered in the game detection anyway, so you could just not register it?

**Comment by oreyg** [comment]
@Vatuu Yep, sounds good. Silly me.
