### ISSUE TITLE
Party Size Bug

### ISSUE THREAD

**Issue by Lachee** [discordapp/discord-rpc#111]
I am implementing my own C# version of this library and have been basing it off this one. I followed your implementation of Party Size and come across a issue. 

The documentation states it needs both size and maxsize, but your implementation makes it optional.
```cpp
if ((presence->partyId && presence->partyId[0]) || presence->partySize ||
                    presence->partyMax) {
                    WriteObject party(writer, "party");
                    WriteOptionalString(writer, "id", presence->partyId);
                    if (presence->partySize) {
                        WriteArray size(writer, "size");
                        writer.Int(presence->partySize);

                        //This is making max optional
                        if (0 < presence->partyMax) {
                            writer.Int(presence->partyMax);
                        }
                    }
                }
```

When I implemented, I copied the optional party max. 
```csharp
 [JsonProperty("size", NullValueHandling = NullValueHandling.Ignore)]
        private int[] _size
        {
            get
            {
                //We have no size, so its null
                if (!Size.HasValue) return null;

                //It does not have a max size, so just return the size
                if (!Max.HasValue)
                    return new int[] { Size.Value };

                //It has max size, return both
                return new int[] { Size.Value, Max.Value };
            }
        }
```

However if I set Max to null (excluding it from the array), I get a error message from discord:
`"child "activity" fails because [child "party" fails because [child "size" fails because ["size" must contain 2 items]]]"`

Everything else works, and I can have nullable timestamps etc, but its just the party size that throws an error. Either the documentation is wrong or the implementation in  /src/serialization.cpp#L137 is wrong.

This is the JSON I am spitting out (prettified for convenience):
```json
{
  "args": {
    "pid": 8784,
    "activity": {
      "state": "In Editor",
      "details": "Testing Library",
      "timestamps": {
        "start": 1
      },
      "assets": {
        "large_image": "default_large",
        "large_text": "Where's Perry?",
        "small_image": "default_small",
        "small_text": "THREADS RULE"
      },
      "party": {
        "id": "dickwaffles",
        "size": [
          1
        ]
      },
      "instance": false
    }
  },
  "cmd": "SET_ACTIVITY",
  "nonce": "1"
}
```

**Comment by oreyg** [comment]
https://github.com/discordapp/discord-rpc/blob/060182f366690fbdfdca99ae2f855da79bf30a8f/documentation/hard-mode.md
The one major difference is the `party.size` field. It is an array with a size of two. The first element is the current party size, `partySize` from the main documentation. The second element is the maximum party size, `partyMax` from the main documentation.

**Comment by Lachee** [comment]
Correct.
However in serialization.cpp on line 137:
```cpp
  //This is making max optional
 if (0 < presence->partyMax) {
    writer.Int(presence->partyMax);
 }
```

It is only writing the second number if it has a second number.

**Comment by oreyg** [comment]
Ive just checked the code and it omits second number if its _below_ 0. So no bug here.

**Comment by msciotti** [comment]
In the SDK, that field is marked as optional. However, I believe that in actual implementation, the invite will not work properly without a `partyMax`. @snowyote we should probably change this to be required.
