### ISSUE TITLE
[Feature Request] 'Join me' commands in chat

### ISSUE THREAD

**Issue by oreyg** [discordapp/discord-rpc#114]
I was unable to find a way to invite someone to a group in a convenient way. And so I think it would be nice to be able to publish a clickable link in the chat room.
For example, allow to use /joinme command, that will create a 'Join' button for everyone in chat (maybe including non-friends). If someone clicks on a button, party leader receives usual join request, that he can accept or decline.
Also this join link should have expiration time to prevent abuse of old links.

**Comment by Vatuu** [comment]
That literally already exists...

You just have to press the „Append File“ button if you‘re playing a game with rich presence game that has passed a match and join- or spectate secret. A little windows will be posted in the channel, allowing you to join the party of a player, displaying the users in the party and the game to be played.

**Comment by oreyg** [comment]
Ooops, it really does, kek
