### ISSUE TITLE
Discord_Shutdown doesn't wait for ClearPresence

### ISSUE THREAD

**Issue by Vultraz** [discordapp/discord-rpc#117]
I'm using the v2.1.1 lib, and I noticed that `Discord_Shutdown` doesn't clear Rich Presence data. Additionally, it doesn't wait for `ClearPresence` to complete either, so it seems impossible to clear RP data on shutdown except by actually closing your game.

**Comment by msciotti** [comment]
I'm confused as to what your use case is. In the case that you want to clear your game's presence from a user's Discord profile without closing the game, calling `ClearPresence()` will do so. In the case that you want to clear the presence _and_ close the game (like a Quit button from a menu), simply closing the game will close the connection and remove the presence information.

`Discord_Shutdown()` destroys the thread on which the connection runs, allowing you to exit your game without any issues from us. In fact, the thread destruction is actually now done without needing to explicitly call `Discord_Shutdown()`, but you can use it for the sake of being explicit.

Could you tell me a bit more about your use case that you're running into this issue?

**Comment by Vultraz** [comment]
It's a bit of a corner case, really. I was attempting to implement Rich Presence for the MP portion of the game only. I'm now expanding it to the entire game, but I figured I might as well report this.

Essentially, I had a manager object that existed while a player was in MP mode which initializes (in its constructor) Rich Presence (`Discord_Initialize`) and destroys (`Discord_Shutdown`) in its destructor:

https://github.com/wesnoth/wesnoth/blob/e1db5fd879db3bca4ac0afbb3b225059a90c9144/src/desktop/discord_rich_presence.cpp#L70-L75

But when the manager object was destroyed, the last Rich Presence data I sent remained displayed in Discord, it never vanished.

**Comment by msciotti** [comment]
Gonna close this issue, as it is working as documented, though I'm sorry that we don't play super nicely with your use case.
