### ISSUE TITLE
Unreal Engine 4.18.3

### ISSUE THREAD

**Issue by Jengas** [discordapp/discord-rpc#124]
Hello! I downloaded example for unreal engine 4 and when I open this `unrealstatus.uproject` it says this:

![image](https://user-images.githubusercontent.com/14033756/36100672-51856efa-1007-11e8-98bc-4c5e301e7bab.png)

And when I press rebuild button, it says:
![image](https://user-images.githubusercontent.com/14033756/36100692-66655088-1007-11e8-9258-d4ecd28ca1d3.png)

Then I tryed to rebuild from `unrealstatus.sln`

![image](https://user-images.githubusercontent.com/14033756/36100716-7e9c14ca-1007-11e8-83e0-d88afb575fdd.png)

I dont know what to do. P.S I am new for this and practising

**Comment by msciotti** [comment]
I don't think my build script works in master for Unreal yet, so make sure you have the DLL in the right place. First, grab the windows DLL from our [Releases](https://github.com/discordapp/discord-rpc). Then, place it in:

`discord-rpc\examples\unrealstatus\Plugins\discordrpc\Source\ThirdParty\DiscordRpcLibrary\Win64`

You'll also want to put the header files located at `discord-rpc\include` in:

`discord-rpc\examples\unrealstatus\Plugins\discordrpc\Source\ThirdParty\DiscordRpcLibrary\Include`

**Comment by Vatuu** [comment]
If you're building from the latest source, please keep in mind that now
discord-register.h is located in include too. I'll take the blame for this,
sorry :/

2018-02-12 18:43 GMT+01:00 Mason Sciotti <notifications@github.com>:

**Comment by msciotti** [comment]
@Jengas bumping this as the build script is now done in master. If you pull the latest changes, you should be able to run `python build.py unreal` and have the libraries in the right place. Please make sure you also place `discord_register.h` and `discord-rpc.h` in the proper include path, listed above.

Let me know if this fixes the issue.

**Comment by Jengas** [comment]
@msciotti sure, thank you!

**Comment by msciotti** [comment]
Haven't heard from you in a bit about this, so gonna close the issue. Please re-open if it persists.
