### ISSUE TITLE
[Unity] Wont stop playing (on discord) until i quit the editor.

### ISSUE THREAD

**Issue by ThomasAunvik** [discordapp/discord-rpc#13]
Trying out the Testing RPC asset, and when i start the game it wont show up in discord until i click a button. And whenever i quit the game / stop playing the game, it still continues to show up. It disappears when i exit the editor.

![](https://i.imgur.com/0oH6yJK.png)

**Comment by crmarsh** [comment]
This is intentional, though I'm going to add a call to explicitly disable the rich presence status.

If you want more detail: As far as Discord is concerned here, the Unity editor is the process it is talking to, so as long as it is still running, it thinks you are still playing that game.

**Comment by ThomasAunvik** [comment]
Thanks for the information.

**Comment by msciotti** [comment]
Wew, this has been hanging around for a while. For the sake of coming full circle, the latest SDK release version has a new `Discord_ClearPresence()` function, which will do just this for you :)
