### ISSUE TITLE
Unreal Engine 4.15+ Nativize Error

### ISSUE THREAD

**Issue by Hevedy** [discordapp/discord-rpc#131]
When you try to package the game as shipping and with Nativize as Inclusive the compiler find a problem with the Object Discord

"...Source/NativizedAssets/Public/BP_GameInstanceCore__pf2323974764.h(58) : Error: Unrecognized type 'UDiscordRpc' - type must be a UCLASS, USTRUCT or UENUM"

My Discord var there is a DiscordRPC Reference type, any idea or why this happen ?

*Visual Studio and all compiles fine, just happen at package and Nativize

**Comment by msciotti** [comment]
I can take a look at this. It looks like it's marked as a `UCLASS` in the code, which is odd:

https://github.com/discordapp/discord-rpc/blob/f5f2d69a72954647a9c9e457324908b205502c4a/examples/unrealstatus/Plugins/discordrpc/Source/DiscordRpc/Public/DiscordRpcBlueprint.h#L82

**Comment by msciotti** [comment]
So, I believe I've done the same steps that you have trying the sample application, and I could not repro. Are these settings correct?

![image](https://user-images.githubusercontent.com/4193854/36287557-85e1744a-126a-11e8-82fa-4b02c44a8906.png)

![image](https://user-images.githubusercontent.com/4193854/36287568-8d1d3aa0-126a-11e8-8f7c-c9d797ff0302.png)

![image](https://user-images.githubusercontent.com/4193854/36287571-93158f02-126a-11e8-9c06-189816f43922.png)

**Comment by Mootjuh** [comment]
Could you post part of the nativized code that errors?

**Comment by Hevedy** [comment]
Yeah like you have done, then make sure you have a GameInstance or some class and add a var called as you want based in the UObject of Discord
![ue4editor_2018-02-15_22-06-17](https://user-images.githubusercontent.com/3521442/36301532-82346488-1305-11e8-9ecf-bfcc2bbf9f2e.png)
![ue4editor_2018-02-15_22-06-46](https://user-images.githubusercontent.com/3521442/36301536-8573e948-1305-11e8-9c0e-0345c8e43067.png)
![2018-02-15_22-12-26](https://user-images.githubusercontent.com/3521442/36301540-89bb3632-1305-11e8-8835-afd9cdd4a393.png)

I'm using the version 4.15 but didn't tested the newer ones right now*

**Comment by Mootjuh** [comment]
Where's your constructor?
![image](https://user-images.githubusercontent.com/13383284/36302118-938c69c2-1307-11e8-88e0-d8670c19aedb.png)

**Comment by Hevedy** [comment]
I have no constructor, just the var, probably that is the problem ? Let me check :thinking:

**Comment by Mootjuh** [comment]
Most likely.

**Comment by Hevedy** [comment]
Added the constructor
![ue4editor_2018-02-16_11-05-05](https://user-images.githubusercontent.com/3521442/36302687-a7ea0e86-1309-11e8-82fa-5fd48a7ab744.png)

Solves nothing, I want to say without the constructor and without nativize the Discord system worked so...

**Comment by Mootjuh** [comment]
The Outer must be a playercontroller AFAIK

**Comment by Hevedy** [comment]
Don't think so as have parts of other code I can't show, still looks total like a bug with UE4 or something ?
In other hand I can't create that using a player controller because must cross between levels and menus and basically as is in the GameInstance

**Comment by Mootjuh** [comment]
When you nativize, the nativized code shows in intermediate "\Intermediate\Plugins\NativizedAssets". Open up the file it says its erroring at and pastebin it or something.

**Comment by Hevedy** [comment]
"UPROPERTY(EditDefaultsOnly, BlueprintReadWrite, meta=(DisplayName="Discord RPC", Category="Social", OverrideNativeName="DiscordRPC"))
	UDiscordRpc* bpv__DiscordRPC__pf;"
The return error is the one I postd on top and the code is this one on the line 58

**Comment by Mootjuh** [comment]
Can you post both the full .h and .cpp file of it instead?

**Comment by Hevedy** [comment]
As said no cause have included other libs and private content.

But I notice by adding in my project cs:

		PublicDependencyModuleNames.AddRange(new string[] { ... "DiscordRpc" ... });
		PublicIncludePaths.AddRange(new string[] {"DiscordRpc/Public" });

Fixes that problem but return me a different one with the Gameinstance trying to get something public <no idea if is related>

**Comment by msciotti** [comment]
Glad you were able to get the help you needed here. Thank you Mootjuh for your assistance.
