### ISSUE TITLE
im tring to upload an assets but it doesent work

### ISSUE THREAD

**Issue by vascreeperGR** [discordapp/discord-rpc#132]
i dont know if im uploading wrong size i was trying to upload a 512x512 image and it says Minimum Size: 512x512 in red im i doing something wrong???? i was testing it and it worked fine with no image

**Comment by msciotti** [comment]
Could you post a screenshot of this error? I just tried it myself with a 512x512 image and it worked just fine.

**Comment by msciotti** [comment]
Has @vascreeperGR, are you still seeing this issue? Will leave this issue open for another day or so for you to respond with errors/console errors so we can diagnose. Otherwise, I'll assume fixed and close.

**Comment by vascreeperGR** [comment]
Sorry i lost my email pass i will send a screenshot now

**Comment by vascreeperGR** [comment]
Or i will close it now for some reason it works
