### ISSUE TITLE
IoThreadHolder edge case

### ISSUE THREAD

**Issue by codecat** [discordapp/discord-rpc#134]
Okay, so my situation might be a little bit specific, but perhaps can be solved without requiring me to use `DISCORD_DISABLE_IO_THREAD`. (This is actually the second project I've experienced this issue with, but only now actually figured out exactly what is happening.)

I build the discord-rpc library statically and link it into a dll, which I then dynamically load into a process.

This works great when cleanly shutting down with `Discord_Shutdown()`, but not on process termination. In this case, `~IoThreadHolder()` gets called (because of the static instance of `IoThreadHolder`), which runs `Stop()` which causes a deadlock because it's waiting on a [non-existing thread that has already been terminated](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682658(v=vs.85).aspx):

> All of the threads in the process, except the calling thread, terminate their execution without receiving a DLL_THREAD_DETACH notification.

The MSDN page also states:

> If one of the terminated threads in the process holds a lock and the DLL detach code in one of the loaded DLLs attempts to acquire the same lock, then calling ExitProcess results in a deadlock.

![](https://4o4.nl/20180227FkE1UBg8.png)

The same thing also happens when trying to call `Discord_Shutdown()` in `DllMain` when `lpvReserved` is non-null, but that can be avoided by simply not calling that, as process termination here is essentially not clean.

I know this might be sort of an edge-case for me, but perhaps this can be fixed somehow?

**Comment by codecat** [comment]
I found a workaround for this that I'll be using for the time being:

```c++
    void Stop()
    {
#ifdef _MSC_VER
        // Windows-only hack: don't bother if thread is already killed
        DWORD dwExitCode = 0;
        ::GetExitCodeThread((HANDLE)ioThread.native_handle(), &dwExitCode);
        if (dwExitCode != STILL_ACTIVE) {
            return;
        }
#endif

        keepRunning.exchange(false);
        Notify();
        if (ioThread.joinable()) {
            ioThread.join();
        }
    }
```

**Comment by msciotti** [comment]
Thank you for letting us know about this and posting a temporary workaround for folks that may also be experiencing this.

@snowyote will take a look and see if there's a way that we can fix this a bit more elegantly.

**Comment by snowyote** [comment]
Honestly, it seems like we just shouldn't call `Stop()` from `~IoThreadHolder()` - if we're at the point that static destructors have been called, pokily going to the trouble of shutting down threads seems pointless as the OS is obviously already doing it for us.

@codecat, does that seem like that would fix your problem without interfering with the `Discord_Shutdown()` use case?

**Comment by crmarsh** [comment]
iirc I added it because there is an `abort` in `std::thread` destructor if you didn't join the thread.
