### ISSUE TITLE
Can't open 'discord-rcp.lib'

### ISSUE THREAD

**Issue by L4Vo5** [discordapp/discord-rpc#138]
I've been trying for a few hours to set up a simple program to test the basic features of rich presence. I had a bit of trouble following the instructions, but searching on google seemed to be solving the problems that popped up.
But now I'm stuck. I put the .h files in the project directory (I'm using visual studio 2017), and I've linked the lib folder, and mentioned discord-rcp.lib, in several places of the properties.
I get the following error (translated from spanish):
1>LINK : fatal error LNK1104: can't open file 'discord-rcp.lib'
Is there something I'm doing wrong? The things I've done are all new to me, so I didn't really know what I was doing. I wouldn't discard the possibility that everything I did thus far was wrong.

For the code of the project itself, I basically copy-pasted the code from send-presence, changing a few things to solve a few errors that popped up (as I'm using C++ and that, I think, is in C)

**Comment by WolfspiritM** [comment]
> 1>LINK : fatal error LNK1104: can't open file 'discord-rcp.lib'

Looks like a typo there.
The lib is called "discord-rpc.lib" not discord-rcp.lib"

**Comment by L4Vo5** [comment]
Oh wow, that was dumb.

Now I'm getting a lot of errors, all saying some values don't match.
These are the first three lines. I don't think I should paste the entire log, specially as it is in spanish:

1>discord-rpc.lib(discord_rpc.obj) : error LNK2038: differences were detected for '_ITERATOR_DEBUG_LEVEL': the value '0' doesn't match the value '2' in ConsoleApplication1.obj

1>discord-rpc.lib(discord_rpc.obj) : error LNK2038: differences were detected for 'RuntimeLibrary': the value 'MD_DynamicRelease' doesn't match the value 'MDd_DynamicDebug' in ConsoleApplication1.obj

1>discord-rpc.lib(discord_register_win.obj) : error LNK2038: differences were detected for '_ITERATOR_DEBUG_LEVEL': the value '0' doesn't match the value '2' in ConsoleApplication1.obj

I also get this other error:

1>LINK : warning LNK4098: the predetermined [might be better to translate as default?] library 'MSVCRT' is in conflict with other libraries; use the library /NODEFAULTLIB:biblioteca

**Comment by bitcynth** [comment]
I am trying to not sound rude or anything, but please consider learning basic c++ and what c++ is before reporting stuff as issues with the library.

**Comment by msciotti** [comment]
Sorry to be late on this one. @L4Vo5, these are some issues in your implementation/linking of the DLL rather than the library itself. Unfortunately, I can't really offer coding help here. If you run into issues with the library specifically in the future, this is the place to come, but not for general coding/project setup help. Thank you!
