### ISSUE TITLE
[Unity] Custom App Images wont show up in User Info

### ISSUE THREAD

**Issue by ThomasAunvik** [discordapp/discord-rpc#14]
As you see in the images, i have added the additional info to make this work. Including the App Id.
I have also tried Image Text, but that does not work either.
![](https://i.imgur.com/4bciJC8.png)
![](https://i.imgur.com/X6S4tM6.png)

**Comment by night** [comment]
Try restarting your Discord client. It might be due to caching.

**Comment by ThomasAunvik** [comment]
It worked, thanks.
