### ISSUE TITLE
Making a dll

### ISSUE THREAD

**Issue by Issvn** [discordapp/discord-rpc#141]
Hi ! 
I wanna know to build a windows 64bits dll, 32bits dll and a MacOS dll ?
Thanks.

**Comment by MinnDevelopment** [comment]
You can use the artifacts in the [latest release](https://github.com/discordapp/discord-rpc/releases/tag/v3.0.0)

**Comment by Issvn** [comment]
OH !
I have'nt noticed that...
Thanks

**Comment by Issvn** [comment]
But, should I use dynamic or static ?

**Comment by msciotti** [comment]
That's a question for your game Engine. I believe you were using Unity, so you want dynamic. Otherwise, you'll have to do a bit of research to figure out which is best for your project.
