### ISSUE TITLE
[Feature Request] Scroll strings at the client if they exceed the width of the profile view

### ISSUE THREAD

**Issue by sll552** [discordapp/discord-rpc#146]
It would be nice to be able to tag long strings as scrolling and then let these strings scroll in the client so they can be read in the small player profile.

**Comment by msciotti** [comment]
I believe our intention was to marquee strings that went longer than the profile width. @mpeterson2 is this something we still plan to do?

**Comment by sll552** [comment]
Just to be clear, with "small player profile" I am talking about the small popout when you click at someone in the memberlist.
What do you mean with marking those strings?

**Comment by Lachee** [comment]
it would be nice to extend this with all strings that exceed their max length and not have to rely on manually tagging them. Especially the description string would be the most useful. Tagging them seems redundant when a length check could be used automagically by the discord client.

**Comment by sll552** [comment]
I thought about tagging them because sometimes it might just be like 2-3 chars too long and then scrolling would be kinda distracting, but I'am happy either way.

**Comment by msciotti** [comment]
Yeah if we did this, it wouldn't be a tagging thing I don't think. We'd just automatically scroll ones that are longer than the width. And @sll552 not marking, marquee. Like the <marquee /> html tag which scrolls text ;)

**Comment by sll552** [comment]
Oh, html didn't come to my mind :D
Yeah, it would be nice to automatically scroll text that otherwise would be cut off.

**Comment by msciotti** [comment]
To update—I placed this on an internal todo list (I did when this was opened, sorry just doing some house cleaning on the repo right now). I don't have an ETA, as it's a somewhat low priority issue, but it is on our radar!

**Comment by codecat** [comment]
I'd like to +1 this, as it's quite hard to fit everything into the small dialog. The hover tooltip helps, but it doesn't work for the player count in a lobby, so you'd for example only see `(2 of`, and hovering your mouse over it doesn't make it show a tooltip, so you have no idea what the max players are.

**Comment by msciotti** [comment]
Moved to [Feedback Site](https://support-dev.discordapp.com/hc/en-us/community/posts/360043425811-Scroll-strings-on-users-profiles-if-they-re-too-long-to-fit-in-the-view) due to #290
