### ISSUE TITLE
build.py issues

### ISSUE THREAD

**Issue by AdnascentiaV** [discordapp/discord-rpc#147]
I'm trying to implement rich presence into our Unity based game, but I'm running into some errors I don't know how to handle. My approach to make a dll for use in our game is to clone the repo from github then open the dir in cmd and run "build.py unity" (i've also tried "python build.py unity") i've also already ran "pip install click" successfully. This is the output from CMD:

D:\Docs\GitHub\discord-rpc>build.py unity
--- Building win32-dynamic
-- Selecting Windows SDK version 10.0.15063.0 to target Windows 10.0.16299.
CMake Error at CMakeLists.txt:2 (project):
  Failed to run MSBuild command:

    MSBuild.exe

  to get the value of VCTargetsPath:

    The system cannot find the file specified

-- Configuring incomplete, errors occurred!
See also "D:/Docs/GitHub/discord-rpc/builds/win32-dynamic/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "D:\Docs\GitHub\discord-rpc\build.py", line 313, in <module>
    sys.exit(cli())
  File "D:\Python\lib\site-packages\click\core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\core.py", line 697, in main
    rv = self.invoke(ctx)
  File "D:\Python\lib\site-packages\click\core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Python\lib\site-packages\click\core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Python\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "D:\Python\lib\site-packages\click\decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "D:\Docs\GitHub\discord-rpc\build.py", line 79, in unity
    just_release=True
  File "D:\Python\lib\site-packages\click\core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "D:\Docs\GitHub\discord-rpc\build.py", line 297, in libs
    build_lib('win32-dynamic', generator32, dynamic_options, just_release)
  File "D:\Docs\GitHub\discord-rpc\build.py", line 194, in build_lib
    subprocess.check_call(initial_cmake)
  File "D:\Python\lib\subprocess.py", line 291, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', 'D:\\Docs\\GitHub\\discord-rpc', '-DCMAKE_INSTALL_PREFIX=..\\install\\win32-dynamic', '-G', 'Visual Studio 14 2015', '-DBUILD_SHARED_LIBS=ON', '-DUSE_STATIC_CRT=ON', '-DCLANG_FORMAT_SUFFIX=none']' returned non-zero exit status 1.

Now i've re-cloned and reinstalled Python and The RPC several times to no difference. I've also tried restarting to update the path. I'm currently using dll's from [Here](https://github.com/discordapp/discord-rpc/releases/tag/v3.0.0) but I'd like to be able to build the dll's from the repo

Any help would be appreciated. 
-AdnascentiaV

P.S. I haven't ever used Cmake before. Python as well.
Specs:

I7 4790k
Evga GTX 1070
16gb ddr3

Versions:
Unity : 5.6.3p1
Cmake: 3.11.0
Python: 3.6.4 (32 bit)
VS: 2017
Github: 1.10
Git: 2.16.0.2

**Comment by msciotti** [comment]
After a quick google search, it looks like <https://stackoverflow.com/questions/44478492/cmake-failed-to-run-msbuild-command-msbuild-exe> is the most relevant answer. It seems the most common issue is that MSBuild is not properly in your PATH, especially if you're running straight `cmd` and not doing it in the visual studio command line which sets a bunch of env vars for you.

I'd recommend:

1. Try looking for the visual studio command line in your programs (just hit the windows key and start typing it) and using that instead

2. Install MSBuild.exe as the second comment in that SO thread suggests. Installing build tools for visual studios should prompt you to stick it in your path during installation. Then a restart of cmd (though I find powershell to be a bit more useful than vanilla cmd) should properly find the env variables and work as advertised.

**Comment by msciotti** [comment]
Haven't heard a response here, so I assume all is well. Please let me know if additional assistance is needed.
