### ISSUE TITLE
Linux Unity Support

### ISSUE THREAD

**Issue by srylain** [discordapp/discord-rpc#15]
In the Unity example, there is only a Windows DLL (Unity won't give options to include it with Linux). Will there be Linux support eventually?

**Comment by crmarsh** [comment]
You should be able to build dynamic libs on OSX & Linux in a similar way now, I just never got around to testing it in Unity there, or adding it to my build script.

**Comment by crmarsh** [comment]
Are you blocked on it not being pre-built, or is it broken in some other way?

**Comment by speedis** [comment]
Could perhaps some information be added on how to properly build the Linux and OSX versions?

**Comment by crmarsh** [comment]
The readme already has the basic steps to run cmake, which should be roughly the same on all platforms. If you want Unity support, you'll need to build the dynamically linked version (I think) so you'd do something like:
```sh
mkdir builds/dyn
cd builds/dyn
cmake ../.. -DBUILD_DYNAMIC_LIB=ON
cmake --build .
# see it is there on Linux:
ls -l src/libdiscord-rpc.so
```

**Comment by speedis** [comment]
Thanks, worked well to compile with that! :)

**Comment by msklywenn** [comment]
I managed to compile a linux version (see: https://github.com/msklywenn/discord-rpc) but it doesn't work. DiscordReady() gets called but nothing happens in the discord, be it the linux or windows client.
