### ISSUE TITLE
Ambiguity between presence.matchSecret vs presence.joinSecret

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#152]
What is the difference between these?

matchSecret = `unique hashed string for Spectate and Join`

joinSecret = `unique hashed string for chat invitations and Ask to Join   `

^ While matchSecret seems dominant for spectating and joinSecret can be an invitation to chat, **both mention join**. What situations would you use one another for join?

**Comment by msciotti** [comment]
The match secret is a deprecated field from a previous Notify Me feature that we skipped in favor of Ask to Join. The documentation did not clearly explain that this and the `instance` field should not be worried about at this time, but it is clarified with https://github.com/discordapp/discord-api-docs/commit/7f1dcc9f24cc490ae0ffa18c0b351a888b853ba6.
