### ISSUE TITLE
#question SELECT_VOICE_CHANNEL implementation

### ISSUE THREAD

**Issue by djrisc** [discordapp/discord-rpc#154]
It doesn't appear that this wrapper has any of the SELECT_VOICE_CHANNEL RPC implementation in place. Is this correct or am I missing something. Will this be coming soon? Just curious! Awesome work, I have this wrapper working just doesn't have the feature I'm looking for. (which is obviously the one above.) ;)

**Comment by msciotti** [comment]
Hey @djrisc! This repo only handles commands around Rich Presence, wrapped in our SDK. It does not touch the rest of our RPC commands, which require whitelisting to a program for which we are not currently accepting developers. Apologies for the confusion.
