### ISSUE TITLE
Steam custom game mod support

### ISSUE THREAD

**Issue by YaLTeR** [discordapp/discord-rpc#16]
Hello, as far as I can tell replacing `steam://run/` with `steam://rungameid/` in `Discord_RegisterSteamGame` makes it possible to additionally launch Steam custom game mods (which you can't launch otherwise because they don't have a Steam ID). This is important for me as I want to add support to a Half-Life mod which is not on the Steam store.

**Comment by crmarsh** [comment]
Looks like you fixed this and the warning thing in your fork, can you PR?

**Comment by YaLTeR** [comment]
Sure!
