### ISSUE TITLE
Discord not detecting Path of Exile

### ISSUE THREAD

**Issue by N0vac41n3** [discordapp/discord-rpc#160]
Hi Guys,

Just wondering why Discord isn't detecting PoE.
Here is a snip I took after looking around for people with similar issues.
![poe discord](https://user-images.githubusercontent.com/37101963/38024446-874c1794-32e1-11e8-9053-ac64e205e095.PNG)

Is there anything else you need or is there something I need to do to get it to detect?

Cheers.

**Comment by msciotti** [comment]
Hey N0vac. It looks like this is the non-Steam version of PoE. Which automatically detect stuff from Steam and other "trusted distributors"—like Origin, GOG, etc.—but standalone clients don't always play nicely.

You should send a support ticket to https://dis.gd/contact, they'll be able to get this information to the right people. This repo is just for Rich Presence stuff. Thank you!

**Comment by N0vac41n3** [comment]
Ok thanks msciotti, thanks for pointing me in the right direction.
