### ISSUE TITLE
[Feature Request] Allow clearing rich presence for a pid through the RPC's HTTP API

### ISSUE THREAD

**Issue by Tenrys** [discordapp/discord-rpc#164]
Right now, I'm dealing with Garry's Mod which does not provide a way for me to grab its process ID, so I pick a random one every time I update the rich presence I made for it. (yeah that's probably a terrible idea, but it's also the only one I could think of)

However, that creates an issue where the rich presence doesn't clear itself on game exit. Until a binding gets added for that on this side, is there a way currently to clear a rich presence through the HTTP API for the local RPC server? If not, could it be added? Apparently the C++ API has something like that, so there shouldn't be any problem with it, I think? (talking about `http://127.0.0.1:6463/rpc`)

I've tried sending an empty activity but the RPC server wouldn't accept it.

Thank you!

**Comment by MinnDevelopment** [comment]
Hey!

This worked for me:
```
curl \
-H 'content-type: application/json' \
-d '{"cmd": "SET_ACTIVITY","args": {"pid": 10521},"nonce": "0"}' \
"http://127.0.0.1:6463/rpc?v=1&client_id=382629176030658561"
```
As you can see I just omit the "activity" field, this resets the activity and removes the playing status as expected. I copied this behavior from [the source](https://github.com/discordapp/discord-rpc/blob/2ce9fe068bfb51a223465f57c29d15bf5f4f6336/src/serialization.cpp#L105).
**The pid and client_id may be different for your application.**

I'm unsure if this will clear the presence if no active connection is currently managing your presence through IPC but it works just like the SDK you mentioned.

Let me know if this is solves your issue.

**Comment by Tenrys** [comment]
I completely forgot to try that out, let's see

**Comment by Tenrys** [comment]
I don't know why I haven't thought of that before posting this, that seems to do the trick perfectly. Thank you!

**Comment by valeth** [comment]
This doesn't seem to work yet (?) on the regular Discord client, but works just fine on Discord Canary.

Looks like this when trying to clear it.
![screenshot_20180409_183838](https://user-images.githubusercontent.com/3198362/38510387-3a1813ea-3c25-11e8-9158-9920912124c0.png)

**Comment by amukh1** [comment]
> This doesn't seem to work yet (?) on the regular Discord client, but works just fine on Discord Canary.
> 
> Looks like this when trying to clear it. ![screenshot_20180409_183838](https://user-images.githubusercontent.com/3198362/38510387-3a1813ea-3c25-11e8-9158-9920912124c0.png)

Discord canary is pretty much discords test client

**Comment by samael-45** [comment]
> This doesn't seem to work yet (?) on the regular Discord client, but works just fine on Discord Canary.
> Looks like this when trying to clear it.

@valeth Have you tried `client.clearActivity();`
