### ISSUE TITLE
Not working when launching the game from Steam

### ISSUE THREAD

**Issue by kreesty** [discordapp/discord-rpc#168]
As the title says, I am using Unity and it always works if i play the game from the editor, but when we launch it from Steam, it doesn't connect with discord at all or something, because it won't display the state and details.

**Comment by kreesty** [comment]
It's been released for 3 good months. No, you can't run it like a standalone because it will just close down instantly and open up from Steam. ;P

**Comment by msciotti** [comment]
Fixed this offline. Had to do with Unity editor settings for the DLL. If you're experiencing similar issues, make sure your settings look like this:

https://cdn.discordapp.com/attachments/340203944179531787/438440226592129034/unknown.png
https://cdn.discordapp.com/attachments/340203944179531787/438440266509320193/unknown.png
