### ISSUE TITLE
Timestamps

### ISSUE THREAD

**Issue by ConCodeDC** [discordapp/discord-rpc#173]
Hello, how can I let the remaining time go backwards? So "elapsed time".

Thank you.

**Comment by Lachee** [comment]
To quote my documentation: 
When `Start Time` is included (not-null), the time in the rich presence will be shown as "00:01 elapsed".
When `End Time` is included (not-null), the time in the rich presence will be shown as "00:01 remaining". If `Start Time` is set, this value will override the "elapsed" state to "remaining".

**Comment by ConCodeDC** [comment]
So, if I understand that correctly, do not I have to specify `end-timestamp`? I'll test that. Give me a Second.

**Comment by MOBILORD** [comment]
I don't understand. Can you give code?

**Comment by WizardGoose** [comment]
> I don't got it. Can you give code?

This works fine for me :)
`
std::time_t CurrentTime = std::time(0);
discordPresence.startTimestamp = CurrentTime;
`
