### ISSUE TITLE
Unable to compile Unreal Example project

### ISSUE THREAD

**Issue by KiaArmani** [discordapp/discord-rpc#18]
Hello,

I am currently trying to get the Unreal Example running, but I am running into issues.
I have placed the .lib file in `\Source\ThirdParty\discordrpcLibrary\x64\Release`, but I get these errors when compiling

> Module.discordrpc.cpp.obj
>  : error LNK2019: unresolved external symbol __imp_Discord_Initialize referenced in function "public: void __cdecl UDiscordRpc::Initialize(class FString const &,bool,class FString const &)" (?Initialize@UDiscordRpc@@QEAAXAEBVFString@@_N0@Z)
> 2>Module.discordrpc.cpp.obj : error LNK2019: unresolved external symbol __imp_Discord_Shutdown referenced in function "public: void __cdecl UDiscordRpc::Shutdown(void)" (?Shutdown@UDiscordRpc@@QEAAXXZ)
> 2>Module.discordrpc.cpp.obj : error LNK2019: unresolved external symbol __imp_Discord_RunCallbacks referenced in function "public: void __cdecl UDiscordRpc::RunCallbacks(void)" (?RunCallbacks@UDiscordRpc@@QEAAXXZ)
> 2>Module.discordrpc.cpp.obj : error LNK2019: unresolved external symbol __imp_Discord_UpdatePresence referenced in function "public: void __cdecl UDiscordRpc::UpdatePresence(void)" (?UpdatePresence@UDiscordRpc@@QEAAXXZ)
> 2>C:\Users\Administrator\Downloads\discord-rpc-master(1)\discord-rpc-master\examples\unrealstatus\Plugins\discordrpc\Binaries\Win64\UE4Editor-discordrpc.dll : fatal error LNK1120: 4 unresolved externals

I tried to solve this by adding `PublicIncludePaths.Add(Path.Combine(ModuleDirectory, "Include"));` to `discordrpcLibrary.Build.cs` and copy `discord-rpc.h` from the include dir into it, but it still won't find it.

How does one resolve this error? It looks like it doesn't find the additional header file to me.
I am using the win64-static lib.

**Comment by rojo8399** [comment]
+1
Been trying to get the Unreal Project working also.
Hopefully they can update it to 4.18, too.

**Comment by KiaArmani** [comment]
Seems that you need to use the **dynamic** .lib file in order to compile the project.

**Comment by KiaArmani** [comment]
After trying to launch the compiled project I get an error message that the module discord-rpc could not be loaded, so there seems to be another issue here or using the dynamic lib file was the wrong approach.

**Comment by KiaArmani** [comment]
https://i.imgur.com/zqwTYhw.png Works now.

Need to place the .dll in Binaries/ThirdParty/discordrpcLibrary/Win64/discord-rpc.dll

**Comment by rojo8399** [comment]
@KiaArmani Could you type out what needs to go where?

**Comment by rojo8399** [comment]
For anyone else with this issue, just drag this folder onto your plugin's folder, then rebuild the project.
[discordrpc.zip](https://github.com/discordapp/discord-rpc/files/1461195/discordrpc.zip)

**Comment by crmarsh** [comment]
I should probably update build.py to copy that file into the right places for the samples.

**Comment by Jigosystems** [comment]
For anyone wondering how to get it to work in a packaged ue4 build here is how to do it:
1. Edit the discordrpc.uplugin file in a text editor and change the type from "Developer" to "Runtime" under modules.
2. Package your build
3. In your packaged game folder, go under the folder that has your game name (where binaries, content, and saved folders are) and create a folder called "Plugins".
4. Create the following directory under the "Plugins" folder "discordrpc/Binaries/ThirdParty/discordrpcLibrary/Win64"
5. Place the discord-rpc.dll file in the Win64 folder and then you are done! :D
Hope this helps everyone.﻿

**Comment by Valkyrie121** [comment]
Yea, the plugin seems to not work in staged/packaged build even tho the plugin is loaded.

**Comment by Mootjuh** [comment]
So any progress on doing this automatically?

**Comment by msciotti** [comment]
Though we don't have it working automatically, I'm going to close this issue as it was resolved. I'll open a new feature request to make our build script work properly in UE4 like it does with unity.
