### ISSUE TITLE
RPC disappearing after an hour plus other issues

### ISSUE THREAD

**Issue by SgtBreadStick** [discordapp/discord-rpc#181]
Hello,
I'm having some issues with discord-rpc, after around an hour the rich presence reverts to the normal game of Euro Truck Simulator 2 playing status until it is restarted, information is sent every 15 seconds and other stuff sent at 1-3 minutes, we have a repository on github with it too. 

I've also noticed that when the game is closed with the rpc in the background, it just says "Playing Euro Truck Simulator 2" but with no played for X minutes or X hours and stays like that until the rpc is closed or restarted, even though we have the rpc destroy function on when the game is closed.

Example: [https://i.imgur.com/3K2AaiE.png](https://i.imgur.com/3K2AaiE.png)

Our Repo: [https://github.com/VirtualTruckerRPC/Virtual-Trucker-Rich-Presence](https://github.com/VirtualTruckerRPC/Virtual-Trucker-Rich-Presence)

Regards,
SgtBreadStick.

**Comment by msciotti** [comment]
Thank you for reporting this issue. I've seen this across a couple integrations now, so something is up. I have a feeling this will be one of those hard to catch bugs, but I'm glad to know it seems to be a more general issue than integration specific.

I'll start hunting this down; thanks!

**Comment by SgtBreadStick** [comment]
I found the issue about discord stating the game is still running even when it isn't, just a spelling mistake caused an issue and didn't destroy the rpc haha. But it still times out :) I hope you manage to find a fix with the disappearing rich presence.

**Comment by SgtBreadStick** [comment]
Any progress so far? :)

**Comment by msciotti** [comment]
I have not been able to reproduce this using the examples in this repo. I've let it go for up to 6 or so hours, and it stays without issue. Sorry I didn't report back on this sooner.

Unfortunately, that's the same conclusion I've come to with others who have had this issue.

I will try again today. Could you see if the same issue happens if you use the unity example here?

**Comment by LaxZ** [comment]
Hey,
I have this problem also.

@msciotti Did you tried it with Euro Truck Simulator 2? My thought is, that ETS2 is the problem. There must be something wrong. It only happens with SCS Software Games.

**Comment by msciotti** [comment]
I've not tried with Euro Truck Simulator 2, no. What I'll do is test locally with our test app for the hour and see what happens—if it looks fine, I'll try it with ETS2 and one of your guys' mods. If that fails, it's most likely an implementation/game issue, but I don't know what it would be.

**Comment by msciotti** [comment]
OK, I've had my rich presence testing app running for about 4 hours now, and it's still going strong. So the short of it is that this is an implementation issue, but what the issue is, I can't say for sure. My next step will be trying your applications.

**Comment by SgtBreadStick** [comment]
Alrighty, seems pretty strange as every version i do i always update everything i can.

**Comment by msciotti** [comment]
Appreciate the added information. The only steps I have next are to try and test one of the broken integrations locally and see what's up. I've been out of the office and so haven't had time to debug, but I can see what I can find by perhaps the end of the week.

**Comment by msciotti** [comment]
Uh, I don't think so, but I'm super happy to know that it's all good for you now 😄 I assume that the others here are still having the issue, so I'll keep this on a TODO list.

**Comment by SgtBreadStick** [comment]
Well the problems seem to be fixed on our end. Thanks for the fix! :D

**Comment by msciotti** [comment]
2/3 ain't bad so far! If @LaxZ can confirm as well, I'll happily call this closed.

**Comment by LaxZ** [comment]
Yes, Its fixed! Thanks!
