### ISSUE TITLE
Discord_Shutdown() doesn't clear the presence.

### ISSUE THREAD

**Issue by Megamouse** [discordapp/discord-rpc#184]
Calling Discord_Shutdown (or Discord_ClearPresence followed by Discord_Shutdown) without closing the app does not clear the presence.
Using Discord_ClearPresence works fine by itself.

On another note: How does the current implementation handle 2 calls to Discord_Initialize ?

**Comment by msciotti** [comment]
`Shutdown()` is not intended to clear the user's presence—that's what the `ClearPresence()` function is for. `Shutdown()` closes the IPC connection to the local Discord client, whereas `ClearPresence()` sends an empty activity payload to clear the presence and un-pin the process id.

By calling Shutdown in quick succession after ClearPresence, you're probably destroying the connection before the activity payload can be sent, hence the presence not clearing.

As far as handling multiple `Initialize()` calls, you can check out the source code! If we detect a connection is already open, we just ignore the new attempt:

https://github.com/discordapp/discord-rpc/blob/master/src/discord_rpc.cpp#L305

**Comment by FireController1847** [comment]
So... what's the correct way to clear the presence when the program closes then?

If we can't called ClearPresence and then Shutdown right after one another, what do we do?

**Comment by Megamouse** [comment]
#189
