### ISSUE TITLE
Discord_UpdatePresence - clears state?

### ISSUE THREAD

**Issue by vadi2** [discordapp/discord-rpc#185]
Hi, 

Can I keep updating my `DiscordRichPresence` object and just call `Discord_UpdatePresence()` on it as needed? It seems the objects state is being cleared, so I'm wondering if I'm doing right or external status tracking is required.

**Comment by msciotti** [comment]
Hi there vadi,

Whether or not the object's state is cleared would be dependent on your implementation, I suppose. If you're using the same instance of a `DiscordRichPresence` object throughout your game, it should retain state; if you're making new objects, they'll obviously be new.

**Comment by vadi2** [comment]
I'm keeping it around, but it's being cleared - will look into this. Thanks for the quick reply!

**Comment by vadi2** [comment]
For anyone else implementing this using Qt, here's sample code:

```cpp
void Discord::UpdatePresence()
{

    DiscordRichPresence discordPresence;
    memset(&discordPresence, 0, sizeof(discordPresence));

    char buffer[256];
    buffer[0] = '\0';
    auto gameName = mGameName.toLower().toUtf8();
    auto status = mStatus.toUtf8();
    auto smallIcon = mSmallIcon.toLower().toUtf8();
    auto smallIconText = mSmallIconText.toUtf8();
    if (!mGameName.isEmpty()) {
        sprintf(buffer, "Playing %s", mGameName.toUtf8().constData());
        discordPresence.details = buffer;
        discordPresence.largeImageKey = gameName.constData();
    }

    if (!status.isEmpty()) {
        discordPresence.state = status.constData();
    }

    if (!smallIcon.isEmpty()) {
        discordPresence.smallImageKey = smallIcon.constData();
    }

    if (!smallIconText.isEmpty()) {
        discordPresence.smallImageText = smallIconText.constData();
    }

    auto timestamp = static_cast<int64_t>(std::time(nullptr));
    discordPresence.startTimestamp = timestamp;

    discordPresence.instance = 1;
    Discord_UpdatePresence(&discordPresence);
}
```

**Comment by SlySven** [comment]
Ah, @vadi2 - the `discordPresence` is local to this function/method - so each time you call `UpdatePresence()` a new instance is passed to the `Discord_UpdatePresence(`...`)` invocation.

Also the `discordPresence.startTimestamp` needs to be set to a time where whatever is being timed started (or `0` apparently to turn it off) as it is the difference between the fixed time and the *current* time at the point that the Discord RPC library works out what it is, is what is shown as the "Elapsed" time in the Discord Rich Presence display - all that the two lines dealing with that does is constantly set the elapsed time to be pretty much the current time so - give the resolution of the time display will never show *any* time has elapsed....

*For the record *Vadi* and I are co-coders on a project which is trying to integrate Discord Rich Presence support at this time...*
