### ISSUE TITLE
build.py error

### ISSUE THREAD

**Issue by DopeDealers** [discordapp/discord-rpc#188]
When running the py script there is an error for the module/click

`py build.py unity
Traceback (most recent call last):
  File "build.py", line 4, in <module>
    import click
ModuleNotFoundError: No module named 'click'`
even tried organizing the imports,

any suggestions would be much appreciated

**Comment by kkirigaya** [comment]
Try installing `click` using `pip`:

    pip install click

**Comment by DopeDealers** [comment]
thank you @kkirigaya that worked,
