### ISSUE TITLE
[Question] g++ Linker not recognising discord-rpc.lib / functions inside discord_rpc.h

### ISSUE THREAD

**Issue by OhhLoz** [discordapp/discord-rpc#190]
Hello,

This is probably an easy question but it has stumped me for a few days now and decided I can't seem to solve it so I am asking for some help.

I'm writing a small C++ program to run rich presence for a game for which it doesn't already exist, I believe it would work if I was able to compile it, however whenever I attempt to do so, it says that there are undefined references to some functions that are declared within the discord_rpc.h and I presume are defined within discord-rpc.lib (Discord_UpdatePresence, Discord_Initialize, Discord_Shutdown).

These errors seem to be down to the linker not being able to locate the three functions above despite my attempts at linking the static library discord-rpc.lib using the g++ -L or -l flag. Perhaps I have misunderstood how to use the header and library files. It was my understanding that the header file should be #included much like any header file, this is done within the header of the .cpp file that uses the 3 functions that aren't found by the linker.

Any help would be appreciated & I can easily answer any confusions from my post.
Thank you!

p.s. I also wanted to ask a quick question about how assets are handled, for instance, is it possible to have an asset that can be referenced by anyone using an id (like clientid or appid) or does each user have to create an application through the discord website and upload the assets individually.

**Comment by OhhLoz** [comment]
Please can anyone help?
I still cant get the library working.
Thanks

**Comment by kkirigaya** [comment]
Hey there OhhLoz,

I unfortunately cannot answer your main question (as I have no experience with C++), however I can answer your second question. Assets (accessed with `largeImageKey` and `smallImageKey`) are uploaded by the owner of the application, not the users. The purpose of rich presence is that it's hands-free for the user; it's supposed to be 100% done programmatically. 

I hope someone will be around soon to help with your main problem soon. Best of luck!

**Comment by OhhLoz** [comment]
Hey,

Thanks for the response,
So when I create an application in the developer section i.e (https://discordapp.com/developers/applications/me), as long as the person has the ID associated with that application then they can access the same assets assuming they use the correct largeImageKey & smallImageKey.

Thanks again!

**Comment by OhhLoz** [comment]
Ah cool thanks a lot, I hoped that would be how it worked. That makes things easier.
Now just hoping they will allow uploading of images dynamically instead of manually in the future but that's another matter entirely.
Thanks for the reply!

**Comment by kkirigaya** [comment]
No problem! Uploading assets dynamically via a hash has been suggested [here](https://github.com/discordapp/discord-rpc/issues/70), if you want to weigh in on it. 😄

**Comment by OhhLoz** [comment]
Thanks, I saw that issue when I was browsing for solutions to mine, they also mentioned programmatically adding images in the [FAQ](https://discordapp.com/developers/docs/rich-presence/faq#q-can-i-send-images-via-the-payload-rather-than-uploading-them-to-my-developer-dashboard) where they said they might tackle it in the future. I hadn't thought about commenting on it but I'll be sure to do that now. :)

**Comment by msciotti** [comment]
Apologies for letting this slip. kkirigaya is correct in how the images work—you need to upload them to your dashboard and reference the keys in the code. There are not currently any plans to allow for dynamic asset uploading, unfortunately; that stance remains as is.

As for the g++ linking, I similarly do not have experience using g++, unfortunately.

It also seems more like a question of how to properly statically link things with g++ than a question/issue with this library specifically. You're probably better off asking/looking for help somewhere like SO?

I'm going to close this issue, as I do not believe it is specific to the Rich Presence library. Feel free to re-open if you believe I am wrong; others that see this, please do feel free to comment and help if you know the answer offhand.

**Comment by OhhLoz** [comment]
Hi,

Whilst I was using g++ to compile, I was having similar issues as with CLion. I was having trouble following the installation instructions for installing by package, i.e. which packages (dynamic/static) do what & what send_presence.exe is used for.

I had already tried to solve the issue and find answers online (hence the -l to try to link libraries), I just wanted to know how to actually connect the source files to the library. Whether by repo/CMake is best or package will work fine (mine is only a small program so I chose by package). I just want to know the general way of going about things if thats ok.

Thanks

**Comment by msciotti** [comment]
The `send_presence.exe` is just a sample C app so you can see how stuff runs. I may be a bit ignorant suggesting this, but it sounds like you probably want to just pull a release from this repo? Or are you doing that already?

From there, you'll want the `discord_rpc.h` and `discord_register.h` header files to go along with `whatever-dll-you-picked.dll/lib/dylib/a/so`.

**Comment by OhhLoz** [comment]
Thanks for the reply, 

I had already downloaded discord_rpc.h (which is already being included) and discord_register (not included in my code - changing this doesn't seem to work either).
I chose the static version for windows which just has a .lib file with no .dll I assume thats ok.

When I include the libraries at the start of the compilation statement I get 3 errors about the functions I am trying to use (`Discord_UpdatePresence`,` Discord_Initialize`, `Discord_Shutdown`) but if a put the library includes at the end of the g++ statement I get a bunch of [garbled mess](https://pastebin.com/XiVc1EhK) I cant make sense of.

Am I doing something wrong? I haven't directly pulled a release from this repo so I will try that but I'm not hopeful.

**Comment by msciotti** [comment]
Well, the library does depend on the `discord_register.h` file, so you will want that. You should try pulling a release directly—always the safest/path of least resistance.

Aside from that, it seems like an issue in knowing how to properly link stuff with g++, of which I am ignorant. So, unfortunately, I can't be of much more help here 🙁

**Comment by OhhLoz** [comment]
Thanks for your help anyway,
I'll keep trying
