### ISSUE TITLE
[Fix Request] Having an Invalid smallImageKey causes both the largeImage and smallImage to not display

### ISSUE THREAD

**Issue by CDAGaming** [discordapp/discord-rpc#194]
While working on an App including DiscordRPC, I noticed that with an Invalid Key for the Small Image, itll fail to display the large and small Image, when It should only cause the Small Image to stop working.

Referenced Issue: https://github.com/MinnDevelopment/java-discord-rpc/issues/26

**Comment by msciotti** [comment]
ACK on this issue. Don't have an ETA for a fix as this is below other things in priority, but I'll see if I can do something quick or if this is more involved 👍

**Comment by msciotti** [comment]
Good news! Just merged a fix for this. Should roll to various clients within a day or two. An invalid small image key should no longer block the large image.

Note that if you send a bad _large_ image, artwork will not display, as the small image will have nothing to anchor to.

**Comment by CDAGaming** [comment]
Thanks so much :)
