### ISSUE TITLE
background color

### ISSUE THREAD

**Issue by norkdev** [discordapp/discord-rpc#198]
I cant find anything about this... Its possible to make background color like Spotify and Xbox One?

![jez-discord-xbox-integration](https://user-images.githubusercontent.com/22281911/42062247-692783f6-7b03-11e8-81a8-8af3ef561c8b.jpg)

**Comment by kkirigaya** [comment]
AFAIK it's not possible to change the colour of the information on the client. Maybe one of the devs can let us know if it's planned or not. 😄

**Comment by msciotti** [comment]
Right now, no, we do not support changing the background color unfortunately. There's no plans to build it out right now, but we can certainly keep it in mind!

**Comment by norkdev** [comment]
Thanks guys!

**Comment by StaticGamerYT-India** [comment]
wtf

**Comment by StaticGamerYT-India** [comment]
so how this guy did ? 
![image](https://user-images.githubusercontent.com/77852984/106031768-a798e000-60f5-11eb-9063-c43fe5b755c1.png)

**Comment by greg6775** [comment]
Did you get this screenshot from https://community.stadia.com/t5/Stadia-General/Stadia-Discord-Integration-and-Rich-Presence/m-p/22988 ?

**Comment by StaticGamerYT-India** [comment]
> Did you get this screenshot from https://community.stadia.com/t5/Stadia-General/Stadia-Discord-Integration-and-Rich-Presence/m-p/22988 ?

Yes

**Comment by m-sterling** [comment]
@StaticGamerYT-India Well, Xbox and other services partnered with Discord have special modals for their rich presence information. There's no way for us to make our presences look like these as it's restricted to Xbox, Spotify, etc. Stadia isn't currently partnered with Discord, so that's just concept art.

**Comment by greg6775** [comment]
He probably just modified the Discord code to take this screenshot

**Comment by m-sterling** [comment]
@GregTCLTK Yep, you're right. Stadia isn't partnered with Discord so that's just a fan-created concept.
