### ISSUE TITLE
[Request] Pass additional data along with a Join request, such as SteamID

### ISSUE THREAD

**Issue by coty-crg** [discordapp/discord-rpc#199]
would be useful

**Comment by Lachee** [comment]
that information can be encoded into your join secret

**Comment by night** [comment]
what Lachee stated is correct.

**Comment by coty-crg** [comment]
Well no, because the join request wont contain the secret of the other user. 

If User A is hosting a party and User B selects "ask to join" - then User A will get a join request. But User A has no way of knowing User B's SteamID. So, the only choice User A has is to accept any network request from the next SteamID that asks, which is sort of a vulnerability for Steam users.

**Comment by msciotti** [comment]
Maybe I'm misunderstanding, but it seems like the auth is a bit backwards in your case?

If I've got a Steam game that only a certain criteria of people can join—maybe the game is password protected—that password/key to join should be encoded within the `joinSecret`. That way someone who wants to play:

- Launches the game
- Gets the join secret
- Has their client decode the secret to whatever special information is needed to join the game
- Gives that info to the lobby to which they're connecting
- Is denied/accepted

Perhaps there's a case of game that I'm not understanding?

**Comment by night** [comment]
Join secrets are generally a secret value representing the lobby a user can join into. While you can store metadata with the join secret to assist your game in locating the player's lobby, you cannot rely on the information being genuine (non-forged) without some form of encryption or backend server component. In general, if join secrets are implemented this way you shouldn't have to worry about user b's steam id since they used a secret value that can be validated as genuine.

**Comment by coty-crg** [comment]
But what about this case, where the session is entirely peer to peer, it is still useful to know the steamid of the player requesting to join, so then you will only allow incoming connection requests from that steamid.

**Comment by msciotti** [comment]
If you are really concerned about validating a user's steamid, it can be done, albeit with some additional work.

When the SDK starts up, you get the user object of the connected user in the `read` callback. You could, if you wanted, store the mapping between steamid <--> discordid. Then, when someone Asks to Join, go find the steam id for that discord id and anticipate their joining.

I get your use case, but I think additional "auth" outside what is capable with the secrets is out of scope of SDK enhancements, and should be handled by individual developers.

**Comment by coty-crg** [comment]
I'm afraid I don't follow. How would you go about storing the mapping for the other player wanting to join? The problem is I don't see a way to get this info without having to host a server myself that relays this data

**Comment by night** [comment]
There's unfortunately not a way to do it without your own server. Discord doesn't have a user's steam ID just because they launch a steam game. We only have a user's steam ID if they link their Steam account to Discord, which is not required.

**Comment by coty-crg** [comment]
Right, which is why I was requesting allowing us to send over a string along with the join request.

**Comment by msciotti** [comment]
After re-reading this a few times, I think maybe I'm misunderstanding your question. This stuck out to me:

> User A's only information they're given is the discord ID and name of the user requesting to join their session. They have no way of knowing what that discord user's steamid is, though. They hit accept anyways

Is your concern that User A _doesn't know who User B is when they get the request?_

If so, note that in order for Ask to Join to work, you need to be friends on Discord. If Users A and B are friends on Discord, I think it's fair to assume they'd know who the person is requesting to join.

**Comment by coty-crg** [comment]
This is true, however it leaves a moment in time between the requests where anyone can connect to that users steam session, because User A doesnt have User B's steamid on hand, they just have to "trust" the next steam network request.

**Comment by Lachee** [comment]
I am not familar with the Steam MatchMaking API, but I would imagine it would have a way to password protect games. If userC tried to connect, they wouldn't be able to because they dont have the password. You can then pass the password to userB via the JoinSecret, and they can use that to connect.

**Comment by msciotti** [comment]
Yeah I think that's really the heart of it. If you're concerned about "anyone" joining the game that shouldn't be there, it should be password protected in some way, and that password should be sent as the joinSecret. If someone else also happens to have the password and joins "ahead" of User B...not really an issue I guess, since they have the password, so should be in the game anyway.

**Comment by Lachee** [comment]
And if you are worried about avatars mismatch, OnReady gives a user object that you can tell the host about after you connect. OnReady will be called before the JOIN event
