### ISSUE TITLE
[discordapp.com "bug"] - tiny icon's minimum size is 512x512

### ISSUE THREAD

**Issue by coty-crg** [discordapp/discord-rpc#206]
![tiny icon](https://i.imgur.com/n6gWdKY.png)

![tiiiiiny](https://i.imgur.com/OrvP26i.png)

kind of silly that this tiny tiny icon should be 512 minimum on the website. oversight maybe?

**Comment by night** [comment]
this is not considered a bug. large images are used to future proof future uses of these uploaded assets.
