### ISSUE TITLE
Impossible to specify an empty party

### ISSUE THREAD

**Issue by SlySven** [discordapp/discord-rpc#212]
If the RP **`partySize`** is set to zero the party details disappear - even when the **`partyMax`** is non-zero. So, for instance it is not possible to set a party size of **`(0 of 9)`**.  Whilst I guess the *normal* usage as a party may be expecting the party to always to include the user on which it is displayed so as to have a minimum of **`1`** - it could be useful for other things like a progression count - in that usage the ability to show the zeroth count value is also required:
![screenshot_20180731_161529](https://user-images.githubusercontent.com/6163092/43469138-6d26adc6-94dd-11e8-99ae-fd92956f333e.png)
![screenshot_20180731_161643](https://user-images.githubusercontent.com/6163092/43469137-6ce1b464-94dd-11e8-894a-e5ac037df07f.png)
![screenshot_20180731_161728](https://user-images.githubusercontent.com/6163092/43469135-6cad693e-94dd-11e8-9888-0c7ea1702ce2.png)
![screenshot_20180731_161746](https://user-images.githubusercontent.com/6163092/43469134-6c6b047c-94dd-11e8-9a50-cba89e45eaec.png)
I would suggest that only setting the **`partyMax`** value to **`0`** should cause the party information to not be shown - this manifests in both the vanilla and PTB Discord versions on Linux...

**Comment by msciotti** [comment]
The party values have a pretty specific use case, in that they enable players to use the join features of Rich Presence. They tell Discord when a user should be able to post an invite into chat, how many slots that invite should have open, and when it should be locked until someone leaves.

I understand your use case, but I'd recommend for things like a bug ticker (in your example), you should code it directly into the state string if representing 0 is crucial.

**Comment by SlySven** [comment]
Okay, I'll note it in the details for our implementation of bridging protocol(s) between a Mud Server ==> Our Mud Client ==> Discord RP RPC library.
