### ISSUE TITLE
Advanced UE4 functional

### ISSUE THREAD

**Issue by ANTEVETY** [discordapp/discord-rpc#214]
Hey. I'm just starting to develop the game on UE4 and besides we will have our own backend system with registration only through discord. This is necessary because you are cool) and a lot of logic is tied to deep. I would like to ask you about additional functionality in the plugin for UE4. Need to get audio stream directly in ue4 when new negotiations to produce it in the right place in the world. This gives the game an unprecedented realism when communicating players (similar implemented in ARMA 3 with TeamSpeak). If you can implement it in future versions, I think it will help not only our game, but also many others who do not want to implement TeamSpeak. My knowledge is not enough to implement, while only one variant of the discord.js+ue4 tcp local connection+our launcher(nw.js) and reading the file at the right time)

**Comment by msciotti** [comment]
Hi there,

Right now, there are no plans to implement voice chat in the Rich Presence SDK. We love the idea of using Discord accounts as your auth system—for sure we support that! But right now, voice chat is limited to using our app, and the plan is to keep it that way for the foreseeable future.

Thank you for the suggestion!
