### ISSUE TITLE
Destination Array Not Long Enough

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#218]
I have this sample 128-bit encoded string:

`"L4qRz+4LD21QLEebBZiLbs0mXIvDw7plPVqMtrJ6YRwd2QtOd/C6fBTxIq6VZcfI1iv8pTy3T50sF0xlE1i8U0Cv7EKCJYhxfQYpUe8j9U1rZmnrUy4o3M49l73fl8IK"`

When this was passed to StrToPtr for joinSecret:

`_presence.joinSecret = StrToPtr(joinSecret, 128);`

An error is thrown for:

```
[Discord]**ERR @ UpdatePresence: System.ArgumentException: Destination array was not long enough. Check destIndex and length, and the array's lower bounds
```

However, a character counter showed that it was exactly 128. What's going on?

**EDIT**: I am using the official Unity wrapper example. It seems that the issues are coming from here when converting the encoded string to C++ form:

https://github.com/discordapp/discord-rpc/blob/master/examples/button-clicker/Assets/DiscordController.cs#L36

https://github.com/discordapp/discord-rpc/blob/master/examples/button-clicker/Assets/DiscordRpc.cs#L157

The main error is @ UpdatePresence:

```csharp
public static void UpdatePresence(RichPresence presence)
{
    var presencestruct = presence.GetStruct();
    UpdatePresenceNative(ref presencestruct);
    presence.FreeMem();
}
```

**EDIT 2:** I am seeing multiple answers across the web saying "These functions are _not likely thread-safe_. Could this be a possibility? If so, does that mean this would be a _Discord_ (this repo) issue rather than my own issue?

**Comment by msciotti** [comment]
Is this using our SDK, or a wrapper/reimplementation?

**Comment by MinnDevelopment** [comment]
I am not exactly sure where you are getting this function from but keep in mind that C requires an additional null-terminator at the end of the string. It could cause this to fail because the actual representation requires 129 bytes instead.

**Comment by msciotti** [comment]
^ also very possible, yes

**Comment by dylanh724** [comment]
Ah, I forgot to mention - yes, this is a C# wrapper within Unity. Sometimes it works, sometimes it doesn't. How can I "add an additional null-terminator at the end of the string"? I tried Googling this, but it's difficult to find a good answer.

**Comment by MinnDevelopment** [comment]
Note the description of `maxbytes` 
> max bytes the resulting string should have (including null termination)

This means that the maxbytes are the 128 characters however with the additional null terminator added it becomes 129 so the destination array cannot actually hold the entire string. Your string of 128 characters requires 129 characters when represented as a c-string which means it fails copying it over.

**Comment by msciotti** [comment]
OK, so our string -> pointer stuff here is...wrong, lol. I'm gonna go fix that. Won't close this quite yet.

**Comment by dylanh724** [comment]
You guys are awesome ;D thanks
