### ISSUE TITLE
Crashing after handlers run with non-Unity C#

### ISSUE THREAD

**Issue by nathan130200** [discordapp/discord-rpc#220]
I'm using CSharp version to Discord-RPC Native, no handlers are fired.

```cs
var Handlers = new EventHandlers();
Handlers.readyCallback = OnReady;
Handlers.errorCallback = OnFail;
Handlers.disconnectedCallback = OnFail;

DiscordRpc.Initialize("479021344625917953", ref Handlers);

Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(false);

DiscordRpc.RunCallbacks(); // Does nothing too.
DiscordRpc.UpdatePresence(new RichPresence
{
    largeImageKey = "ct_survival",
    state = "Missão: The Great White",
    details = "Sobrevivência: Difícil",
    startTimestamp = Utilities.GetUnixTimestamp()
});

Application.Run();

static void OnReady(ref DiscordUser self)
{
	MessageBox.Show($"[DiscordRpc]: Connected. {self.username}#{self.discriminator} ({self.userId})", "", MessageBoxButtons.OK, MessageBoxIcon.Information);
}

static void OnFail(int code, string msg)
{
	MessageBox.Show($"[{code}]: {msg}", "", MessageBoxButtons.OK, MessageBoxIcon.Error);
}
``` 

Nothing occurs, rpc just initialize and keep running.

**Comment by Lachee** [comment]
Have you made sure to call RunCallbacks numerous times throughout your code? You cannot only call it once.

**Comment by nathan130200** [comment]
In cause, i can Call RunCallbacks every second?

**Comment by Lachee** [comment]
yes that is fine.

**Comment by nathan130200** [comment]
Thanks for information.

**Comment by nathan130200** [comment]
Ok i have another problem, RunCallbacks don't throw an exception but closes my C# application without reason.

**Comment by nathan130200** [comment]
My rpc code, i'm using Windows Forms

```cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Text;
using System.Threading;
using System.Windows.Forms;
using WarfaceRichPresence.Interop;

namespace WarfaceRichPresence.Forms
{
	public partial class MainForm : WarfaceRichPresence.Forms.BaseForm
	{
		public DiscordUser Self;
		public EventHandlers Handlers;
		public Thread RunCallbacksThread;

		public MainForm()
		{
			InitializeComponent();
		}

		public void Log(string message)
		{
			if (tbLog.InvokeRequired)
				tbLog.Invoke(new Action<string>(Log), message);
			else
			{
				tbLog.AppendText(message + Environment.NewLine);
			}
		}

		void MainForm_Load(object sender, EventArgs e)
		{
			Handlers = new EventHandlers();
			Handlers.readyCallback = OnReady;
			Handlers.errorCallback = OnError;
			Handlers.disconnectedCallback = OnDisconnect;

			DiscordRpc.Initialize("479021344625917953", ref Handlers);

			RunCallbacksThread = new Thread(() =>
			{
				while (true)
				{
					DiscordRpc.RunCallbacks();
					Thread.Sleep(1500);
				}
			});

			RunCallbacksThread.Start();
		}
		
		void OnReady(ref DiscordUser user)
		{
			this.Self = user;
			Log($"[DiscordRpc] Conectado ao RPC do discord como {this.Self.username}#{this.Self.discriminator}");
		}

		void OnError(int code, string message)
		{
			Log($"[DiscordRpc] {code}: {message}");
		}

		void OnDisconnect(int code, string message)
		{
			Log($"[DiscordRpc] {code}: {message}");
		}
	}
}
```

**Comment by nathan130200** [comment]
Not yet, i'm trying to create a C# direct pipe client to discord rpc without native.

**Comment by msciotti** [comment]
I cannot reproduce this when using the Unity example that's currently in master. I am able to run callbacks without anything crashing, and I successfully receive Ready and Ask to Join callbacks when interfacing with another client.

![image](https://user-images.githubusercontent.com/4193854/44559072-6f0ea400-a6fc-11e8-9a40-58c5355fadb7.png)

Does the Unity example in the repo work for you? If so, it may just be an implementation/DLL linking issue, or weird behavior with Windows Forms?

**Comment by Lachee** [comment]
If you are running a WinForm, it is worth while mentioning that its not thread safe. If you want to update a UI element, you will need to do it from a UI thread. (Not sure what your Log function is doing, but if it is updating a TextBox that could be potentially why its crashing).

As for the C# pipes, they work just fine for the RPC, but make note they will not work within Unity3D. A native library is required for the unity engine.

**Comment by nathan130200** [comment]
@Lachee My Discord RPC don't interact with form, is inside a thread. And Log is thread safe (InvokeRequired), application just close without any exception throw by Visual Studio. Console application too. I'm with same code in unity example.

**Comment by nathan130200** [comment]
@msciotti Application just close with strange exit code, no exception is throwed in application. When i remove RunCallbacks line in code, don't crash application.

**Comment by nathan130200** [comment]
Note: Java library that uses native discord-rpc.dll too don't fire handlers when RunCallbacks is invoked, but don't crash.

**Comment by msciotti** [comment]
Is the exit code from your application, or from trying to run the Unity example? 

Can you paste the exit code here? 

If you open up the console in Discord - control + shift + i - when you try and run the code, do you see any errors?

**Comment by nathan130200** [comment]
@msciotti Don't receive erros and exit code is `The program '[12828] WarfaceRichPresence.exe' has exited with code -1073740940 (0xc0000374).`

**Comment by FayneAldan** [comment]
I've been having the same problem. However, I *just* realized you can get an error message if you run your program in debug mode. This is the error I got:
```
Managed Debugging Assistant 'CallbackOnCollectedDelegate' 
  Message=Managed Debugging Assistant 'CallbackOnCollectedDelegate' : 'A callback was made on a garbage collected delegate of type 'SVRichPresence!DiscordRpc+ReadyCallback::Invoke'. This may cause application crashes, corruption and data loss. When passing delegates to unmanaged code, they must be kept alive by the managed application until it is guaranteed that they will never be called.'
```

I have no idea what it means, however... :/

**Comment by FayneAldan** [comment]
Well, I moved my handlers object so it's not garbage collected. However, now it's crashing without any exceptions. Debug mode doesn't pick up anything. Error in the library?

**Comment by FayneAldan** [comment]
After some debugging, I found that my code crashes after the ReadyCallback is run. Here is my code if it helps: https://github.com/FayneAldan/SVRichPresence/compare/callbacks

**Comment by MinnDevelopment** [comment]
The disconnect callback is currently bugged because the library removes the event handlers when it disconnects, this is fixed in #228

**Comment by nathan130200** [comment]
@FayneAldan same here, crash without exception, i really think that is a discord-rpc library issue, not our code.

**Comment by FayneAldan** [comment]
I tried using the [latest CI build](https://ci.appveyor.com/project/crmarsh/discord-rpc/build/276/artifacts) and it didn't work either.

**Comment by FayneAldan** [comment]
I made a [simple console application](https://github.com/FayneAldan/RichPresenceTest/releases/tag/test1) in C# to test the issue. As expected, the compiled program crashes after the ready callback. Unless there's something wrong with [my code](https://github.com/FayneAldan/RichPresenceTest), I'm pretty sure it's an issue with the library... or the C# wrapper.

**Comment by msciotti** [comment]
Are you guys using one of the releases, or compiling the source yourself? This is very strange, as both work perfectly fine when testing on the default Unity example in this repo on macOS. I'll try on my windows machine today with both the latest master build and what's in releases.

**Comment by nathan130200** [comment]
I'm using latest discord-rpc release and don't work, just crash when call RunCallbacks...............

**Comment by msciotti** [comment]
I’ll test a basic C# and windows form app today then.

**Comment by FayneAldan** [comment]
@msciotti I have tried both the official release and [this CI build](https://ci.appveyor.com/project/crmarsh/discord-rpc/build/276/artifacts).

On another note: May I recommend updating the issue title to something like "Crashing after handlers run with non-Unity C#"

**Comment by nathan130200** [comment]
So solution yet? I re created all code, and same crash when call RunCallbacks.........

**Comment by nathan130200** [comment]
Without any exception!

![2018-10-01_19-57-00](https://user-images.githubusercontent.com/14365254/46320346-3fcd3b80-c5b4-11e8-86a5-00730cb285d7.gif)

**Comment by msciotti** [comment]
I'm so sorry for the delay. At the moment, I'm really the sole maintainer of this repository. We've all been really focused on our [store](https://blog.discordapp.com/the-discord-store-beta-9a35596fdd4) launching soon. Not an excuse for neglecting this though.

I need to make some small sample apps and repro this. I believe you that you are having this issue. I just need a small enough code sample in my own hands to see what's up.

**Comment by Lachee** [comment]
Have you tried just setting up a timer instead of trying to create a new thread for the RunCallbacks? Just a random suggestion that might be worth a try.

**Comment by FayneAldan** [comment]
Hey, I already created a sample C# console app that doesn't use any threads or timers. It only uses a `while (true)` loop, which is all you really need for testing. I uploaded the code to a repo and uploaded an EXE file so you can quickly test it:
https://github.com/FayneAldan/RichPresenceTest/releases/tag/test1

**Comment by Lachee** [comment]
Yes, I have created a test project myself and have been able to reproduce the error. The main code for it can be found here https://gist.github.com/Lachee/04543c4149d3907c2d8a751e9dd3a878. Its literally just a form with a button which calls initialize and then starts either a form timer or a thread. Both produce the same results of the client exiting. 

If I put a MessageBox.Show in the ready event and use the form timer however, I get an exception instead of just closing. Unfortuantly the exception is not helpful at all, and is literally just `External exception occured`. 

This makes me believe that the native library is crashing for some reason, or the marshaling is going wrong and is just crashing C#. Maybe even heap corruption in C# itself? (but surely it would throw an actual exception for that?).

**Comment by FayneAldan** [comment]
Most likely the marshalling. If it was the native library, why would it only affect C#? But more importantly, why would it not affect Unity?

**Comment by Lachee** [comment]
Because unity is a magical bundle of joy which nobody can predict what its going to do.

**Comment by FayneAldan** [comment]
Here's an important note to make: I modified the wrapper to remove the user parameter from the ready handler. Doing so stopped the crashing but obviously removes access to info on the connected user. I don't have the resources to test the other handlers that provide a user, so I don't know if they would also crash.

**Comment by nathan130200** [comment]
@Lachee module crash is ntdll.dll:

```exception
Nome do aplicativo com falha: WarfaceRichPresence.exe, versão: 1.0.0.0, carimbo de data/hora: 0xf6bc5d2a
Nome do módulo com falha: ntdll.dll, versão: 10.0.17134.254, carimbo de data/hora: 0xa5a334d4
Código de exceção: 0xc0000374
Deslocamento da falha: 0x00000000000f4d3b
ID do processo com falha: 0x614
Hora de início do aplicativo com falha: 0x01d45a972e218006
Caminho do aplicativo com falha: C:\Users\Nathan Ferreira\Documents\Visual Studio 2017\Projects\WarfaceRichPresence\WarfaceRichPresence\bin\Debug\WarfaceRichPresence.exe
Caminho do módulo com falha: C:\Windows\SYSTEM32\ntdll.dll
ID do Relatório: 47bf08eb-7337-4d4d-9f65-142bfc915c15
```

**Comment by nathan130200** [comment]
Ok, i changed .exe and discord-rpc library do x86 now worked with thread.

**Comment by FayneAldan** [comment]
[I created a GUI for testing.](https://github.com/FayneAldan/RichPresenceTestGUI) To get it to run past initialization, you need to remove the parameters from `ReadyCallback` in `DiscordRpc.cs` (no other changes needed). After some testing, I have confirmed that receiving a RequestCallback also results in a crash.

**Comment by nathan130200** [comment]
I will test this, thanks for share this information.

**Comment by nathan130200** [comment]
My recommendations for the project are:

Move these methods to open connection with discord etc, for a class called DiscordRpc.

the Discord_Initialize method returns a pointer (which can be availed by the IntPtr programming languages in the case of C #) with the instance address of the DiscordRpc class

Regarding event handlers, from what I researched on the internet, you do not need to call events manually from the pro c ++ language, (calling Discord_RunCallbacks all the time), d

the Discord_Shutdown method requested the address of the previously opened instance in Discord_Initialize to be able to turn off rpc.

I've done an example of class sharing between C++ and C#:
https://github.com/nathan130200/CppTestClassPointer/

(Note i'm not C++ professional, i only know very basic but this code works.)

**Comment by nathan130200** [comment]
My recommendations for the project are:

Move these methods to open connection with discord etc, for a class called DiscordRpc.

the Discord_Initialize method returns a pointer (which can be availed by the IntPtr programming languages in the case of C #) with the instance address of the DiscordRpc class

Regarding event handlers, from what I researched on the internet, you do not need to call events manually from the pro c ++ language, (calling Discord_RunCallbacks all the time), d

the Discord_Shutdown method requested the address of the previously opened instance in Discord_Initialize to be able to turn off rpc.

I've done an example of class sharing between C++ and C#:
https://github.com/nathan130200/CppTestClassPointer/

(Note i'm not C++ professional, i only know very basic but this code works.)

**Comment by nathan130200** [comment]
@FayneAldan here i don't removed DiscordUser from ReadyCallback, i downloaded repository and make a clean build for library and now are working.

After build, cmake generated discord-rpc.dll in x86 arch, i set in C# WinForms to use x86 and now are working, without bluescreen and no crash, using thread (no Windows Forms Timer).

![image](https://user-images.githubusercontent.com/14365254/46416560-2afcbf00-c6fe-11e8-9049-ecd0531f257f.png)

https://github.com/nathan130200/WarfaceRichPresence

**Comment by FayneAldan** [comment]
Hey, why did you close? This isn't resolved yet. Removing the connectedUser parameter isn't a proper fix, especially since you still can't use Ask to Join with crashing.

**Comment by nathan130200** [comment]
I could not test on ask to join. But i wait a resolution.

**Comment by msciotti** [comment]
Removing the user struct from the two callbacks fixes the crash!?

...you're right, I bet this is the marshaling. We had a PR a while ago that did some custom marshaling for the C# wrapper because....something something Unity doesn't like UTF8 or something like that?

I'm surprised (ish) that it's causing crashes in "normal" C# stuff. But this does seem to be the heart of it.

**Comment by nathan130200** [comment]
@msciotti No, not fixed when removed two callbacks, i cloned repository and make a clean build and worked Discord_RunCallbacks inside a thread without crash.

**Comment by Lachee** [comment]
yes, C# has the concept of `unsafe` code, but obviously its not recommended. C# also has access to "managed" pointers which is what the wrapper found in the button clicker uses.

**Comment by nathan130200** [comment]
Also, can use Native bindings (like QtSharp) using CppSharp https://github.com/mono/CppSharp

**Comment by nathan130200** [comment]
No fix yet? 🤦‍♂️

**Comment by nathan130200** [comment]
Ok this library is dead.
