### ISSUE TITLE
[Request] Please provide pre-built DLLs

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#223]
Windows machines intended for Unity/C# require an extraordinary amount of time and [minimal documentation](https://github.com/discordapp/discord-rpc/issues/222) (with steps missing for Windows). Unity is super popular and a great deal of devs are using this -- and currently, the most suitable environment for Unity is Windows. 

Tons of "extras" and knowledge is needed just to build this for Windows with errors giving no direction without _Google-Fu'ing_ your way through. And the Windows 10's Ubuntu subsystem has no support for building these (it doesn't work). The DLLs are quite small and it'd help a great deal of indie devs get Discord working if we could just grab the DLLs out of the box.

Currently the only doc is:

```
Run python build.py unity in the root directory to build the correct library files and place them in their respective folders.
```

**Comment by dylanh724** [comment]
Oh! I also wanted to ask: Is there a separate area for Mac and Linux dlls, as well? These builds are still built on Windows with Unity. Sorry to bother!

**Comment by msciotti** [comment]
There are releases - pre built DLLs - for all 3 architectures in this repo under “releases” on the main page on the top banner...thing. Are those not what you’re looking for?

**Comment by msciotti** [comment]
You can find artifacts at the appveyor link that @Lachee posted, which I believe runs on every push to master.

You can find our releases at https://github.com/discordapp/discord-rpc/releases which are updated slightly less frequently; usually when major changes happen.
