### ISSUE TITLE
Seeking clarification: win64-dynamic ALSO works for 32-bit?

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#224]
Just clarifying:

win64-dynamic dll is for both 32-bit AND/OR 64-bit?

**Comment by msciotti** [comment]
No sir. Check out the releases at https://github.com/discordapp/discord-rpc/releases. If you download `discord-rpc-win.zip`, you'll see inside there are four folders:

![image](https://user-images.githubusercontent.com/4193854/44265275-c41d5800-a1da-11e8-8537-69a02b454203.png)

These folders are static and dynamic DLLs for both Win32 and Win64.
