### ISSUE TITLE
[Bug or User-Error?] Timecodes not properly updating?

### ISSUE THREAD

**Issue by xtilly5000** [discordapp/discord-rpc#226]
I have an entire system to determine what epoch second the game was created and the time span between the game start and the first second of 2015 but it isn't showing properly on discord. On discord the time elapsed is showing as 00:00 yet on the rich presence visualizer on the discord application hub shows it should be working properly and tracking how long the game was open. I'm on unity c#. I set it to 20 seconds per update, while documentation says the rate limit is 15 seconds per update. Its properly spitting out the correct time in the logs, but not in the discord app presence. Any thoughts?

**Comment by msciotti** [comment]
Mind posting the little code snippet for your UpdatePresence() call?

**Comment by Lachee** [comment]
The timestamps are Unix Epoch.
```csharp
		public static DateTime FromUnixTime(long unixTime)
		{
			var epoch = new DateTime(1970, 1, 1, 0, 0, 0, DateTimeKind.Utc);
			return epoch.AddMilliseconds(unixTime);
		}
```

**Comment by xtilly5000** [comment]
`        discordEpoch = DateTime.Parse("01/01/2015 00:00:00");
        currentTime = DateTime.Parse(DateTime.UtcNow.ToString("MM/dd/yyyy HH:mm:ss"));

        epochOffset = discordEpoch - currentTime;
        epochOffsetSeconds = (int)epochOffset.TotalSeconds;

        Debug.Log(epochOffsetSeconds * -1);`
Is called in the Start() method and retrieves discord epoch time. I read on discord documentation that discord epoch time is the number of seconds since the first of January 2015. When I plug in the number it logs into the discord application rich presence visualizer, it seems to be working perfectly fine.

`        presence.state = "Singleplayer";
        presence.details = "Playing with the wolves.";
        presence.largeImageKey = "hidden";
        presence.partyId = "hidden";
        presence.startTimestamp = (int)epochOffsetSeconds * -1;
        presence.partySize = 1;
        presence.partyMax = 1;
        presence.spectateSecret = "hidden";
        presence.joinSecret = "hidden";
`
This is called in the Update() method to update the presence values. I have a Co-routine called every 20 seconds to update the rich presence.

https://discordapp.com/developers/docs/reference
There is where I found how to calculate the correct time. It clearly states: "Milliseconds since Discord Epoch, the first second of 2015 or 1420070400000." On the rich presence visualizer it says that startTimestamp should be set to a number within discord epoch. The number you put in should be the number of seconds between the first of January 2015 and the current datetime.

I realized at this point that documentation might be wrong, or that I, myself may have gotten confused while searching. I will try your code and see if it works correctly. Thanks for all your help so far!

**Comment by xtilly5000** [comment]
Ah, I put in your code and it worked. I re-checked documentation and I realized my error. Simply misread the information that it gave me. Confirmed user error. Thank you guys for helping me solve this problem and taking time out of your day for me!
