### ISSUE TITLE
[Question] What happened to progress bars?

### ISSUE THREAD

**Issue by wr1ght** [discordapp/discord-rpc#227]
A while back you were able to see progress bars on Rich Presences with a `startTimestamp` and an `endTimestamp`

As seen here:
![image](https://user-images.githubusercontent.com/30602871/44557666-a76aae00-a70d-11e8-8ea9-f50c01d661f6.png)

Are there any plans on bringing this back, or adding a field such as `progress_bar: <Boolean>` which would enable/disable the bar?
I'm interested in using this in an application I'm working on.

**Comment by msciotti** [comment]
Right now, the progress bar is for the spotify integration only. We've never actually released it as a feature for Rich Presence; if that ever appeared, it was an unintended bug. There aren't any plans to add the bar at the moment, as it's fairly specific to music app integrations rather than game integrations.

**Comment by Lachee** [comment]
a more general progress bar outside of time would be cool for game integration however, you could show statistics about a game such as goals completed or level completion. It would be awesome if it could be at least considered as a extra feature. 

Maybe having 2 new fields, `progress_value : float` and `progress_max : float`, which will display the bar with the values like seen in the screenshot (but formatted in a more generic way like 2 decimal places??).

**Comment by K73SK** [comment]
I was literally just trying to figure out how to get the dang progress bar and have been ripping my hair out because all I get is this "Time left". Is this ever going to be a feature in the future? I'd also much rather see progress left by using a progress bar as opposed to "time left".

**Comment by Arimodu** [comment]
I was just googling for the same thing, wanted to use as a progress bar in a rythm game, oh well, what can I do.

**Comment by XORbit01** [comment]
It's 2024, have they added the progress bar?

**Comment by Dragon-Batch** [comment]
no :(
![image](https://github.com/user-attachments/assets/356d37fb-d0a7-4a54-ba6b-e28864e81707)

**Comment by clay-rip** [comment]
seems to work

<img width="310" height="135" alt="Image" src="https://github.com/user-attachments/assets/e5967f6c-1fa8-4433-b637-7528f8b80164" />

**Comment by Dragon-Batch** [comment]
this is a music app that has been integrated by discord themselves

**Comment by clay-rip** [comment]
no it isn't, this is a custom rpc

**Comment by EzyPzyAsh** [comment]
> no it isn't, this is a custom rpc

Can you link to it?

**Comment by Lachee** [comment]
> > no it isn't, this is a custom rpc
> 
> Can you link to it?

set the activity_type to `2` (for listening) and `timestamps.start` and `timestamps.end`. This will give you the desired result.
I've documented what the different activity types look like with different timestamps [here](https://lachee.github.io/discord-rpc-csharp/articles/features/timestamps.html) for my library.

Combine this with dynamic assets (using a url) to get album art like in [my example](https://lachee.github.io/discord-rpc-csharp/articles/features/assets.html#dynamic-assets)
