### ISSUE TITLE
DLL placement question in Unity

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#229]
Probably a newb question, but I don't work with DLLs very often in Unity:

Right now, I have the my dll's at `/Assets/Plugins/x86` and `/Assets/Plugins/x86_64` 

Can I place them at, say, 

/Assets/Plugins/**Discord**/x86 
and
/Assets/Plugins/**Discord**/x86_64

without issues? Do I need to do anything special, if so?

**Comment by Lachee** [comment]
I believe they have to be within the plugins folder. But what you can do is `/Assets/Discord/Plugins/x86` instead.

**Comment by dylanh724** [comment]
> I believe they have to be within the plugins folder. But what you can do is /Assets/Discord/Plugins/x86 instead.

Thanks

> This repository is not really the place to ask questions about unity.

Wasn't sure if it was specific to Unity -- The architecture is placed as if Discord is the only plugin we'll use in our project. It should really be reorganized to the above hierarchy in /Discord/Plugins/ (then I wouldn't have had to ask this question O_o)
