### ISSUE TITLE
Compile errors in VS 2017

### ISSUE THREAD

**Issue by weltkante** [discordapp/discord-rpc#23]
I've manually created a VS 2017 project (without cmake) to compile discord-rpc for statically linking with my game (I need specific compiler settings for static linking to work)

I'm getting a bunch of compile errors in discord_register_win.cpp because it includes psapi.h before windows.h - types like `BOOL`, `DWORD` and `WINAPI` aren't defined apparently - swapping the order to include windows.h first fixes the compile errors.

Did you chose this include order with a particular reason in mind or did I miss something while creating my project file? Or is this actually an oversight and discord currently does not compile in VS 2017 without this fix?

**Comment by YaLTeR** [comment]
I believe it is due to clang-format misconfiguration and has been fixed in https://github.com/discordapp/discord-rpc/commit/2f54e62c23939561c47a969ddaa68bca90fc064c.

It's possible to configure clang-format to always sort `windows.h` first, I'll try doing it later.

**Comment by crmarsh** [comment]
This is in the right order now.
