### ISSUE TITLE
handleJoinRequest never called?

### ISSUE THREAD

**Issue by fr500** [discordapp/discord-rpc#233]
Hi

I'm trying to hookup the ask to join functionality into RetroArch.
I followed your send_presence demo closely, the code is pretty much identical except for the game runloop of course

https://github.com/fr500/RetroArch/blob/master/discord/discord.c#L78

So here is my call to handle_join_request.

The handlers are set here:
https://github.com/fr500/RetroArch/blob/master/discord/discord.c#L182

And the callbacks are being fired, I'm logging the ready callback for instance and I have zero issues with that one:

https://github.com/fr500/RetroArch/blob/master/discord/discord.c#L49

```
[INFO] Loading history file: [userdata\playlists\windows\x64\history\content_video_history.lpl].
[INFO] Loading history file: [userdata\playlists\windows\x64\history\content_image_history.lpl].
[INFO] [GL]: VSync => on
[INFO] [WGL]: wglSwapInterval(1)
[WARN] [WGL]: wglSwapInterval() failed.
[INFO] [Discord] connected to user: radius#5870 - avatar id: 155390707853557760
[INFO] [Discord] updating (2)
```

As you can see it's firing, so on another client I hit the Ask to Join button (I have a whitelisted alt account) but nothing happens

![image](https://user-images.githubusercontent.com/1721040/45269741-84076900-b458-11e8-995a-fa78d308006b.png)

I added exit(1) to make it close if the handler is called for testing... but nothing.
Any ideas on what I might be doing wrong?

**Comment by fr500** [comment]
I made sure update_callbacks is being fired every frame btw so that is not the issue either.

**Comment by Lachee** [comment]
Have you subscribed to the events? What are you receiving in the discord console? And is your second account whitelisted on your application rp page

**Comment by fr500** [comment]
![image](https://user-images.githubusercontent.com/1721040/45269850-7eab1e00-b45a-11e8-885b-0b1f2a37b908.png)

I get this in the console of the discord user asking to join


Hmmm, how do I subscribe to the events, is that on the documentation?

**Comment by MinnDevelopment** [comment]
@fr500 could you look at the network tab and see what the response is for that request?

**Comment by fr500** [comment]
I get 5, Invalid Activity Action

**Comment by fr500** [comment]
Hmmm I'm not setting a partyId maybe that's the reason, let me try that

**Comment by Lachee** [comment]
Oh yeah, totally forgot and probably should be documented. You cannot join without a party ID and join secret. You cannot spectate without a spectate secret and party ID too

**Comment by msciotti** [comment]
When in doubt, check the handy table! 

https://discordapp.com/developers/docs/rich-presence/how-to#rich-presence-field-requirements

**Comment by MinnDevelopment** [comment]
The client shouldn't show an ask to join button if it doesn't actually work, though.
