### ISSUE TITLE
Whitelist not working?

### ISSUE THREAD

**Issue by fr500** [discordapp/discord-rpc#239]
Hi,
I developed the ask to join implementation for RetroArch here.
https://github.com/libretro/RetroArch/pull/7210
It was working fine, we were testing it with a whitelist and everything was going well till last week, but now we can't click the ask-to-join button even if whitelisted.

It shows and everything but it just won't let the other whiltelisted user click.

Anything going on?
No changes on our end.

**Comment by night** [comment]
What client are you using, Stable or Canary (and on what operating system)? Do you know the date/time when it broke? Is there a photo/video of the behavior being exhibited?

**Comment by Lachee** [comment]
possible duplication of issue #238 ?

**Comment by fr500** [comment]
Sadly, no idea on the date
My windows client is stable, build 26016
My linux client is stable, build 26016

The users are properly whitelisted.

![image](https://user-images.githubusercontent.com/1721040/46911962-6b92de80-cf2f-11e8-8241-26567a6ebd44.png)

**Comment by msciotti** [comment]
Not a duplicate of #238, but I think related. @paulshen since we changed this stuff to look at Dispatch as well, looks like we caught a snag across the board.

**Comment by msciotti** [comment]
@fr500 can you try this again now? I believe the fix was deployed.

**Comment by fr500** [comment]
Sure, do I need to update the client?
Because it's not showing updates for me

**Comment by fr500** [comment]
Seems to work in canary

**Comment by fr500** [comment]
Ok some more info, ask to join (canary to canary) seems to work in a windows host and linux asks to join scenario.

The other way around (linux hosts, windows asks to join) now gets this:
![image](https://user-images.githubusercontent.com/1721040/46992501-fca0bb80-d0cf-11e8-97d7-addfa3dffd9b.png)

This is seen on the joiner console

**Comment by msciotti** [comment]
If you expand that error, what's it say in the body?

**Comment by fr500** [comment]
![image](https://user-images.githubusercontent.com/1721040/47051779-4e4a5400-d16b-11e8-9fc6-fd8f5f9f26e6.png)

The other way around is working 100% in canary tho

**Comment by fr500** [comment]
join from linux, windows host (works):

![image](https://user-images.githubusercontent.com/1721040/47053711-d5032f00-d173-11e8-8337-88d240e60f3c.png)

join from windows, linux host (doesn't):

![image](https://user-images.githubusercontent.com/1721040/47053724-e64c3b80-d173-11e8-97e8-fb438a6f0428.png)

**Comment by fr500** [comment]
Yes, for some reason had to dup the partyId string on linux
🤷‍♂️ 

https://github.com/fr500/RetroArch/commit/17384f719f06f40e5ad1c9d009e72cf9e08c3813 
Other than that, it's working
