### ISSUE TITLE
Crash during shutdown (documentation bug)

### ISSUE THREAD

**Issue by weltkante** [discordapp/discord-rpc#24]
The documentation over at [discord](https://discordapp.com/developers/docs/rich-presence/how-to) does not mention that you have to call `Discord_Shutdown` even though it is vital for a clean shutdown.

If you don't call `Discord_Shutdown` then the application does not shut down properly. You have a static variable of type std::thread which will run its destructor during termination of the application. Running a destructor on a running thread is not allowed and will crash the program (calls std::terminate)

**This prevents a clean exit because other destructors and onexit handlers are not executed.**

You apparently have `Discord_Shutdown` which properly terminates the thread, allowing clean shutdown of the game, but you haven't mentioned this anywhere in your documentation.

**Comment by msciotti** [comment]
Will get it added—thank you very much!

**Comment by msciotti** [comment]
This has been added here: https://github.com/discordapp/discord-api-docs/commit/5be941b5230524e0db6b49e26af6357d514303ec

Thank you very much for this important info.
