### ISSUE TITLE
Game not launching from Rich Presence invite

### ISSUE THREAD

**Issue by samuelmaddock** [discordapp/discord-rpc#240]
**Platforms:** Windows 10 64-bit, macOS 10.13.5
**App Builds:**
`Release Channel: stable, Build Number: 26016, Version Hash: 50458c1749127936028ccfb9909bd63545c83948`
`Release Channel: canary, Build Number: 26239, Version Hash: d30e3b1f8a04c02522d0589e29c39ade6321f45e`

Accepting Rich Presence invites via chat or the top-bar "Launch game and join" do not launch the game. My game is non-verified and I've tested using two whitelisted accounts.

On startup, the game calls `Discord_Register()` with the `autoRegister` parameter set to `1`. Here's what the Windows registry looks like:

### HKEY_CURRENT_USER\Software\Classes\discord-`appid`

| Name | Type | Data |
| --- | --- | --- |
| (Default) | REG_SZ | URL:Run game `appid` protocol |
| URL Protocol | REG_SZ | _Empty_ |

### HKEY_CURRENT_USER\Software\Classes\discord-`appid`\DefaultIcon

| Name | Type | Data |
| --- | --- | --- |
| (Default) | REG_SZ | C:\Users\Sam\AppData\Local\Programs\metastream\Metastream.exe |

### HKEY_CURRENT_USER\Software\Classes\discord-`appid`\shell\open\command

| Name | Type | Data |
| --- | --- | --- |
| (Default) | REG_SZ | C:\Users\Sam\AppData\Local\Programs\metastream\Metastream.exe |

**Comment by StrikerMan780** [comment]
This issue happens on linux too: https://github.com/discordapp/discord-rpc/issues/163

**Comment by msciotti** [comment]
Seems to be a bug, will investigate.

**Comment by RagingNoob** [comment]
Still not working for me. ask to join is blocked.

**Comment by fr500** [comment]
@RagingNoob game launch is a separate bug

I fixed the RA bug (there was a bug on discord, and then a bug on RA)
https://github.com/discordapp/discord-rpc/issues/239

You can try it by building my fork.

**Comment by fr500** [comment]
Yeah seems completely discord side, there isn't any activity in the inspector when this is attempted

**Comment by fr500** [comment]
Ugh didn't expect my constant rebasing to produce so much noise sorry about it!

**Comment by msciotti** [comment]
OK—bug has been found and a fix is being worked on!

**Comment by fr500** [comment]
awesome!

**Comment by msciotti** [comment]
Fix should be out to Canary, PTB, and Stable. Please let me know if it works!

**Comment by fr500** [comment]
It worked on windows.
On linux clients it did nothing for me at least.

**Comment by samuelmaddock** [comment]
@msciotti Confirmed that it's working on the platforms listed in the original post. Thanks!

**Comment by msciotti** [comment]
@fr500 are you seeing any console errors or anything like that when you click play? Or just nothing?

**Comment by fr500** [comment]
There is activity:

![image](https://user-images.githubusercontent.com/1721040/47546268-10a9a180-d8b6-11e8-81b7-b4dab2ec6930.png)

**Comment by msciotti** [comment]
@fr500 I think I have an ubuntu vm on my machine. Let me see if I can repro.

**Comment by fr500** [comment]
Let me know if I can help in any way.

**Comment by msciotti** [comment]
@fr500 I cannot repro on Linux, it worked OK for me on Ubuntu. That launch target is accurate and what mine shows as well. You may want to check what that is registered to.

It works for me on all platforms, so I'm going to mark this issue as closed. If others continue to see this issue, please feel free to re-open here or open a new issue. Thank you all for your help!

**Comment by fr500** [comment]
@msciotti hmmm something weird is going on, when I launch from the shell
ie: retroarch

it works
when I launch from discord it's as if some arguments are passed (I worked around the %u argument that is appended adding a ; after retroarch)

I got it to work by making the launch command `sh -c retroarch` but I dunno why is that this is required.
