### ISSUE TITLE
[$50 Bounty] RP completely broken with il2cpp (Unity 2018.2 Stable): Needs dll marshaling

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#243]
## Reviving this issue:
https://github.com/discordapp/discord-rpc/issues/186

## Background
Unity 2018.2 now **only** builds **il2cpp** for Windows UWP and now also gives the option for il2cpp builds for Windows & Mac standalone (which is definitely the future for security+performance) -- this version is not a beta. Very soon, you'll see tons of people raising this issue: a permanent fix in a newer version with cross-compatibility would be ideal~

## The Issue
The answer within the https://github.com/discordapp/discord-rpc/issues/186 was not explained in detail for those not too familiar with DLL madness (very little interaction with DLL's from Unity users).

I found where to put this attribute, but don't know what to do with the errors that follow.

@mdsitton was the original person that answered https://github.com/discordapp/discord-rpc/issues/186 and @franckmolto seemed to resolve it from that answer: Any of you guys up to sharing your result?

## Bugs reported from logs
```csharp
[Discord] init @ OnEnable
UnityEngine.DebugLogHandler:LogFormat(LogType, Object, String, Object[])
UnityEngine.Logger:Log(LogType, Object)
UnityEngine.Debug:Log(Object)
DiscordController:OnEnable()

(Filename: C:\buildslave\unity\build\Runtime/Export/Debug.bindings.h Line: 43)

NotSupportedException: IL2CPP does not support marshaling delegates that point to instance methods to native code.
  at DiscordController.OnEnable () [0x00000] in <00000000000000000000000000000000>:0 
```

## Original Code
```csharp
[MonoPInvokeCallback(typeof(DiscordRpc.ErrorCallback))]
```
**So you have this @ DiscordRpc:**
```csharp
[UnmanagedFunctionPointer(CallingConvention.Cdecl)]
public delegate void ErrorCallback(int errorCode, string message);

public struct EventHandlers
{
    public ErrorCallback errorCallback;
    [...]
}
```
## Suggested Change from https://github.com/discordapp/discord-rpc/issues/186
If you change it to this:
```csharp
using AOT; // Parent of MonoPInvokeCallback

[MonoPInvokeCallback(typeof(DiscordRpc.ErrorCallback))]
```
**So you have this @ DiscordRpc:**
```csharp
[MonoPInvokeCallback(typeof(DiscordRpc.ErrorCallback))] // 
public static void ErrorCallback(int errorCode, string message);

public struct EventHandlers
{
    public ErrorCallback errorCallback;
    [...]
}
```
![image](https://user-images.githubusercontent.com/8840024/47232298-e3ff1100-d401-11e8-8bb3-42c723305664.png)
![image](https://user-images.githubusercontent.com/8840024/47232308-ea8d8880-d401-11e8-8796-dc0037d42b27.png)

It starts getting confusing, starting with ErrorCallback not being a type

## Cross-Compatibility
From my research (someone else can confirm), converting to dll marshaling using the `[MonoPInvokeCallback]` attribute and static callbacks has claims of cross-compatibility, exampled at steamworks.net and facepunch.steamworks repo's (or a quick Google search).

**Comment by dylanh724** [comment]
The keyword is `AOT` (Ahead of Time) - we need AOT-friendly delivery of the dll reads.

**Comment by dylanh724** [comment]
> Responded to the closed issue without seeing this open first

To consolidate:

> I'm perfectly happy accepting a PR for the static class member changes if it won't break existing implementations (and it shouldn't?).

Unless you have suggestions for a more "real" solution. As mentioned above, neither myself nor snowyote are well-versed in this il2cpp stuff, so we're going a bit on community knowledge here.

Alas, I'm not good, either. I tried a few things, but failed. Something to do with turning the callbacks into static callbacks tagged with (for ErrorCallback's example) `[MonoPInvokeCallback(typeof(DiscordRpc.ErrorCallback))]`

Then the importdll[] tags probably have to be changed to something similar, too. Maybe? I tried researching, but I wasn't even familiar with dll madness to begin with :P I mostly use native C# libraries, personally**. Anyone able to come to the rescue?**

**Comment by dylanh724** [comment]
## Bounty!
**$50 PayPal** to whoever gets this working.

**Comment by pipliz** [comment]
I'd like to point out that IL2CPP is the new standard for UWP builds only - "standalone" windows builds using mono/.net are not being deprecated.

See the section about it at https://blogs.unity3d.com/2018/07/10/2018-2-is-now-available/

**Comment by msciotti** [comment]
@pipliz thank you for that documentation. That's mainly what I'm referring to. Unity deprecating .NET altogether seemed a bit fishy to me :p I think we can definitely come up with a solve for folks who want to make the switch, and just ensure it doesn't break other stuff.

**Comment by dylanh724** [comment]
Ah, my bad -- I updated OP

**Comment by msciotti** [comment]
Based on the solution offered in #186, this seems like something that is handled more in the use of the methods, rather than the underlying source code. That is to say, handled in `DiscordController.cs` which is an example, rather than `DiscordRpc.cs` which is the "header" file.

Perhaps @mdsitton would be able to share with us a bit more of his code, but in the meantime, I am trying to finagle the example to get it working.

**Comment by dylanh724** [comment]
Porting a recent comment over from https://github.com/discordapp/discord-rpc/issues/186

> Hey, I'm a dev at Unity working on IL2CPP, so I thought I might help here.
> 
> The use of the `MonoPInvokeCallback` attribute for cases where a managed delegate is marshaled to native code is required for both IL2CPP and Mono AOT. As it turns out, Unity won't be supporting Mono AOT on many platforms soon (and currently we don't support too many), but this is a more general AOT issue.
> 
> The AOT code generator needs to know which managed methods could be called from native code, as it needs to generate marshaling wrappers. Doing this for all managed methods is not feasible, so the `MonoPInvokeCallback` attribute guides the AOT code generator.
> 
> While IL2CPP is now an option for desktop standalone player builds in Unity 2018.2 and later, we plan to continue to support Mono JIT for those platforms. We don't plan to _require_ IL2CPP as is the case on iOS, for example.
> 
> Still, using `MonoPInvokeCallback` is the correct solution here, and should have no impact for other cases. The chances of it breaking something else are pretty low (or zero).

**Comment by joshpeterson** [comment]
I think this is on the right track.

> When you import a DLL, the callback must be static (original ReadyCallback was not static)

> The callback must have the attribute [MonoPInvokeCallback] (via using AOT;), recommended to include the typeof (ReadyCallback used [UnmanagedFunctionPointer])

This is correct. This code is trying to get a function pointer to the managed method `ReadyCallback`, and give it is native code via the `Initialize` method, so the native code can call back into the managed code at some point later.

These two requirements are correct. The method which will be called back from native code needs to be a static method and it needs to have the `MonoPInvokeCallback` attribute.

> The initial callback must not be a delegate and must end with (), not ; (ReadyCallback was a delegate)

I'm not entirely sure what this requirement means.

Based on the code above though, I think you need one modification:

``` csharp
// DiscordRpc.cs
using AOT;

public delegate void OnReadyInfo(ref DiscordUser connectedUser);

[MonoPInvokeCallback(typeof(OnReadyInfo))]
public static void ReadyCallback(ref DiscordUser connectedUser)
{
      UnityEngine.Debug.Log("[DiscordRpc] @ ReadyCallback");
}

public struct EventHandlers
{
        // I think this is the change we need.
	// public ReadyCallback readyCallback; // Unchanged?
        public OnReadyInfo readyCallback; // The type of this field should be OnReadyInfo
}

// From the examples I've seen, I don't think this line is the issue -- but the callback, rather.
[DllImport("discord-rpc", EntryPoint = "Discord_Initialize", CallingConvention = CallingConvention.Cdecl)]
public static extern void Initialize(string applicationId, ref EventHandlers handlers, bool autoRegister, string optionalSteamId);
```

If this does not fix the issue, can you provide more details about what the error is? Thanks!

**Comment by msciotti** [comment]
Hi josh! Thanks a ton for this helpful info and for chiming in. Based on your and Dylan's notes this definitely seems like a change we need to make. No problem at all there.

The second piece will be updating the example code in `DiscordController.cs` to work with the new "header" file. As we swap these callbacks to statics, the code example throws a number of errors about requiring object references when `Invoke()`ing the `UnityEvent`s. I've refactored them into a singleton GameManager:

```cs
public class GameManager {
  private static GameManager instance = null;
  public static GameManager Instance {
    get
    {
      if (instance == null)
      {
        instance = new GameManager();
      }
      return instance;
    }
  }
  public UnityEngine.Events.UnityEvent onConnect;
  public UnityEngine.Events.UnityEvent onDisconnect;
  public UnityEngine.Events.UnityEvent hasResponded;
}
```

And changing the invokes to:

```cs
public static void ReadyCallback(ref DiscordRpc.DiscordUser connectedUser)
  {
    Debug.Log(string.Format("Discord: connected to {0}#{1}: {2}", connectedUser.username, connectedUser.discriminator, connectedUser.userId));
    GameManager.Instance.onConnect.Invoke();
  }
```

This makes the compiler happy, but seems to cause some runtime crashes in the player. Starting the player will result in a freeze after `Discord: init` without any errors thrown. So, that's where I am at as of this morning 😄

**Comment by msciotti** [comment]
Can confirm that `UnityEvent.Invoke()` seems to be the culprit. This freezes the player:

```cs
public static void ReadyCallback(ref DiscordRpc.DiscordUser connectedUser)
  {
    Debug.Log(string.Format("Discord: connected to {0}#{1}: {2}", connectedUser.username, connectedUser.discriminator, connectedUser.userId));
    GameManager.Instance.onConnect.Invoke();
  }
```

This works successfully and the Debug Log is printed:

```cs
public static void ReadyCallback(ref DiscordRpc.DiscordUser connectedUser)
  {
    Debug.Log(string.Format("Discord: connected to {0}#{1}: {2}", connectedUser.username, connectedUser.discriminator, connectedUser.userId));
    // GameManager.Instance.onConnect.Invoke();
  }
```

**Comment by joshpeterson** [comment]
I'm curious about the specific errors you get when calling `Invoke` here. Can you provide more details?

**Comment by joshpeterson** [comment]
Is there any information in the Unity player log?

**Comment by msciotti** [comment]
Not much from what I've seen, but here's a couple videos.

Not working when invoking events: https://gfycat.com/ShrillDigitalAnglerfish
Working when removing the `Invoke()`: https://gfycat.com/QuickDearDogwoodtwigborer

Sorry for the gfycat links; github doesn't like mp4 embeds apparently!

If there's some logging I can attach that I might be missing, would love to know. I'm a Unity newbie for the most part. My changes are also reflected in #249 if anyone would like to pull it down themself.

**Comment by msciotti** [comment]
Think I found my own issue. The callbacks in `DiscordController.cs` did _not_ need to be static; that was my misunderstanding. So there's no need for a singleton and the "normal" code works just fine. Updating PR.

**Comment by msciotti** [comment]
@dylanh724 could you pull down my PR and see if it fixes the issue for you? It works on my machine for il2cpp and Mono, but would love a second confirmation before merging.

**Comment by dylanh724** [comment]
I had sort of a custom implementation for the DiscordMgr, I'm going to cherry pick the changes and get back to you shortly 😅 I'll be able to start really soon (today).

**Comment by dylanh724** [comment]
@msciotti I copy+pasted your `DiscordRpc` changes without changing it. I then moved my custom logic into its own file (DiscordMgr), leaving `DiscordController` a copy+paste of your version.

I was unable to get this working, getting the same error:

![image](https://user-images.githubusercontent.com/8840024/47963366-45f88100-e066-11e8-9f01-a7652d9413ee.png)

What's your build info? Mine is:

* Unity 2018.2.12f1
* il2cpp (not Mono)
* .NET 4.5
* Windows Standalone x64 build

**Comment by msciotti** [comment]
We can continue tracking this over in the PR. But my settings are as follows:

![image](https://user-images.githubusercontent.com/4193854/48018446-b85c7600-e0e5-11e8-8ca6-5560b7613bfd.png)

![image](https://user-images.githubusercontent.com/4193854/48018451-bbeffd00-e0e5-11e8-941c-e9fe6fa463af.png)

I'm testing over on macOS. Unity build 2018.3.0b8

**Comment by msciotti** [comment]
This didn't get auto-closed with the PR, so closing.

**Comment by mdsitton** [comment]
I'm a little late to the party, but glad this issue was figured out eventually 👍

**Comment by derwodaso** [comment]
Is there an official solution here now? I am still getting the `IL2CPP does not support marshaling delegates that point to instance methods to native code.` error in the build when compiling the button-clicker example with IL2CPP:


My solution after trying around a bit was the following (not sure if that all makes sense but it seems to work):

In DiscordRpc.cs:
```C#
// public EventHandlers are set from the DiscordController.cs in stead of passing in the handlers when initializing:
public static EventHandlers Callbacks;

[MonoPInvokeCallback(typeof(OnReadyInfo))]
public static void ReadyCallback(ref DiscordUser connectedUser) { Callbacks.readyCallback(ref connectedUser); }
public delegate void OnReadyInfo(ref DiscordUser connectedUser);

[ ... ]

public static void Initialize(string applicationId, bool autoRegister, string optionalSteamId)
{
	EventHandlers eventHandlers = new EventHandlers();
	// asign the static methods above, which invoke the Callbacks
	eventHandlers.readyCallback += DiscordRpc.ReadyCallback;
	eventHandlers.disconnectedCallback += DiscordRpc.DisconnectedCallback;
	eventHandlers.errorCallback += DiscordRpc.ErrorCallback;
	eventHandlers.joinCallback += DiscordRpc.JoinCallback;
	eventHandlers.spectateCallback += DiscordRpc.SpectateCallback;
	eventHandlers.requestCallback += DiscordRpc.RequestCallback;
	InitializeInternal(applicationId, ref eventHandlers, autoRegister, optionalSteamId);
}

[ ... ]
```

In DiscordController.cs I replaced the OnEnable() with this:
```
void OnEnable()
{
	Debug.Log("Discord: init");
	DiscordRpc.Callbacks.readyCallback = ReadyCallback;
	DiscordRpc.Callbacks.disconnectedCallback = DisconnectedCallback;
	DiscordRpc.Callbacks.errorCallback = ErrorCallback;
	DiscordRpc.Callbacks.joinCallback = JoinCallback;
	DiscordRpc.Callbacks.spectateCallback = SpectateCallback;
	DiscordRpc.Callbacks.requestCallback = RequestCallback;
        DiscordRpc.Initialize(applicationId, true, optionalSteamId);
    }
```

**Comment by msciotti** [comment]
@derwodaso Hm, the example as-is in the repo works fine for me? Here are my steps:

1. Get the repo fresh (git reset --hard HEAD && git pull && git clean -xdf)
2. `python build.py`
3. Open unity -> button-clicker
4. Swap to il2cpp compiler -> restart
5. Press play

I get my ready callback with my userid in it:

![image](https://user-images.githubusercontent.com/4193854/49666633-8eacac80-fa0d-11e8-8291-d2fd52d399c2.png)

This does not work for you?

**Comment by franckmolto** [comment]
You must make a build with il2cpp.

It stays c# in the editor

Provenance : Courrier pour Windows 10

De : Mason Sciotti
Envoyé le :vendredi 7 décembre 2018 19:48
À : discordapp/discord-rpc
Cc : franckmolto; Mention
Objet :Re: [discordapp/discord-rpc] [$50 Bounty] RP completely broken withil2cpp (Unity 2018.2 Stable): Needs dll marshaling (#243)

@derwodaso Hm, the example as-is in the repo works fine for me? Here are my steps:
1. Get the repo fresh (git reset --hard HEAD && git pull && git clean -xdf)
2. python build.py
3. Open unity -> button-clicker
4. Swap to il2cpp compiler -> restart
5. Press play
I get my ready callback with my userid in it:

This does not work for you?
—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


Garanti sans virus. www.avg.com

**Comment by derwodaso** [comment]
franckmolto is correct, the problem only occurs in the build. The editor worked right away.

**Comment by msciotti** [comment]
Hm, OK can confirm, I didn't realize it was failing on a built app. @derwodaso if your changes work and you'd like to PR them, I'm happy to review and test and merge.

**Comment by derwodaso** [comment]
@msciotti done! Did some minor changes to my previous version to keep the signature of the Initialize method the same. So no changes are required in _DiscordController.cs_.
