### ISSUE TITLE
UE4 discord plugin crashes after closing Play In Editor and making one action in the editor

### ISSUE THREAD

**Issue by SyedAman** [discordapp/discord-rpc#244]
I'm using UE4 4.20.3. I haven't made any changes to the plugin. I've only used the exposed blueprints in my Game Instance.

Steps to reproduce:

1. Do something similar to the UE4 Example where you initialize connection. I did it in an Actor which I construct from the Game Instance.
2. Open PIE
3. Close PIE
4. Engine should crash soon

Engine stopped crashing once I stopped executing "Check for all Callbacks" in event tick of the Actor which I have my Discord logic in.

![2018-10-21 17_59_23-krieg debuggame - unreal editor](https://user-images.githubusercontent.com/11065634/47272970-1708e800-d55b-11e8-8efa-f0116b5f5d38.jpg)

![image](https://user-images.githubusercontent.com/11065634/47272980-3a339780-d55b-11e8-9954-9485096b6914.png)

Fixed once I stopped checking for callbacks:

![image](https://user-images.githubusercontent.com/11065634/47272982-3f90e200-d55b-11e8-81c1-8e4952eda5d9.png)

![image](https://user-images.githubusercontent.com/11065634/47272998-60593780-d55b-11e8-83db-5b822be956be.png)

I've been able to replicate this using PIE while developing. I haven't been able to replicate on a shipping build of my game.

**Comment by infinitegachi** [comment]
What are these pictures for ants

**Comment by msciotti** [comment]
This is a very late reply, but I think if you're still seeing issues and want to integrate, you'd be best to move to our GameSDK, which should be perfectly compatible with newer Unreal versions.

https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide

If you need help, come join us in the Discord at https://discord.gg/discord-gamesdk !
