### ISSUE TITLE
[Feature Request] Add Java support

### ISSUE THREAD

**Issue by TomAvecLeVdsl** [discordapp/discord-rpc#246]
All in the title :)

**Comment by xaanit** [comment]
https://github.com/Vatuu/discord-rpc
https://github.com/MinnDevelopment/java-discord-rpc
https://github.com/jagrosh/DiscordIPC

Plenty of java libraries, it's definitely possible to use Java with this.

**Comment by TomAvecLeVdsl** [comment]
Thanks you
