### ISSUE TITLE
Problem with "startTimestamp"

### ISSUE THREAD

**Issue by Issvn** [discordapp/discord-rpc#248]
Hi ! 
I actually have some troubles with the startTimestamp functions in discord RPC
All I wanna know is how to make the timestamp start from 0 and go up to 1, 2, 3,  .... 
Thank you in advance 
Issun
![image](https://user-images.githubusercontent.com/29113989/47727051-042d9c00-dc5c-11e8-8650-7af91b43a85f.png)

**Comment by msciotti** [comment]
Hi Issun. To do so, you should grab the current unix timestamp in whatever the easiest way in your code is, and put it in the `startTimestamp` field. Note that if you send an `endTimestamp` as well, it will turn into a timer counting _down_, so don't do that.

The payload should support both seconds and milliseconds. If you see it starting at a larger number than 0, make sure the timestamp you're sending matches the current unix timestamp. I usually use https://www.unixtimestamp.com/ or https://www.epochconverter.com/ as a sanity check.
