### ISSUE TITLE
Game doesn't register on initialize or Discord_Register anymore.

### ISSUE THREAD

**Issue by StrikerMan780** [discordapp/discord-rpc#251]
On Windows, applications using Discord RPC don't register anymore on Discord_Initialize or Discord_Register. Rich presence itself will work, but the game will not show up on the games list, nor will you be able to click join invites (Discord will error out and say "Game executable not found".

**Comment by Pepper551** [comment]
I'm glad I came across this, been having an issue all day with "Failed to launch game. Game executable was not found" which I'm guessing is the exact same issue.

**Comment by Bluexin** [comment]
You may be able to get more info on the issue by opening the console in Discord (`ctrl+shift+i`) which might be logging something when you try to register (ie some message telling you why it failed to register)

**Comment by msciotti** [comment]
It's late now, but I can look into this again tomorrow. We haven't shipped anything touching this code recently, so I'm not sure why behavior would have changed, but as we all realize, this is flaky sometimes.

**Comment by Pepper551** [comment]
Just double checked on the console, when I click on Spectate etc, we get the following in the console

launchTarget: discord-512026136507xxxxxxx://
useLauncher: false

We get the red bar at the top saying "Executable not found", what is weird though is if I then copy the launch target and run it via the run prompt on windows, the application launches first time.

So not sure if mine is related somehow to this issue or mine actually might be something completely different

**Comment by msciotti** [comment]
That is helpful, thank you Pepper. So that means registration should be working properly, which is good. But our attempt to call it is breaking. Are you guys using Discord canary, or stable? Or PTB?

**Comment by Pepper551** [comment]
I mainly use stable but I've also tried using canary to the same result.

**Comment by StrikerMan780** [comment]
Stable.

**Comment by msciotti** [comment]
Fix is out on canary and should be rolling to the rest of clients today. Thanks all!

**Comment by Pepper551** [comment]
@msciotti I can confirm this worked on Canary, and just had the update on Stable, all working perfectly. Thanks for the swift fix.

**Comment by msciotti** [comment]
Can also confirm it seems to be working again. Sorry about that and thanks guys!
