### ISSUE TITLE
[JavaScript] Invalid Origin

### ISSUE THREAD

**Issue by CreatorVilius** [discordapp/discord-rpc#252]
I am having Close Event, and it's reason is `Invalid Origin`. I don't really know what's wrong.

**Comment by msciotti** [comment]
Hey Creator! How are you trying to connect to the local Discord client? Sounds like WebSocket; are you doing it from a browser? A locally installed app?

**Comment by CreatorVilius** [comment]
I am not connecting through local Discord client, I am doing it through Node JS.

**Comment by msciotti** [comment]
If you are looking to connect via a WebSocket, that will not work. If you want to build a NodeJS app that works with Rich Presence, I recommend using this existing wrapper: https://www.npmjs.com/package/discord-rich-presence.

**Comment by CreatorVilius** [comment]
I am already using that Package.

**Comment by msciotti** [comment]
Hm, that package has worked for me in the past. Would you be able to share the code here?
