### ISSUE TITLE
[OSX][Unity] DllNotFoundException: discord-rpc

### ISSUE THREAD

**Issue by Skeledurr** [discordapp/discord-rpc#253]
Hey!

I followed the Unity setup guide in the read me and could never get the library to work on mac. I checked other forks and I can't seem to find anyone else that has it working on OSX either.

Should I give up on this for now? Or am I doing some wrong?

**Comment by msciotti** [comment]
Hey @Skeledurr, I think I may have made a mistake in that Readme. By chance, is your dll file named `libdiscord-rpc.bundle`? It should just be `discord-rpc.bundle`. I'll change the readme right now to reflect that; I apologize for the confusion if that's the case.

If that's not the issue, could you take a screenshot of what your folder structure looks like for the Unity project? Where you've put the DLLs, their names, etc.

**Comment by Skeledurr** [comment]
That was it!
Should I do the same for the linux .so?

**Comment by msciotti** [comment]
I _think_ the linux .so actually looks for `libdiscord-rpc`, because consistency 😆 If it's not working as that, then yeah drop the `lib`.

**Comment by msciotti** [comment]
Gonna close this as the solve was found. Please re-open if it's not working!
