### ISSUE TITLE
[ANNOUNCEMENT] Ask to Join no longer requires whitelisting

### ISSUE THREAD

**Issue by msciotti** [discordapp/discord-rpc#255]
Hi everyone!

Wanted to make an exciting announcement. As of a little while ago, the Ask to Join feature of Rich Presence no longer requires whitelisted approval by Discord.

As a bit of background: we originally required whitelisting for Ask to Join because we relied on developers to create in-game UI to handle the requests. Without in-game prompts, a user with a pending request could only see it as a banner in the Discord app itself. When you're in the middle of playing a game, you may not be looking at Discord, or you may only have one monitor and not even have it up.

We have recently added support for Ask to Join requests in the Discord Overlay. They're pretty darn snazzy, too! Now that we have first-party support for requests, we are no longer reliant on developers creating in-game UI. Therefore, we have removed the whitelist restriction.

This also means that you as a developer do not necessarily need to handle the Ask to Join callback flow in your game. If you would like to build custom in-game UI to do so, be our guest! Or, feel free to rely entirely on our overlay.

We are also looking into removing the whitelisting requirement for Spectating. The original thought around Spectating was that we didn't want developers using Spectate as an "Auto-Join", a.k.a. Ask to Join but circumventing the need of the person playing to say Yes or No. We've not fully decided on this yet, but we're learning towards lifting the restriction.

I'll update documentation accordingly, and more info will come if there's more to say!

**Comment by aaronfranke** [comment]
So, when will the overlay be available on Mac and Linux?

**Comment by aaronfranke** [comment]
The point of my above comment is that "Or, feel free to rely entirely on our overlay" isn't a relevant approach for any game that runs on more than just Windows.

**Comment by msciotti** [comment]
No it isn't, but I think we all understand that the vast majority of gaming is done on Windows machines by your average user. If you are developing with cross-platform in mind, you're already cognizant of differences between operating systems, and if you're going so far as to integrate this deeply with Discord, I imagine you understand the limitations of our platform.

For folks devving for mac and linux, using our GameSDK to check the status of the overlay and hooking up UI/leaving it to our overlay accordingly is the appropriate way to handle it. If, like many others, you're focused on the Windows gaming use case, feel free to let Discord handle it all!
