### ISSUE TITLE
Images in gallery do not show when tab is selected.

### ISSUE THREAD

**Issue by HowlerSpiritWolf** [discordapp/discord-rpc#256]
When I pull up my gallery tab to choose a picture I'm met with a grey screen, when I tap on one of the grey blocks it acts like I'm tapping a picture but I cannot view the picture. I've tried restarting the app, restarting my device, clearing the cache, and even going as far as reinstaling the app after I had promptly deleted it, trying to fix the issue to no avail. If anyone has any advice for getting this to work please let me know.

**Comment by msciotti** [comment]
Didn't get a repro on this, and our dev portal has been through a few iterations since this issue. If anyone is still having problems uploading assets for Rich Presence, please let us know!
