### ISSUE TITLE
discord rpc code signing on Mac OS version 10.10 support not working

### ISSUE THREAD

**Issue by anupbelambe** [discordapp/discord-rpc#259]
Platform: Mac OSx 10.10

Came across a issue where the libdiscord-rpc.dylib (dynamic library) could not be loaded due to signing issue. We are seeing following error while loading the library.

Reason: no suitable image found.  Did find:   /Applications/abc.app/Contents/MacOS/../Frameworks/dependencies/libdiscord-rpc.dylib: **code signature invalid for '/Applications/anc.app/Contents/MacOS/../Frameworks/dependencies/libdiscord-rpc.dylib'**

On doing some research came across following stackoverflow discussion which points to the root cause
https://stackoverflow.com/questions/41865537/how-does-apples-codesign-utility-decide-which-sha-algorithms-to-sign-a-shared/41868747

The 10.10.x version of Mac OS requires libraries to have sha1 hash in your code signature  while later Mac OS releases require  =SHA-256 hashes.

The codesign utility applies the hashes based on the LC_VERSION_MIN_MACOSX which is 10.12 on the libdiscord-rpc.dylib.

What is the minimum MAC OS version supported by the discord-rpc sdk?
Also the same needs to be reflected on the prebuild mac osx binaries.

**Comment by msciotti** [comment]
So, this one's a little outside my wheelhouse. I spoke with one of our native engineers, and we think we can make a change in our `src/CMakeLists.txt` to make it work. I'll open a PR and tag it back here and see if we can get this sorted.

Apologies in advance if this requires a little back and forth. Definitely outside my normal realm of knowledge.
