### ISSUE TITLE
"Admin Mode" breaks RPC (Demanded by some games like MTGA)

### ISSUE THREAD

**Issue by dylanh724** [discordapp/discord-rpc#261]
**EDIT:** Ok, so it's admin mode that's causing this. I remember _MTG Arena_ demanded I set Discord to admin mode to use voice chat, and so I did. This completely broke RPC for every other game that's not also in admin mode.

(_and, off-topic, also breaks drag+drop file sharing_)

What can be done about this? Why do some games demand Discord ran as admin? It breaks a TON of things. There needs to be some way to either discourage the use of games encouraging end-users to run Discord as admin OR provide workarounds for those running with admin.
__________________

![image](https://user-images.githubusercontent.com/8840024/50372190-902cc600-0604-11e9-8d76-831979b1c305.png)

Anyone know what would cause this? Seemed fine earlier, suddenly nothing's happening.

On the live game, I get "Just started playing" that never updates (the default start rpc for known games).

Within Unity, I don't even get that -- just nothing. It used to give me full rpc in Unity, but no longer does.

If others can get it fine, seems like it's just me. What would cause this? Win10.

**Comment by msciotti** [comment]
The only times that Discord need to be run as admin is when, I think, games themselves are running as admin. It should only affect the ability to use push to talk voice mode, as programs can't "listen to" key inputs when programs with elevated permissions are focused if they do not also have elevated permissions.

That's my very rudimentary understanding, at least.

Running as admin should not break Rich Presence, at least as far as I understand. If you open your Discord console, can you confirm that that RPC connection is never happening? Not within game logs, but within the Discord console.

Could I also ask what you mean by MTGA "demanding" Discord be run in admin mode? I play MTGA fairly often myself; is this something their support team told you?

**Comment by msciotti** [comment]
Closing this for cleanup—if anyone is having issues with connection to Discord while running as admin with our new GameSDK, please let us know! You can contact us in the help server at https://discord.gg/discord-gamesdk
