### ISSUE TITLE
Discord RP not working on Mac OS 10.10

### ISSUE THREAD

**Issue by anupbelambe** [discordapp/discord-rpc#268]
Discord Rich Presence stopped working on Mac OS 10.10.
In discord debug console (CMD+ Opt + i) following error is being reported
Uncaught (in promise) Error: dlopen(/Users/yosemite/Library/Application Support/discord/0.0.254/modules/discord_rpc/discord_rpc.node, 1): Library not loaded: @rpath/libcrypto.dylib   Referenced from: /Users/yosemite/Library/Application Support/discord/0.0.254/modules/discord_rpc/discord_rpc.node   Reason: Incompatible library version: discord_rpc.node requires version 1.0.0 or later, but libcrypto.0.9.8.dylib provides version 0.9.8     at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)     at Object.Module._extensions..node (internal/modules/cjs/loader.js:722)     at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)     at Module.load (internal/modules/cjs/loader.js:602)     at tryModuleLoad (internal/modules/cjs/loader.js:541)     at Function.Module._load (internal/modules/cjs/loader.js:533)     at Module.require (internal/modules/cjs/loader.js:640)     at require (internal/modules/cjs/helpers.js:20)     at Object.<anonymous> (Users/yosemite/Libra…scord_rpc/uws.js:30)     at Object.<anonymous> (Users/yosemite/Libra…cord_rpc/uws.js:525)     at Module._compile (internal/modules/cjs/loader.js:693)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)     at Module.load (internal/modules/cjs/loader.js:602)     at tryModuleLoad (internal/modules/cjs/loader.js:541)     at Function.Module._load (internal/modules/cjs/loader.js:533)     at Module.require (internal/modules/cjs/loader.js:640)     at require (internal/modules/cjs/helpers.js:20)     at Object.<anonymous> (Users/yosemite/Libra…discord_rpc/ws.js:8)     at Object.<anonymous> (Users/yosemite/Libra…iscord_rpc/ws.js:11)     at Module._compile (internal/modules/cjs/loader.js:693)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)     at Module.load (internal/modules/cjs/loader.js:602)     at tryModuleLoad (internal/modules/cjs/loader.js:541)     at Function.Module._load (internal/modules/cjs/loader.js:533)     at Module.require (internal/modules/cjs/loader.js:640)     at require (internal/modules/cjs/helpers.js:20)     at Object.<anonymous> (Users/yosemite/Libra…cord_rpc/index.js:1)     at Object.<anonymous> (Users/yosemite/Libra…cord_rpc/index.js:7)     at Module._compile (internal/modules/cjs/loader.js:693)     at Object.Module._extensions..js (internal/modules/cjs/loader.js:704)     at Module.load (internal/modules/cjs/loader.js:602)     at tryModuleLoad (internal/modules/cjs/loader.js:541)     at Function.Module._load (internal/modules/cjs/loader.js:533)     at Module.require (internal/modules/cjs/loader.js:640)     at require (internal/modules/cjs/helpers.js:20)     at requireModule (evalmachine.<anonymous>:6)     at Object.requireModule (Users/yosemite/Libra…nativeModules.js:86)     at Object.requireModule (8247725….js:62)     at Object.<anonymous> (8247725….js:74)     at Object.<anonymous> (8247725….js:74)     at t (7771eaa….js:1)     at t.loadServer (8247725….js:90)     at 8247725….js:62

On triggering the update rich presence call, not seeing any activity being reported in the discord console.

Discord Rich Presence is working fine on later versions of Mac OS.

Let me know if any additional information is required.

**Comment by msciotti** [comment]
Hey there! How are you attempting to use the SDK? Within Unity, UE4, XCode, something else?

**Comment by anupbelambe** [comment]
We are integrating the prebuilt SDK from https://github.com/discordapp/discord-rpc/issues/259.
The fix was working earlier.
The above issue seen is in discord. So suspecting this to be the root cause issue.

**Comment by msciotti** [comment]
Hm, I wonder if this is some arcane side-effect of recent electron upgrades in Discord. Which Discord client are you testing with? If Stable, can you try Canary? Or vice-versa

**Comment by anupbelambe** [comment]
We are using stable version of discord client

**Comment by msciotti** [comment]
Could you try the Canary client? You can get it here:

**Comment by anupbelambe** [comment]
Will try canary build and get back. I believe the problem seems to be with discord. The dependency error can be seen on launching the discord (in console) on Mac OS 10.10.

**Comment by msciotti** [comment]
Great to hear! We're trying to diagnose what went wrong here. Did this work for you previously and stopped working sometime recently?

Canary gets shipped to stable somewhat frequently. I think there was a stable update this afternoon if you wanna give it a try.

**Comment by anupbelambe** [comment]
Can you please confirm the canary fix was migrated to stable build?

**Comment by msciotti** [comment]
By now it should have been, as canary updates get shipped to stable decently regularly. I don't have access to a mac with 10.10 on it, so if you could confirm it working that'd actually be very helpful.

**Comment by anupbelambe** [comment]
The issue is still reproducible on the mac with 10.10 with the same reported error.
Seems like the canary fix has not been shipped into stable yet.

**Comment by anupbelambe** [comment]
@msciotti 
Any update on this? Appreciate your help in getting this resolved. We already seem to be having a fix in canary which requires to be propogated in stable build.

**Comment by msciotti** [comment]
@anupbelambe sorry for this delay; other duties and personal issues kept me from being on top of this repo. Is everything working alright for you now?

**Comment by msciotti** [comment]
(I believe whatever fix this was, as it was on Canary as of February something, has most definitely gotten through all versions of Discord by now. If the problem persists, please re-open the issue!)
