### ISSUE TITLE
handleDiscordReady does not fire anymore

### ISSUE THREAD

**Issue by vadi2** [discordapp/discord-rpc#269]
Our Discord integration in Mudlet (`450571881909583884`) used to work fine before, but now it doesn't. We're still calling `Discord_Initialize()` as before.

The only thing that could have potentially changed is that we transferred the Discord Application from an individual developer account to a Discord team account.

Discord consistently gives the following error message in debug:

```
aafd1b7e051208c1dbba.js:135 [RunningGameStore] games [{…}]
aafd1b7e051208c1dbba.js:135 Tried getting Dispatch instance before instantiated
e.(anonymous function) @ aafd1b7e051208c1dbba.js:135
h @ aafd1b7e051208c1dbba.js:62
pause @ aafd1b7e051208c1dbba.js:62
t.pause @ aafd1b7e051208c1dbba.js:40
G @ aafd1b7e051208c1dbba.js:45
(anonymous) @ aafd1b7e051208c1dbba.js:45
runCallback @ timers.js:694
tryOnImmediate @ timers.js:665
processImmediate @ timers.js:647
aafd1b7e051208c1dbba.js:135 Error: Error 1 when fetching info on 10168
    at aafd1b7e051208c1dbba.js:40
e.(anonymous function) @ aafd1b7e051208c1dbba.js:135
(anonymous) @ 78ef2bacf4821012a2b5.js:1
Promise.catch (async)
componentDidUpdate @ 78ef2bacf4821012a2b5.js:1
da @ aafd1b7e051208c1dbba.js:117
fa @ aafd1b7e051208c1dbba.js:117
ca @ aafd1b7e051208c1dbba.js:117
_a @ aafd1b7e051208c1dbba.js:117
e.emitChanges @ aafd1b7e051208c1dbba.js:45
n._stopDispatching @ aafd1b7e051208c1dbba.js:127
e.dispatch @ aafd1b7e051208c1dbba.js:127
n.dispatch @ aafd1b7e051208c1dbba.js:127
n.dirtyDispatch @ aafd1b7e051208c1dbba.js:127
j @ aafd1b7e051208c1dbba.js:33
(anonymous) @ aafd1b7e051208c1dbba.js:33
(anonymous) @ aafd1b7e051208c1dbba.js:62
```

This is using Ubuntu 18.10 with the pre-packaged `.so` from Discord releases (sha256: `ae74dde38496ca8c726c79e09f78b836047e779c80f8aabce52a857f31304d4b`).

What could be going wrong?

**Comment by vadi2** [comment]
Latest `.so` (`fc5fd6b8b7951b43bec9c4b6baa53a2f5779ef1588b22768b6c5cc39fc5e7a4a`) doesn't seem to make much of a difference.

**Comment by msciotti** [comment]
Hmmm. Moving to a team wouldn't affect this. Are you using Discord Canary, Stable, or PTB for this testing? It sounds fishily similar to missing JS package stuff in the macos 10.10 issue maybe? Perhaps electron upgrade woes?

**Comment by vadi2** [comment]
Discord Stable client. It's working now that I test on another machine - odd, but maybe it's something on my end!
