### ISSUE TITLE
Add java support please <3

### ISSUE THREAD

**Issue by Azim-D3Tm** [discordapp/discord-rpc#27]

**Comment by PSNRigner** [comment]
I'm working on a Java implementation of this SDK, right now Windows is 99% supported (missing 2 small details with registry), but Linux is not yet started. I'll give more info when i'm done.

Note : I'm not affiliated at all with Discord, i'm just converting this SDK to Java for fun and learning.

**Comment by Azim-D3Tm** [comment]
Thank you very much! Hope to see it soon :D

**Comment by crmarsh** [comment]
I wonder if doing a jni thing with this would be worthwhile. Overall, this is pretty simple (I think?) to rewrite in whatever language, but it would be nice if there was a single place to add new features. That's sorta why I went the wrapper route for the Unity C# example, for instance.

**Comment by mataide** [comment]
@PSNRigner Will you put the project in a Github repository? So we can contribute with.

Thanks

**Comment by PSNRigner** [comment]
@mataide Yes i will, tomorrow.

**Comment by PSNRigner** [comment]
Here it is, it's just a first draft, there are still a few things to test / fix (look in the issues if you wish to contribute)

https://github.com/PSNRigner/discord-rpc-java

**Comment by MinnDevelopment** [comment]
I made a basic JNA binding for this yesterday https://github.com/MinnDevelopment/Java-DiscordRPC

**Comment by Vatuu** [comment]
I also created a Java Wrapper for this, with JNA.
It deploys the DLLs automaticly based on your architecture, and I am adding Linux support today.

https://github.com/Vatuu/discord-rpc

**Comment by mataide** [comment]
Hey Guys, What about we work as team in just one project? @PSNRigner @MinnDevelopment @Vatuu

**Comment by MinnDevelopment** [comment]
PSNRigner implemented the whole SDK in java while Vatuu and I just made a JNA binding for the SDK.
The JNA bindings don't need to be maintained really which means I'll most likely not continue working on it anyway.

**Comment by Bluexin** [comment]
Oh I just found this issue, I've made a wrapper lib in Kotlin (so also jvm), using jna too :')
Was working on reimplementing everything too though.

**Comment by msciotti** [comment]
I've added a table to the ReadMe for community wrappers around and implementations for Rich Presence. If you folks in this thread have wrappers or implementations that you'd like to add for others to use, please feel free to make a PR adding them to the table (make sure they include the requested information!)

https://github.com/discordapp/discord-rpc/commit/8cae35ea464475328934fea5df4f3e39480d1c58
