### ISSUE TITLE
Show more information on invitations

### ISSUE THREAD

**Issue by fr500** [discordapp/discord-rpc#270]
![image](https://user-images.githubusercontent.com/1721040/52323711-0a928900-29ac-11e9-90b4-a942552681b1.png)

Is it possible to have at least a second line of information on these invites?
Thing is, our application runs a multitude of games, so being able to show more information (say... hosting mario kart) or something like that would be great for us.

**Comment by Lachee** [comment]
maybe putting the state or description as a second line?

**Comment by fr500** [comment]
state would do it for us:

![image](https://user-images.githubusercontent.com/1721040/52323857-cbb10300-29ac-11e9-8ebc-b1398b84e8d1.png)

**Comment by furiadeoso** [comment]
I think the number of possible states 
in discord is limited. At least number of assets is limited to 150. 

We can make a state (and asset) for each core, but I think that will not be showed on group invites.

I can help designing assets, if needed.

**Comment by fr500** [comment]
The state is just a text label. It's arbitrary.

**Comment by msciotti** [comment]
Closing this because I believe it's been migrated to the feedback site for the GameSDK, but uh, maybe we have some ideas here 👀
