### ISSUE TITLE
32-bit Linux builds

### ISSUE THREAD

**Issue by SlidyBat** [discordapp/discord-rpc#271]
Any chance of getting 32-bit Linux builds in the release? I'm trying to integrate this into a Source Engine mod (which only supports 32-bit) and it's been a bit of a pain getting it to work with Linux. Including the pre-built 32-bit binaries would make life a lot easier.

Thanks.

**Comment by IntriguingTiles** [comment]
Just to let you know, the client on Linux and macOS tries to load discord-rpc from the bin folder of whatever AppID your mod is using instead of where your client and server binaries are for some reason.

**Comment by xsellier** [comment]
You can do it yourself:
https://gist.github.com/Swyter/98074d2d42cd7f7c0e5f86ef619969d3

**Comment by msciotti** [comment]
Hey there!

We aren't going to officially support 32bit linux at this time. It looks like xsellier posted something that may help you move forward on this. Apologies for the frustration (and very late comment).
