### ISSUE TITLE
Plugin Doesn't Compile For UE 4.19

### ISSUE THREAD

**Issue by tbjbu2** [discordapp/discord-rpc#272]
Plugin Doesn't Compile For UE 4.19
![image](https://user-images.githubusercontent.com/10721266/52906394-9aa9bb80-3253-11e9-984c-eb9f1004ca5d.png)
Can we get a sample project for UE 4.19?

**Comment by msciotti** [comment]
Hm. I don't know enough about the magic of unreal engine. Is this saying the linking when trying to create the DLL messed up?

**Comment by tbjbu2** [comment]
I ended up following this tutorial https://www.youtube.com/watch?v=OJVk03Ynj8g
and downloading version 2.0.1. Then it worked.

**Comment by msciotti** [comment]
Huh, well, that's handy. I'll take a look at this video today and see if I can update the documentation if something is lacking. Thanks for the link!
