### ISSUE TITLE
Confusing 'Now playing' listing

### ISSUE THREAD

**Issue by vadi2** [discordapp/discord-rpc#273]
Is it intended to look like this? The layout does not make any sense:

![selection_363](https://user-images.githubusercontent.com/110988/52998978-e1024480-3424-11e9-87db-c6e7ee92b8f8.png)

**Comment by msciotti** [comment]
It looks like Mudlet isn't sending any presence data other than an image? Does this look different on one of those user's profiles if you click them?

**Comment by vadi2** [comment]
That's right - by default not much more than an image. I'd expect all of the entries to be consolidated?

Here's how it looks like when you click on somebody: 
![image](https://user-images.githubusercontent.com/110988/53037700-29e4e800-347b-11e9-9151-409503e265dd.png)

**Comment by msciotti** [comment]
The Now Playing section is user based, I believe. Whereas the "recently played" is per game. They'd be consolidated if the users were in a party together (all had the same `partyId` set). Then you'd see them in one card.

**Comment by vadi2** [comment]
Okay!
