### ISSUE TITLE
Visual Studio 2010 Discord RPC 

### ISSUE THREAD

**Issue by Naratzull** [discordapp/discord-rpc#276]
How can I compile a project with the Discord RPC library using the Visual Studio 2010 compiler?

**Comment by msciotti** [comment]
Depends what language I suppose? Forgive my ignorance ahead of time as I'm not an expert in linking libraries and whatnot, but what I've found is:

C# - Include the .dll and .lib files in the project folder. Use `[DllImport]` tags to reference functions within the SDK, like so:

https://github.com/discordapp/discord-rpc/blob/master/examples/button-clicker/Assets/DiscordRpc.cs#L96-L97

C++ - Include the .dll and .lib files in the project folder. You can then add them to the project by doing `Project -> Properties -> Configuration Properties -> Linker -> Additional Dependencies`

I think you can also do some magic with like:

```cpp
#pragma comment(lib, "discord-rpc.lib")
```

According to a few StackOverflow responses like: https://stackoverflow.com/a/7845999

I'll leave this open for people who actually know what they're talking about to chime in, but those have worked alright for me in the past.

**Comment by Naratzull** [comment]
C++. The project is on VS 2010 and when I use the static RPC library, the linker refuses to build the source code associated with RPC. Error: LNK2019: unresolved external system referenced in function. I read, that cannot use the library created, for example, on VS 2015 in VS 2010

**Comment by msciotti** [comment]
Frankly, I'm not sure. I'll put this on my list of things to look at. But, I'm not sure this is an issue with the library. I'll leave this open if someone else is willing to chime in. Otherwise, I'll see what I can figure out.

**Comment by Naratzull** [comment]
Can I only use a dynamic library (.dll file). For in the folder with the dynamic library is still .lib.

**Comment by Naratzull** [comment]
Thank you so much! I compiled a project with a dynamic library according to your instructions and PROFIT.

**Comment by msciotti** [comment]
Awesome! Great work! I'll close this issue then
