### ISSUE TITLE
Unreal engine 4 Rich Presence Discord SDK Not Working

### ISSUE THREAD

**Issue by bobost2** [discordapp/discord-rpc#279]
So, I'm creating a game in UE4 v.4.21.2 and I decided to integrate Rich Presence, followed all instructions and didn't worked (Plugin uncompatable with version). So did I did something wrong or the version is incompatable and is there any way to make it work with the new version, because if I downgrade my game files will be damaged.

If you need anything else ask me.

**Comment by infinitegachi** [comment]
Same here, tried rebuilding it same problem occurs

**Comment by infinitegachi** [comment]
I managed to fix it

**Comment by SlapstickChapstick** [comment]
> I managed to fix it

How, you could have said how?

**Comment by disseminate** [comment]
Great work @radva , thanks

**Comment by msciotti** [comment]
Doing some cleanup—closing this in favor of moving to the new SDK and due to quiet around the issue.
