### ISSUE TITLE
Spectate Missing

### ISSUE THREAD

**Issue by Lachee** [discordapp/discord-rpc#280]
The spectate button is currently missing from the Rich Presence despite the spectate secret being filled. 
![Spectate Missing](https://s.lu.je/dav/bastion_tl1ra_20190314_2022.png)
![Discord Response](https://s.lu.je/dav/bastion_f7tob_20190314_2025.png)

Am I missing something that needs to be set? I was certain this was something my example code use to do flawlessly. (and what is this mysterious flags field owo)

**Edit**
Confirmed it not working with a separate account on Canary: 
![nowork](https://s.lu.je/dav/bastion_30l98_20190314_2027.png)

**Comment by Lachee** [comment]
Figured it out
You require separate permission to have a spectate button that you must apply for with a video. This brings up even more questions however such as:

* Why does spectate need approval but join doesnt?
* Why didnt my previous whitelisted accounts get carried over to the new system?
* How is one suppose to test it without actually having access to the button to begin with
* How is one suppose to submit a video without the access to show it working.

Maybe @msciotti can help on this one.

**Comment by msciotti** [comment]
Sorry for the late response, Lachee. Some personal stuff over the last couple months has given me less time to manage this repo on top of my normal daily work.  Let me answer this in order:

**Why does Spectate require approval?**
When we first implemented Rich Presence, Ask to Join and Spectate required approval by Discord to enable for all users for your game. At the time, Ask to Join and Spectate requests were seen by the user either:

1. In the Discord client, in a banner at the top
2. From a developer creating UI in their game to handle the events

To make sure that users had a good experience using Rich Presence, we wanted to ensure that a dev had done #2 before being allowed to release widely, as most users probably aren't going to notice a small banner in Discord asking to join while they're in a game.

When we released our new overlay, we made it handle Ask to Join requests. We felt that was enough to handle the event for most users, so we removed the whitelist requirement. The overlay does _not_ handle spectate events, so we still want devs to create UI for spectate events and therefore require approval (for us to make sure you do, in fact, have UI for it).

**Previous whitelisted accounts and the new system**
I'll be honest, I'm not sure to which new system you're referring. Could you tell me?

**Testing without "having access"**
You can, in fact, whitelist specific users to enable the button on only their profiles for testing. From the [documentation](https://discordapp.com/developers/docs/rich-presence/how-to#spectating):

```
To enable the Spectate button on your players' profiles, you'll need to be approved by us. Submit your integration for approval on your app's developer dashboard. While there, you can also whitelist individual accounts for testing. Those accounts will have the Spectate button enabled on their profiles. For an in-depth explanation of what we look for during approval, see Getting Approved.
```

**Submit a video without access**
Same as above—you can use the whitelist to enable specific users, build and test the integration with those accounts, and submit the video to us.

---

I hope that answers your above questions. Please tell me if any of that is unclear!
