### ISSUE TITLE
[Feature Request] "Spotify-exclusive" API for Developers via RPC

### ISSUE THREAD

**Issue by enhsaihan-d** [discordapp/discord-rpc#281]
Is it possible to implement Spotify-exclusive features via RPC? Those includes:

- Custom [activity name](https://discordapp.com/developers/docs/topics/gateway#activity-object-activity-structure) like **Playing/Listening to [X]** instead of static **Playing a game**.
- Activity type. I believe this is extremely needed feature for many developers.
- Custom game name. Spotify uses this field to show what song is playing.
- Links. Game name, details and state field of Spotify supports links.
- Art Assets API. Spotify Album Thumbnail pictures aren't hosted on Discord.
- Progress Bar.

**Comment by Lachee** [comment]
None of these are possible for non Spotify users, hence the term exclusive. At all without breaking tos. 

As for requesting the ability to add it for non Spotify, a lot of these feature would be awesome and some have already got requests open on this GitHub.

**Comment by msciotti** [comment]
Hi enhsailhan,

With #290 , we're going to moving all feature requests to here:

https://support-dev.discordapp.com/hc/en-us/community/topics

Would you mind creating this request over there? I'm also happy to do it for you.

**Comment by enhsaihan-d** [comment]
> I'm also happy to do it for you.

I would really appreciate it!

**Comment by msciotti** [comment]
I think as Lachee pointed out, a lot of these may be covered in other feature requests. So I'll go through existing ones and then copy whatever's left from here.

**Comment by msciotti** [comment]
Moved to [here](https://support-dev.discordapp.com/hc/en-us/community/posts/360043641772-Allow-use-of-progress-bar-links-in-activity)
