### ISSUE TITLE
Failed to load DiscordRpc plugin. Plug-in will be not functional.

### ISSUE THREAD

**Issue by NerofleLincoln** [discordapp/discord-rpc#284]
I followed this tutorial https://www.youtube.com/watch?v=OJVk03Ynj8g but I couldn't compile. I fix one error with this link https://answers.unrealengine.com/questions/822711/atomich-error-in-all-new-projects.html : I added parenthesis before and after (UE4Atomic_Private::TIsSupportedSize<sizeof(T)>::Value
The other error was the discord-rpc.lib which wasn't in the good folder. It was in "discord-rpc-master\discord-rpc-master\examples\unrealstatus\Plugins\discordrpc\Source\ThirdParty\DiscordRpcLibrary\x64\Release\discord-rpc.lib" and I moved it to "discord-rpc-master\discord-rpc-master\examples\unrealstatus\Plugins\discordrpc\Source\ThirdParty\DiscordRpcLibrary\Win64\discord-rpc.lib". But I obtain this message when i want to start thr project unrealstatus : Failed to load DiscordRpc plugin. Plug-in will be not functional. and if I click on Start, Unreal Editor crashes.
Please help me

Thanks for advance
Nerofel Lincoln

**Comment by msciotti** [comment]
Hey there. I apologize that this issue is so late in being addressed. Entirely my fault. You're right, we do seem to have an issue with (maybe just newer?) versions of Unreal throwing this error. I can repro on my own machine, but haven't gotten around to figuring out what's up. Just wanna let you know there's eyes on it!

**Comment by msciotti** [comment]
This is a very late reply, but I think if you're still seeing issues and want to integrate, you'd be best to move to our GameSDK, which should be perfectly compatible with newer Unreal versions.

https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide

If you need help, come join us in the Discord at https://discord.gg/discord-gamesdk !
