### ISSUE TITLE
(Unity) Visual C++ exception on starting play mode

### ISSUE THREAD

**Issue by Tetriser** [discordapp/discord-rpc#285]
So, I just wanted to try out the Discord RPC plugin for my Unity project. However, there seem to be something in my initialization code that crashes Unity completely with a VC++ exception at my end.

Weirdly enough, it spits a blank error that I don't even understand why.

![Unity_2019-04-02_11-31-54](https://user-images.githubusercontent.com/5746458/55374839-850aff80-553c-11e9-98b2-ff89468ecef9.png)

Here's my code:
```
using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class DiscordRPCController : GenericSingleton<DiscordRPCController>
{
    //Thanks Discord!

    public string appID;
    public string optionalSteamID;
    DiscordRpc.RichPresence presence;
    DiscordRpc.EventHandlers handlers;

    public override void Awake()
    {
        base.Awake();
        DiscordRpc.Initialize(appID, ref handlers, true, "");

        handlers.readyCallback += ReadyCB;
        handlers.errorCallback += ErrorCB;
    }

    private void ReadyCB(ref DiscordRpc.DiscordUser connectedUser)
    {
        Debug.Log("Ready! Logged in as " + connectedUser.username + ".");
    }

    public void UpdatePresence(string details, string state, string imageKey, string imageText)
    {
        presence.details = details;
        presence.state = state;
        presence.largeImageKey = imageKey;
        presence.largeImageText = imageText;

        //Thanks to sonnyyap for the Epoch solution - http://answers.unity.com/answers/876197/view.html

        System.DateTime epochStart = new System.DateTime(1970, 1, 1, 0, 0, 0, System.DateTimeKind.Utc);
        int cur_time = (int)(System.DateTime.UtcNow - epochStart).TotalSeconds;

        presence.startTimestamp = cur_time;

        DiscordRpc.UpdatePresence(presence);
    }

    private void Update()
    {
        DiscordRpc.RunCallbacks();
    }

    void ErrorCB(int errorCode, string message)
    {
        Debug.LogWarning("<b>There's an error with Discord RPC</b>" + "\n" + message);
    }
}
```

**Comment by msciotti** [comment]
Hey Tetriser, sorry for the delay. I'll copy this code into my sample project and see if I can suss anything out.

**Comment by msciotti** [comment]
Couple immediate notes, might just be missing this based on the rest of your code:

Seems like you aren't `new`-ing up either your `Discord.RichPresence` or your `Discord.EventHandlers`. Those should yell at you for null reference exceptions, but perhaps Unity's just getting mad and crashing?

**Comment by Tetriser** [comment]
Sorry for late reply, but yeah apparently I forgot to `new` those.

**Comment by Tetriser** [comment]
Sorry for late reply, but yeah apparently I forgot to `new` those.

**Comment by Tetriser** [comment]
And yes it just crashed like that.

**Comment by msciotti** [comment]
Does `new`ing those fix it? Or still crashing?

**Comment by Tetriser** [comment]
`new`ing them fixed the issue. Thanks for reaching me. Closing the issue now.
