### ISSUE TITLE
Media doesn't load (Pictures, Videos)

### ISSUE THREAD

**Issue by wyxe905** [discordapp/discord-rpc#288]
My issue affects much more than Discord, and I've tried so many different things to fix it to no avail, wasted a day on it. I'm not asking for a fix, I'm asking if there's a workaround. Or if somebody actually has a fix, I would be very appreciative.

(Brand New Computer, I just built it)
I'm on Windows 10, latest update. Google Chrome, as it turns out, doesn't load websites that start with https, it can't securely connect. I knew it wasn't an internet issue because Edge connected just fine. Fast Forward a day and I fix the issue by sucking it up and getting Firefox instead. It has a tick every now and again, but i've been fine with the change.

Discord has also been asking up. And I went to google looking for a fix, and found a thread on here which had the solution of opening the console and clearing the cache. I noticed the console looks identical to Chrome's, and now I'm afraid I'm having the same problem all over again.

Is there a workaround for this? A different version with a different API or whatever it happens to use, that I could test out? Or does somebody here actually know of a proper fix?

**Comment by msciotti** [comment]
Um, apologies wyxe, but I'm not sure we're going to be of much help here. Yes, Discord does have a console similar to Chrome's, as Discord is an Electron application.

This question is outside the scope of this GitHub repo, so I'm going to close the issue. As a last attempt to not send you off with nothing, perhaps make sure any ad blockers you're running aren't configured strangely? Any user scripts in Chrome you've got going? Firewall stuff maybe?

Good luck figuring it out and I'm sorry that this repo can't be of more help.
