### ISSUE TITLE
Rapidjson/document.h No such file or directory

### ISSUE THREAD

**Issue by DiscordPug** [discordapp/discord-rpc#291]
I need a Help 
When i do Compile i get this error 
![image](https://user-images.githubusercontent.com/51095848/58436748-9cdfa980-80cf-11e9-973c-d46bc241f013.png)

**Comment by msciotti** [comment]
Have you installed the `Rapidjson` package? The SDK is dependent on that package; it's automatically installed if you're using the sample apps when you run `python build.py unreal` or `python build.py unity` from the root directory of the SDK zip.

Or, I might recommend swapping to our new SDK: https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide

**Comment by DiscordPug** [comment]
Thank you so much!
