### ISSUE TITLE
Games shows not up by another

### ISSUE THREAD

**Issue by TheCherry** [discordapp/discord-rpc#292]
Games dont show up currently by another ppl.
You can see the game by yourself, but another dont see it.
Spotify and custom games works.

Even a bot, can't get the information, its seems that the API dont give that information to the clients.

**Comment by legoandmars** [comment]
I am also experiencing this and have talked to other people that have

it's a pretty widespread issue, there's a thread on r/discordapp with 700 upvotes right now

**Comment by RowanHall** [comment]
same here, as author of https://github.com/RowanHall/desktop-youtube-music/ , a whole chunk of my project is based off of allowing you to listen with other people. When this doesn't work it kinda ruins a part of the point of it

**Comment by msciotti** [comment]
I think this might have something similar to do with https://github.com/discordapp/discord-rpc/issues/293

Can you confirm if it's still happening? We had an issue with Activity stuff that was fixed and deployed on Sunday afternoon PST.

**Comment by msciotti** [comment]
This was fixed.
