### ISSUE TITLE
Rich Presence does not show up for anyone other than the client

### ISSUE THREAD

**Issue by RowanHall** [discordapp/discord-rpc#293]
... and invites are also broken (the plus next to the send message)

The code can be found here: https://github.com/RowanHall/desktop-youtube-music/

I have absolutely no idea why this is happening

**Comment by msciotti** [comment]
Can you confirm if this is still happening? We had some Rich Presence issues over the weekend and a fix was deployed Sunday afternoon PST!

**Comment by RowanHall** [comment]
Can confirm it is fixed, thanks msciotti!
