### ISSUE TITLE
forza horizon 4 is not getting detect

### ISSUE THREAD

**Issue by qiangqiang101** [discordapp/discord-rpc#294]
forza horizon 4 is not getting detect but forza horizon 3 does

i'll have to manually add everytime i play fh4

**Comment by SinisterRectus** [comment]
This sounds like a client issue, not an API issue. You probably want to visit and maybe contact Discord support at https://support.discordapp.com/hc/en-us. If you suspect that there is a client bug, try https://discord.gg/discord-testers
