### ISSUE TITLE
Images not showing in android app

### ISSUE THREAD

**Issue by ve3lst** [discordapp/discord-rpc#295]
Hi,

  I have discord 9.0.9 on android 4.1, but I cant see thumbnails at all, just black boxes. Friend have same version on a newer android with same issue. 
Tried old versions like 7.7.9 and 6.x
No images, but no black boxes
Tried turning off and on all the setting in text & images tab with no luck

Any help

Thanks

**Comment by JanHolger** [comment]
@ve3lst This is not the repository of the discord app itself. Submit your request at https://support.discordapp.com/hc/en-us/requests/new if you need any help regarding Discord.
