### ISSUE TITLE
Only limited access to the RPC API?

### ISSUE THREAD

**Issue by JanHolger** [discordapp/discord-rpc#297]
Hi,
I am trying to implement positional ingame audio like TFAR/GTAVoice does for teamspeak. Using the GameSDK seems to be way to much for just setting audio balance / volume of the channels clients so I decided to try the rpc interface.

I implemented a custom java client which connects to the ipc pipe and thats working fine so far (I'm able to send commands and receive the events). When I send an Authorize Command my Discord shows up the authorization window with the correct scopes but after authorizing i receive the following OAuth error:
```json
{"cmd":"AUTHORIZE","data":{"code":5000,"message":"OAuth2 Error: invalid_scope: The requested scope is invalid, unknown, or malformed."},"evt":"ERROR","nonce":"asdf"}
```
The Request:
```json
{"cmd":"AUTHORIZE","args":{"client_id":"MY_CLIENT_ID","scopes":["rpc.api","rpc"]},"nonce":"asdf"}
```
Is the pipe api just capable of updating the rich presence?

I also tried using the websocket api, but there is no way to whitelist any origins in the dashboard and the docs say that its in private beta which makes absolutly no sense to me when there is already a new gamesdk.

Is it possible to get an access token for rpc using the normal OAuth Flow and then send an 
 Authenticate Command or is my approach completly pointless?

**Comment by Lachee** [comment]
> Is the pipe api just capable of updating the rich presence?
Yes, pretty much. The GameSDK uses it more extensively I believe.

> I also tried using the websocket api
That API has been closed for a while, and even while it was opened it was considered "Closed Beta".

> Is it possible to get an access token for rpc using the normal OAuth Flow
Nope

Probably worth reading up on this: https://github.com/discordapp/discord-rpc/issues/290

**Comment by JanHolger** [comment]
> That API has been closed for a while, and even while it was opened it was considered "Closed Beta".  

Then it might be a good idea for the team to remove it from the docs, as it seems to be unusable even for whitelisted apps.

> Probably worth reading up on this: #290  

I already read the Deprecation-Issue, but unfortunatly the gamesdk seems to be closed source so it will be pretty hard to reverse engineer the interfaces used and I don't want to use the JNI. Another point is that I am on linux and I couldn't find any shared library file for linux or darwin. For me it seems to be a step backwards dropping support for an existing library in favour of a new one that isn't ready 
 (missing darwin and linux support), but thats just my opinion.

Thanks for your answers anyway :+1:

**Comment by night** [comment]
The IPC and WebSocket RPC interfaces are identical apart from connection transport used. The Game SDK as well as this library just implement the RPC. The reason you're getting issues is because you're requesting `rpc.api` access. Remove that restricted scope, and it will work fine assuming you're the application owner or a whitelisted user on the application. Only via IPC are you allowed to access more commands without authentication. WebSocket interface is useful for web applications, and is used by things like our stream overlay (subject to approval).

I would ultimately recommend using our SDK versus implementing our protocols yourself. It does work on Windows and OSX. Linux might come in the future.

**Comment by JanHolger** [comment]
I've just seen your answer in my e-mail spamfolder. This issue is a bit dusty, but I thought it might still be a good idea to share the following so nobody else puts any effort in trying out your suggestions :)

Just to make sure you understood right: I am actually using IPC like I said in the issue already. I couldn't get any valid connection using the websocket interface. I took a look at this library and replicated it in Java (https://github.com/JanHolger/DiscordRPCTest).

Trying to do anything advanced without authentication leads to the following error:
```json
{"cmd":"SET_USER_VOICE_SETTINGS","data":{"code":4006,"message":"Not authenticated or invalid scope"},"evt":"ERROR","nonce":"asdf"}
```

Requesting just `rpc` via IPC being the app owner gives me an error (after authorization in Discord) anyway:
```json
{"cmd":"AUTHORIZE","args":{"client_id":"595***************","scopes":["rpc"]},"nonce":"asdf"}
```
```json
{"cmd":"AUTHORIZE","data":{"code":5000,"message":"OAuth2 Error: invalid_scope: The requested scope is invalid, unknown, or malformed."},"evt":"ERROR","nonce":"asdf"}
```

I already accepted that using Discord for the thing I was trying to implement might not be possible but if the IPC API should be just working fine then it might actually be an error in the api. This might be an Linux related issue as Linux currently isn't supported by the GameSDK.

**Comment by msciotti** [comment]
The RPC scope request specifically is what's failing there. The rich presence/other game SDK functions don't require the RPC scope, and requesting it will do a logic check against our old RPC whitelist, which your application is not a part of lol, so it'll fail

**Comment by JanHolger** [comment]
So SET_USER_VOICE_SETTINGS isn't used by the GameSDK? I wasn't wondering about the fact that requesting the rpc scope fails but the fact that it requires me to be authenticated when using this command via. IPC because of what @night was saying in his comment 

> Only via IPC are you allowed to access more commands without authentication.

I think giving up and switching back to good old teamspeak is the best option for my special usecase.

**Comment by night** [comment]
You don't need to call `AUTHORIZE` or `AUTHENTICATE` when using IPC. Because you're on IPC you're implicitly authenticated with some scopes.

**Comment by msciotti** [comment]
@JanHolger I think we actually use `SET_USER_VOICE_SETTINGS_2` for the game SDK, so as not to break compatibility with older RPC functionality. I know, excellent naming conventions.

Hope that helps illuminate a path forward for you, but if we don't solve the use case, totally understood. Sounds like a cool project!
