### ISSUE TITLE
Help installing

### ISSUE THREAD

**Issue by Bubeboi** [discordapp/discord-rpc#300]
So, I am trying to install discord Rich Presence into my Unreal game, (4.22) and I have put the Plugins folder into my game folder, but I don't know how I would get it to say on Discord "Playing MyGame" or anything, And I can't find any tutorials on YouTube. Thanks in advance,
-Bubeboi

**Comment by Bubeboi** [comment]
Also, I have looked through the other problems, and no one has had this issue as far as I can tell in this section.

**Comment by Bubeboi** [comment]
Oh, and if any one asks, I used this tutorial to get the Plugins setup: https://www.youtube.com/watch?time_continue=85&v=-P0qbcW60Fc

**Comment by Bubeboi** [comment]
(I don't know why it starts in the middle just restart it)

**Comment by Bubeboi** [comment]
Alrighty, so I have done code and stuff, but everything says that it is not getting anything from the Discord variable.

**Comment by Bubeboi** [comment]
And in the log it spams this:
Blueprint Runtime Error: "Accessed None trying to read property Discord". Blueprint:  ThirdPersonCharacter Function:  Execute Ubergraph Third Person Character Graph:  EventGraph Node:  Check for callbacks

**Comment by Bubeboi** [comment]
Still need help

**Comment by msciotti** [comment]
Hey Bubeboi,

Hard to say on that one. That sounds like an error coming from your specific implementation. I assume you're hooking this up via blueprints. Could you show a screenshot of your blueprint editor with all the relevant stuff?

**Comment by Bubeboi** [comment]
Like, on the one with just the plugin, or the example project? I'm confused. I have barely done a thing. Only installed the plugin.

**Comment by Bubeboi** [comment]
I have only installed the plugin. Nothing else. :I wish I could help more. If you want, add me on discord and we can get in a call: Bub#4663

**Comment by msciotti** [comment]
Worked to solve offline! Helped set Bubeboi up with the Unreal example, and working from there.
