### ISSUE TITLE
Discord-RPC Issue.

### ISSUE THREAD

**Issue by CameraRaphamine100** [discordapp/discord-rpc#301]
Hello! Once I open unrealstatus.uproject, Okay, Normal, Then I notice this;
![image](https://user-images.githubusercontent.com/43272916/61908371-e731ab00-af05-11e9-94ba-c281d44015c6.png)
Um okay... I'm rebuilding by the source then...
![image](https://user-images.githubusercontent.com/43272916/61909107-a89cf000-af07-11e9-9651-8be8d57bed53.png)
Nothing works, The DLLs are on their places... What do I do?
Extra pic - C++/C headers on their places (Included Folder)
![image](https://user-images.githubusercontent.com/43272916/61909227-f6195d00-af07-11e9-816c-b67636db9f17.png)
Also, the version I'm using of Unreal Engine is 4.22.

**Comment by msciotti** [comment]
Doing some cleanup. This was a somewhat common issue with UE4 that required you to sometimes create Visual Studio files and build from there.

Should move over to the game SDK if you are still seeing issues: https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide
