### ISSUE TITLE
UnhandledPromiseRejectionWarning: Error: Could not connect

### ISSUE THREAD

**Issue by AustinLeath** [discordapp/discord-rpc#302]
Hey guys, I am fairly sure I found a bug with ipc.js, it is telling me a .catch block is needed an async function. What do you think?
https://i.imgur.com/4GltMf4.png

**Comment by MinnDevelopment** [comment]
There is no javascript in this repository.

Is this a duplicate of [this issue](https://github.com/devsnek/discord-rich-presence/issues/5)?

**Comment by AustinLeath** [comment]
My mistake, and yes, this is a duplicate of that issue. I just thought it was interesting because discord is open AND my app is open which is serving RPC. Issue Closed
