### ISSUE TITLE
Unreal 4.26 compatibility 

### ISSUE THREAD

**Issue by Sarperdgn** [discordapp/discord-rpc#309]
Unreal 4.26 compatibility 
Thats not working on 4.26 on Unreal engine

**Comment by greg6775** [comment]
Use the GameSDK. This one is deprecated

**Comment by Sarperdgn** [comment]
Game sdk? Whats that and how can I install

**Comment by greg6775** [comment]
You can get more information about the GameSDK here: https://discord.com/developers/docs/game-sdk/sdk-starter-guide

**Comment by Sarperdgn** [comment]
Thanks! But we use blueprint I think we cant make discord rpc for our game
