### ISSUE TITLE
dylib error on Big Sur with UE4

### ISSUE THREAD

**Issue by Mootbing** [discordapp/discord-rpc#312]
Engine version 4.22.3
Macos Big Sur,

error:
/System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/Current/MultitouchSupport no paths with that name

**Comment by Lachee** [comment]
This has nothing to do with discord?

**Comment by Mootbing** [comment]
Sorry I don't think I was being specific enough. The issue is upon using the RPC, it'll say "following assets are missing or built with a different version of the engine", then when you click ok, it'll build, until it crashes. That is the last line of the log before the build crashes

"/System/Library/PrivateFrameworks/MultitouchSupport.framework/Versions/Current/MultitouchSupport no paths with that name"

**Comment by Mootbing** [comment]
@Lachee I downgraded to macOS Catalina today, worked like a charm, however there is another issue. Everything works in the game editor, however when I package it, it gives me this error.

```dyld: Library not loaded: @rpath/libdiscord-rpc.dylib
  Referenced from: /Users/mootbing/Desktop/Unreal_Completed/MacNoEditor/SubwayChaos.app/Contents/MacOS/SubwayChaos
  Reason: image not found
zsh: abort
```
