### ISSUE TITLE
Cannot install discord-epc

### ISSUE THREAD

**Issue by moritz-mn** [discordapp/discord-rpc#325]
Whenever I try to install discord-rpc there are a lot of errors and it doesnt install

**Comment by SinisterRectus** [comment]
This repository's issues are more for the Discord bot/oauth2 API and the accompanying developer docs, Depending on what it is you are actually trying to do, you may find help in other places. Note that Discord's actual "discord-rpc" software is deprecated (not supported) in favor of the GameSDK.

- https://github.com/discord/discord-rpc
- https://discord.com/developers/docs/game-sdk/sdk-starter-guide
- https://discord.gg/discord-developers
