### ISSUE TITLE
rapidjson conflict

### ISSUE THREAD

**Issue by maximumgame** [discordapp/discord-rpc#33]
Our project uses an older version of rapidjson and by including discord-rpc as a static linked library causes issues with the compiler not knowing which to use.

Although this was solved for us by dropping the same version of rapidjson in to our project. This may not be viable for others.

**Comment by crmarsh** [comment]
I [tried to do a thing](https://github.com/discordapp/discord-rpc/blob/master/CMakeLists.txt#L35) where I look for existing rapidjson before downloading a new one; I have no idea how cmake tries to find things, though, so perhaps something in here could be fixed up for your case?

**Comment by crmarsh** [comment]
Did [this change](https://github.com/discordapp/discord-rpc/commit/f22f299330e97e68eed1a256b41630fd981ad1b8) fix this for you?

**Comment by crmarsh** [comment]
I'm not sure there's really anything else I can do about this on my end.
