### ISSUE TITLE
discord-rpc is stopping when i try to start it on my vps

### ISSUE THREAD

**Issue by Greeenman999** [discordapp/discord-rpc#335]
Hey guys,

I have tried running the code on my vps, however it always says when I try to run it:

`Error: Could not connect
    at Socket.onerror (/home/rpc/node_modules/discord-rpc/src/transports/ipc.js:32:16)
`

My Code:

`var rpc = require("discord-rpc")
const client = new rpc.Client({ transport: 'ipc' })
client.on('ready', () => {
client.request('SET_ACTIVITY', {
pid: process.pid,
activity : {
details : "Installiere gerne mein Modpack oder komme auf Redcity ;)",
assets : {
large_image : "Image",
large_text : "NextTopia" // THIS WILL SHOW AS "Playing <Status>" from the outisde
},
buttons : [{label : "NextTopia" , url : "https://www.curseforge.com/minecraft/modpacks/nexttopia/"},{label : "Redcity",url : "https://www.discord.link/redcity"}]
}
})
})
client.login({ clientId : "token is in here" }).catch(console.error);`

On my Laptop it works...

Any Idea?

**Comment by MinnDevelopment** [comment]
This library connects to your local running discord client. If you host it on a different machine it cannot connect anymore.

**Comment by Greeenman999** [comment]
oh
then i look for another way to run it
