### ISSUE TITLE
Cannot use correctly buttons

### ISSUE THREAD

**Issue by demaupeoucorentin** [discordapp/discord-rpc#336]
Hello everyone, 

I'm trying to use buttons of discord-roc library, and it seems to sometimes work, sometimes not.
I've tried a lot of urls, tried to see logs of Discord app (with ipc, and it doesn't seem to getting errors), and I've still not found the solution 😬.

Here's my current code : https://code.alwyn974.re/owunizaxar.coffeescript
Here's an example of what I've when I'm trying to open the url button : https://cdn.discordapp.com/attachments/793382333339271178/840256362361651251/Enregistrement_de_lecran_2021-05-07_a_17.58.21.mov

Thanks for your help and have a good day ❤️,
Corentin

**Comment by morpig** [comment]
## Deprecation Notice

This library has been deprecated in favor of Discord's GameSDK. [Learn more here](https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide)

you're also opening issue to the wrong repo 😂

**Comment by demaupeoucorentin** [comment]
Hahaha sorry for the late but I haven't seen that 😅
