### ISSUE TITLE
Need a way to check if discord is running, or have a callback run when discord isn't present when calling Discord_Initialize.

### ISSUE THREAD

**Issue by StrikerMan780** [discordapp/discord-rpc#35]
In my code, I have a loop like this:

```
	InitDiscord();
	while (discord_status == DISCORD_WAITING)
	{
		handleevents();
		Discord_RunCallbacks();
	}
```
Because I need to wait for Discord to be ready, before I can proceed with the rest of the game's startup (since multiplayer connections happen during this phase).

This loop works perfectly fine if Discord is running, it'll wait until Rich Presence is ready, and then proceed. (All the different handlers will change the value of DISCORD_STATUS, including the error callback.)

However, if Discord isn't running, there's no way to check this, not even the error callback fires, and thus the game just hangs here. I'd like to have some sort of callback or return value here.

**Comment by crmarsh** [comment]
You can expect that Discord is around after the ready callback, and you can expect that Discord has gone away if you get the disconnect cb, but it's not really safe to assume those states are stable. I would expect those cbs to happen pretty quickly, so perhaps just a timeout would meet your need? I would guess that if Discord is really required you'd bring up UI saying so? I think just in general I'm confused with what you're trying to build.

**Comment by StrikerMan780** [comment]
A timeout would be irritating for people without Discord. (Such as people setting up matches the traditional way without it.)

This is an older game, Duke Nukem 3D to be specific. The host starts the game with a certain command line parameter, which puts them in a "Waiting for players" mode, before initializing anything else in the engine. It waits until the appropriate number of players connect, then loads the game fully and puts everyone together in a match.

During this waiting for players stage is where the host could send invites through Discord.

I need this bit, because joining players launched through Discord need to halt at a certain point in the code until Discord is ready, and the joinGame callback fires, to make sure the joining player's game has all of the right information (IP address to connect to, mods loaded, etc) before proceeding to load the appropriate mods, connecting to the right IP, etc during initialization.

**Comment by StrikerMan780** [comment]
Of course, I could avoid this altogether if there were a way to set what command line arguments are used when another player launches the game through discord.

**Comment by msciotti** [comment]
Not an answer for this repo, but our GameSDK does return specific errors for when Discord is either not running or not installed.

Anyone else looking for an answer for this should move to our GameSDK; it has init callback results like:

- `NotInstalled`
- `NotRunning`

And will fire these if Discord is open but the user is logged out, as well.

https://discordapp.com/developers/docs/game-sdk/sdk-starter-guide

If you need help, come join us in the Discord at https://discord.gg/discord-gamesdk !
