### ISSUE TITLE
Discord RPC not working in some of programs in Fedora

### ISSUE THREAD

**Issue by ghost** [discordapp/discord-rpc#358]
In some of the programs (like JetBrains), Discord RPC works. But in some of the programs like VSCode, Salwyrr Client, etc. Discord RPC isn't working. I remember, though, these programs was working on my previous operating system, Debian.

**Comment by GamingGeek** [comment]
Any issues you're having with rich presence in certain applications should be taken up with the authors of said applications as it is likely a flaw in the application's implementation
