### ISSUE TITLE
 Can I run rpc.connect() without Discord open?

### ISSUE THREAD

**Issue by lermal** [discordapp/discord-rpc#359]
I want the profile to be permanent, but for this I need to run the code on a permanent host. If you run it without Discord open, it always gives an error (pypresence.exceptions.DiscordNotFound: Could not find Discord installed and running on this machine.) Can I run rpc.connect() without Discord open? (Via account token?)

**Comment by Lachee** [comment]
RPC works by directly communicating with the Discord client. So no, you cannot set the presence without discord open
