### ISSUE TITLE
RPC not working;

### ISSUE THREAD

**Issue by Netwyn** [discordapp/discord-rpc#374]
I have installed Discord from the Debian package from the official Discord website, and I use IntelliJ Ultimate and WebStorm; the strange thing is, neither of them seem to work, but VSCode's RPC does.
![image](https://user-images.githubusercontent.com/85914720/187494969-0919bfa9-4ca9-49d8-b5e9-a93a1eb4309b.png)

On occasions, the IntelliJ version works, but so far, I have never been able to get the WebStorm version to run.
![image](https://user-images.githubusercontent.com/85914720/187495158-be3efb0a-cd8c-4775-89f0-99fa8bdf1e12.png)

I tried opening up Discord before opening the IDEs, but that didn't seem to fix anything.
I have a decent enough internet connection.
I'm on an x86_64 Debian-based distribution of Linux.
I have the official Discord debian package, but the IDEs are from Flatpak.

Does anyone have any ideas on why this happens? Help appreciated!

**Comment by Lachee** [comment]
you will need to contact the developers of those presence plugins. This library might as well be in archival mode.

**Comment by Netwyn** [comment]
Oh wow. I somehow posted the issue in the wrong repo.
I was wondering why I couldn't find my issue on the RPC plugin's page.
