### ISSUE TITLE
Discord SDK/RPC with C# - what to chose?

### ISSUE THREAD

**Issue by aco228** [discordapp/discord-rpc#377]
I am currently integrating Discord into the C# desktop application - more precisely, I am integrating Rich Presence. I see two ways I can implement this: with SDK (.dll) or with RPC, and I am not sure what to choose, so I need help/advice:

- during my testing I was not able to have Rich Presence buttons with SDK? Is that supported or I was doing it wrongly?

- For RPC I see, `For now, RPC is in private beta. We are not currently accepting any new developers into the program at this time.`. Would it be safe for me to integrate RPC into the application, as I made it work in the way I intended (I am trying to avoid SDK so I do not want to include .dll into app) ?

- In the documentation I see this line `For applications/games not approved, we limit you to creating 10 guilds and 10 channels. This limit is raised to virtually unlimited after approval.`. Does that mean that I have limit with the app? What is the approval process as I could not find anything in the documentation?

Thanks in advanced!

**Comment by advaith1** [comment]
Connecting to the RPC server over WebSockets is private and deprecated, and so is the authentication stuff. Connecting to the RPC server over IPC is supported, and that is how this discord-rpc library, the GameSDK, and many third party libraries and games implement rich presence. You can implement the IPC connection yourself use or one of the many libraries available.

The official discord-rpc and GameSDK libraries do not support custom buttons as they are outdated, but the underlying IPC connection does and many third party libraries do.

Here is a maintained (unofficial) C# rich presence library: [Lachee/discord-rpc-csharp](https://github.com/Lachee/discord-rpc-csharp)

**Comment by aco228** [comment]
thanks, @advaith1 for the answer - I have two more you can help me or point me to the right person/place to ask?

- Is it safe to go with [Lachee/discord-rpc-csharp](https://github.com/Lachee/discord-rpc-csharp)? If I share this feature with 1000+ people, will it work, I am worried about this line from the documentation :
<img width="1033" alt="image" src="https://user-images.githubusercontent.com/35331284/224688943-d76838f0-92ad-4ebd-876c-a307377e2de8.png">

Also, regarding this question: what is the approval process? I don't see this in the developer portal.. is this some old feature, and it was removed in meantime?

**Comment by advaith1** [comment]
> I am worried about this line from the documentation

That only applies to creating guilds and channels; if you are just using rich presence then there is no limit on that.

They stopped approving apps for it many years ago; not sure if there was ever a public process for getting approved
