### ISSUE TITLE
Use `target_include_directories` to specify public header path

### ISSUE THREAD

**Issue by ChrisThrasher** [discordapp/discord-rpc#398]
https://github.com/discord/discord-rpc/blob/963aa9f3e5ce81a4682c6ca3d136cddda614db33/src/CMakeLists.txt#L1

This use of `include_directories` means that those who link to the `discord-rpc` target will not inherit the include paths required to use this target. An easy fix is to change this to a `target_include_directories` call with `PUBLIC` visibility so those linking to `discord-rpc` don't need to manually specify the include paths.

**Comment by p0358** [comment]
This was PR'd into our fork of this library: https://github.com/harmonytf/discord-rpc/pull/8
