### ISSUE TITLE
Send Discord Rich Presence from PWA

### ISSUE THREAD

**Issue by unordentlich** [discordapp/discord-rpc#401]
Hey!
Do you know if there’s any way to send a Discord Rich Presence through a PWA? Since it’s kind of a semi-local thing, I wasn’t sure if there’s an opportunity for it. Any ideas?
Thanks in advance!

**Comment by advaith1** [comment]
You can't, you'd need to use IPC/named pipes which isn't possible to access from in a browser, even in a PWA.

The only way would be to set the rich presence over http with the activities.write oauth scope, but it is private and not given out anymore.

**Comment by unordentlich** [comment]
That's a pity.. Thank you for making this clear! 🙏
