### ISSUE TITLE
Add instructions on 64 bit build with cmake

### ISSUE THREAD

**Issue by codecat** [discordapp/discord-rpc#41]
On Windows, generating a VS project will only add a 32 bit configuration. Maybe it's worth putting in the readme how to make a 64 bit build, too? (Using [`CMAKE_GENERATOR_PLATFORM`](https://cmake.org/cmake/help/latest/variable/CMAKE_GENERATOR_PLATFORM.html))

**Comment by codecat** [comment]
Nevermind that platform flag, on Windows you simply have to set the generator to "Visual Studio Win64" instead of the default.

**Comment by crmarsh** [comment]
Yeah, this is more of a cmake documentation problem than mine :-)
