### ISSUE TITLE
Missing discriminator for DiscordJoinRequest

### ISSUE THREAD

**Issue by MinnDevelopment** [discordapp/discord-rpc#44]
The payload for `ACTIVITY_JOIN_REQUEST` contains a full [user object](https://discordapp.com/developers/docs/resources/user#user-object) (exluding account security/type details) however it reads only `username`, `user_id`, and `avatar`.
The discriminator is incredibly helpful for apps to be specific about what user wants to join.

Was this intentionally left out?
See [Section](https://github.com/discordapp/discord-rpc/blob/c5d3481c474a54d556108778eb00adfc02433fb3/src/discord-rpc.cpp#L147-L152)

**Example**
```json
{
    "evt":"ACTIVITY_JOIN_REQUEST",
    "data": {
        "user": {
            "avatar":"e7032e1e1e602cd5123488da2a75f041",
            "id":"86699011792191488",
            "discriminator":"6688",
            "username":"Minn"
        }
    },
    "cmd":"DISPATCH",
    "nonce":null
}
```

**Comment by crmarsh** [comment]
I left it out because the intention there was to have a thing to show in the game's UI, and I didn't really think most people know/care about the discriminator -- I guess I'm cool with adding it in if you think it would be useful.

**Comment by MinnDevelopment** [comment]
I believe the discriminator is more valuable to the end-user than the user id. I personally really like the way discord (and others like blizzard) have Username#Number to show unique users and think it can be useful to have in a game's UI as well.

**Comment by msciotti** [comment]
I'll +1 adding the discriminator. Those that want to use it can—those who don't can ignore it.

**Comment by crmarsh** [comment]
Yeah, I'm sold on it. [Started to add it](https://github.com/discordapp/discord-rpc/tree/add-descrim) and realized the Unreal example didn't get join requests yet at all..

**Comment by msciotti** [comment]
Fixed with https://github.com/discordapp/discord-rpc/commit/1a278528a2315561f4121a8cb884354bf31cfa16. Chris forgot to link issues.
