### ISSUE TITLE
Unreal example project Solution doesn't compile

### ISSUE THREAD

**Issue by Mootjuh** [discordapp/discord-rpc#49]
Error at:

Plugins\discordrpc\Source\discordrpc\Public\DiscordRpcBlueprint.h

Caused due to the include "DiscordRpcBlueprint.generated.h" not being at the end of the includes.

Build succeeds once moving that line to the bottom of the includes.

**Comment by crmarsh** [comment]
Yeah, [I ran into that](https://github.com/discordapp/discord-rpc/pull/47/commits/00c4df4a8a00def7bc658ea0680f3b01fea3248e), should be fixed soon.

**Comment by KiaArmani** [comment]
https://github.com/discordapp/discord-rpc/pull/51 fixes this.
