### ISSUE TITLE
Constructued DiscordRPC class gets destroyed when doing anything related to Sessions in Unreal Engine.

### ISSUE THREAD

**Issue by Mootjuh** [discordapp/discord-rpc#53]
When hosting or joining a session. The DiscordRPC class gets destroyed/becomes invalid and it won't be able to send presences or check for callbacks anymore. OnDisconnected & OnErrored does not fire either when this happens.

However, if you construct the class again after it's become invalid everything seems to work like normal again. OnConnected does not re-fire when you reconstruct the class.

**Comment by iUltimateLP** [comment]
It might be garbage collected. In the `UDiscordRpc::Initialize` function, try adding `AddToRoot();`, that prevents Unreal from garbage collecting anything :) Report back if it works!
