### ISSUE TITLE
Ingame personal inviting

### ISSUE THREAD

**Issue by Mootjuh** [discordapp/discord-rpc#58]
Any way to invite a specific person and have that person be able to accept that invite ingame? If there isn't, this might be something useful to add. Right now you need to press the joim button inside Discord to accept an invite, which works great for groups but is kinda annoying per person. 

I'm assuming you need to be able to get your friends list somehow.

**Comment by MinnDevelopment** [comment]
You can use the respond method and send the DISCORD_RESPONSE_YES constant.

**Comment by Mootjuh** [comment]
The one sending the response should be getting an invite first though, unlike JoinRequest() the one responding will be the one who's joining a match instead of the other way around.

**Comment by MinnDevelopment** [comment]
So you want a way to request joining within the game?

**Comment by devsnek** [comment]
in-game invitations should be done through your game, not discord rpc

**Comment by Mootjuh** [comment]
The forces you to work with two systems at the same time though, you have the discord joining and request to join and your separate invite system.

**Comment by msciotti** [comment]
@Mootjuh You can send the game invitation in any text channel. So if you want only one person to act on it, you could send it in a PM to that person.
