### ISSUE TITLE
Discord_Shutdown does not unset Discord user's Playing status

### ISSUE THREAD

**Issue by Eng1N33R** [discordapp/discord-rpc#61]
For both the `send-presence` sample and our own integration, a call to `Discord_Shutdown` does not call the `disconnect` handler, and the `Playing <game>` status in Discord stays there for the user even after the process has been shut down. Calling `Discord_UpdateConnection()` and `Discord_RunCallbacks()` after `Discord_Shutdown()` (to _really_ cover all our bases) didn't work either. The only fix for this is restarting Discord client-side; the RP status disappears then. Time doesn't seem to play a role either, as the RP just stays there.

The `send-presence` sample that was tested was taken from the `2.0.1` release of this repo. For our own integration, `discord-rpc` was compiled as a 32-bit DLL from the `master` source as of commit `5d5bc82` on a Win 7 64-bit machine:

```
cmake .. -DCMAKE_INSTALL_PREFIX=..\out -DBUILD_SHARED_LIBS=ON -DUSE_STATIC_CRT=ON -DENABLE_IO_THREAD=OFF -G "Visual Studio 14 2015"
```

**Comment by Eng1N33R** [comment]
But the process _doesn't_ exist in my scenario. For example, this was taken 5 minutes after starting `send-presence.exe`, typing `f` into the prompt, and closing it as soon as `Discord: ready` was shown. As you can see, no `send-presence` process exists, but the RP info is still displayed with the time left having counted down to 00:00.

![image](https://user-images.githubusercontent.com/4773889/33092165-fff76c82-cf01-11e7-9938-fe0c4ee5db29.png)

**Comment by No-Half-Measures** [comment]
Looking at the Send-Presence example 'Discord_Shutdown' is called twice when you 'quit' using the q input option, I actually did this in my own code too accidentally and had the same issue where the rich presence status was stuck displayed even though the process had closed after the 'Discord_Shutdown' function was called (all be it was twice). 
After removing the second un-needed execution of the 'Discord_Shutdown' function and testing it seemed to have fixed it in my code/senario... Could this be an issue then with executing 'Discord_Shutdown' more than once? If that's the case even though you shouldn't there probably should be something stopping this issue from even happening in the first place.

**Comment by crmarsh** [comment]
Nah, `Discord_Shutdown` should be safe to call a second time. That sounds like a bug on Discord's side.

**Comment by crmarsh** [comment]
Fixed on canary and ptb, should get to stable soon.

**Comment by StrikerMan780** [comment]
Good that this is fixed. I thought I was going crazy.

**Comment by crmarsh** [comment]
Should be fixed in stable now.
