### ISSUE TITLE
Use discord-rpc on Qt

### ISSUE THREAD

**Issue by DoctorVWA** [discordapp/discord-rpc#65]
I'm trying to export the lib to the Qt IDE, and use it, I add the folder to the project's folder and add this to the .pro file:

INCLUDEPATH += discord-rpc/include

LIBS += -L"discord-rpc/lib/discord-rpc.lib"

when I try to include the discord-rpc.h in my main file the functions of the lib don't work 

![image](https://user-images.githubusercontent.com/17722403/33241664-c34eb374-d2af-11e7-91d7-016be7b851ad.png) 

when I type ctrl and click in the included file, in the line #include "discord-rpc.h", I go to the file discord-rpc.h, but the functions don't work on the main file.

What is happening?

**Comment by Rapptz** [comment]
`-L` is reserved for library search paths, not actual libraries. To link with a library you have to use `-l` instead, or in the case of `.pro` files not use `-L"..."` at all and just specify the library.

In any case this has nothing to do with this repository since it's not an issue with the RPC.

**Comment by DoctorVWA** [comment]
Okay, thanks and sorry.

**Comment by DoctorVWA** [comment]
I make this issue because I've tryed to use -L"discord-rpc/lib", and have the same error, i'll try what you say and tell you what happens

**Comment by DoctorVWA** [comment]
the apps crashes without errors... but, thanks for all.

**Comment by crmarsh** [comment]
Can you open up a bug with specifics on your crash (if it is still happening)?
