### ISSUE TITLE
.vcxproj file for easier submoduling for Visual Studio Projects

### ISSUE THREAD

**Issue by sr229** [discordapp/discord-rpc#66]
It would be nice if we can just submodule this in a Visual Studio Project however, due to the lack of a .vcxproj file inside, either you have to manually create it yourself or supply the precompiled DLL instead.

**Comment by crmarsh** [comment]
I went the `cmake` route, which should be generating vcxproj files you can use. Is this not working right, or are you objecting to the setup step?

**Comment by sr229** [comment]
@crmarsh I'm kinda referring of having it already in the project since there woul be developers who will build the RPC library alongside their game builds for easier publishing.

**Comment by YaLTeR** [comment]
That would require making a .vcxproj for all the different VS versions, wouldn't it? Which is one of the problems CMake solves.

**Comment by crmarsh** [comment]
I'll think about it, but I want to leave it as is for now.
