### ISSUE TITLE
Instead of segfaulting when Discord is not installed, have a set boolean or something to see if it is installed.

### ISSUE THREAD

**Issue by TsundereBug** [discordapp/discord-rpc#67]
[Logs can be found here.](https://github.com/TsundereBug/discord-intellij/issues/2) Now this might be a here problem, this might be a problem [in the JNI/JNA lib](https://github.com/MinnDevelopment/Java-DiscordRPC/issues/4), or this might be a problem [in how I instantly try to connect to Discord](https://github.com/TsundereBug/discord-intellij/blob/master/src/com/tsunderebug/discordintellij/StartupShutdown.scala).

**Comment by crmarsh** [comment]
This looks like a crash from exiting the process without calling `Discord_Shutdown`, does not have anything to do with Discord being installed or not.

**Comment by crmarsh** [comment]
One could argue that I should fix that crash so that `Discord_Shutdown` is not required.

**Comment by crmarsh** [comment]
Like [this](https://github.com/discordapp/discord-rpc/commit/91307070867ff56e3898bbc3efa841ce36f4fa90)
