### ISSUE TITLE
Allow setting Rich Presence activity types via RPC

### ISSUE THREAD

**Issue by justJS** [discordapp/discord-rpc#71]
Right now, RPC rich presence clients don't allow to set activity types, however, this should be possible, because many people are making apps for music and other integrations using RPC. Also, since devs have clarified that these apps are *allowed*, having (especially) the "listening to" type would be beneficial.

**Comment by msciotti** [comment]
This is a valid want. I don't have any information about when and if we will support this, but I'll keep this issue open as the official request and de-dupe other issues into this one.

**Comment by justdotJS** [comment]
OK, thanks!

**Comment by justdotJS** [comment]
Any update on this? This is ridiculous, Spotify has it and noone else does. How much did Discord get paid?

**Comment by msciotti** [comment]
There is no additional information around allowing Rich Presence applications to set different activity types, though we do have this feature request (and all the others) tracked and documented both here and internally.

Spotify does indeed have this feature, you are correct.

**Comment by msciotti** [comment]
Moved to [Feedback Site](https://support-dev.discordapp.com/hc/en-us/community/posts/360043425691-Allow-setting-different-activity-types-in-UpdateActivity) as part of #290
