### ISSUE TITLE
Error at LSSetDefaultHandlerForURLScheme() (OSStatus -54)

### ISSUE THREAD

**Issue by WillEccles** [discordapp/discord-rpc#77]
Using Xcode, I am linking the compiled lib in my native Objective-C++ based app. [Line 67 of discord_register_osx.m](https://github.com/discordapp/discord-rpc/blob/master/src/discord_register_osx.m#L67) is creating an error, OSStatus -54. This is the code for insufficient privileges usually (i.e., when you try to open a file you aren't allowed), so I'm not sure how this is happening. No clue why, of all things, `LSSetDefaultHandlerForURLScheme()` would be doing this. Also of note: I don't think this is an issue with the example, though I never have been able to get it to run properly in the first place.

**Comment by jhgg** [comment]
Can you provide more specific details about your environment? OSX verison, xcode version, clang version, etc... 

I see an RDAR open for Yosemite describing a similar issue: http://www.openradar.me/17601367

**Comment by WillEccles** [comment]
I'm on High Sierra (10.13.1, 17B1003), Xcode 9.1, Apple LLVM version 9.0.0 and clang-900.0.38.

As far as I know, this should all be up to date, aside from maybe Xcode, but the version of Xcode should not make much difference. If it makes a difference, I used a Java wrapper of this lib for a different app to test it, and it worked just fine.

**Comment by crmarsh** [comment]
If the stuff in register isn't working on OSX, you can always fall back to putting the equivalent stuff in your `info.plist` (which seems to be Apple's preference for such things anyway). I didn't hit this error on my machine though (and I have those same versions of things), so I'm confused.

**Comment by msciotti** [comment]
@WillEccles if you pull the latest version of the repo and try our Unity example, are you able to get it to work? It should be following the same logic.

**Comment by WillEccles** [comment]
@msciotti I will try this later today and report back, although I don't think I have Unity installed. Would it work for the regular lib if I compiled it and used it in Xcode? Or is the change you made only for the Unity one.

**Comment by msciotti** [comment]
Not a matter of a change being made. I'm wondering if you run the unity app (where, in the initialize, it registers an application protocol) if you see the same error.

**Comment by WillEccles** [comment]
Ah, yeah not sure about that. I ran the console test application when I first installed the library (took some messing about to get that to run, but that was because it doesn't want to launch a console app from a .app package or something), and it seemed to work just fine (although I couldn't get Discord to discover it because it was running in a terminal).

**Comment by WillEccles** [comment]
As a side-note, I just tried the Unreal example since I don't have Unity installed, but I do have Unreal installed. When I tried to open the project, it said that two dylibs were out of date or built with an older version of the engine. I told it to rebuild them, but it gives me the message "unrealstatus could not be compiled. Try rebuilding from source manually."

**Comment by WillEccles** [comment]
Alright, installed and ran the Unity project. No issues. I'm not sure how I managed to get a -54 when neither example I have tried has an issue with it.

**Comment by msciotti** [comment]
Apologies on the unreal example—it's out of date and hasn't been touched up in a bit. As Chris mentioned earlier, if the auto-stuff isn't working with your game for some reason, you can just add the necessary stuff to your `info.plist`.

**Comment by msciotti** [comment]
@WillEccles were you able to figure it out with your own implementation?

**Comment by WillEccles** [comment]
@msciotti unfortunately, I'm in school right now and have gotten really busy with finals. I will continue work on that project over the upcoming break or maybe even next semester (if I get too lazy over break). Thanks for the help though, I will likely try the plist fix. Not sure exactly how that's done, however, so I have to figure that out.

**Comment by msciotti** [comment]
@WillEccles No problem at all. Best of luck on your finals—finish the year strong! I'll close this issue, and if it pops back up for you, go ahead and open another one.

This may be a good place to start with the plist stuff: https://stackoverflow.com/questions/471581/how-to-map-a-custom-protocol-to-an-application-on-the-mac
