### ISSUE TITLE
OSX and Linux Libraries in Release Package?

### ISSUE THREAD

**Issue by SirDrMcHurtz** [discordapp/discord-rpc#78]
The current packages currently only include Windows 32-bit and 64-bit DLLs. As the library (in theory?) supports OSx and Linux, is there a reason prebuilt versions aren't available? As a Unity developer it would make implementation orders of magnitude simpler if they were available as well as Windows builds.

Thanks!

**Comment by msciotti** [comment]
Our build machines weren't configured to output pre-compiled binaries for osx and linux at the time of the last release. The next release will have them.
