### ISSUE TITLE
[Suggestion] Version number to check against

### ISSUE THREAD

**Issue by Fireboyd78** [discordapp/discord-rpc#84]
Would it be possible to add a version we can check against for those of us using the `win32-dynamic` build?

For example, if we implement something that requires at minimum v2.1.0, there should be a way to check that the user has a DLL that meets the minimum version. Here's how it could be potentially implemented:

```cpp
DISCORD_EXPORT float Discord_GetVersion(void) const;
```
Usage:
```cpp
if (Discord_GetVersion() < 2.1f) {
  Error("Your Discord RPC plugin is out of date, please update it and try again.");
}
```

This would ensure any projects relying on the dynamic branch (which may require users to download the DLL manually) will continue to work correctly, without having to resort to customer feedback of "why isn't X working?!" -- unless this is guaranteed to never happen, of course!

**Comment by devsnek** [comment]
you should just deploy your app with the dll, any changes worth changing the dll for will most likely require changes to your app anyway

**Comment by Fireboyd78** [comment]
@devsnek It's an [open-source mod](https://github.com/Fireboyd78/mm2hook) for a game that we don't have the source code to. I did attempt to use the static version, but it didn't play well with the linker unfortunately.

**Comment by Bluexin** [comment]
Can't you ship the dynamic dll alongside your mod?

**Comment by msciotti** [comment]
I think Bluexin has the right idea here. Rather than instruct users to update a third-party dependency (that they may or may not know how to to) for _your_ third-party mod, it probably makes more sense to include a build script in whatever update process your mod has to pull the latest dll from our releases, or compile it yourself if that's preferable.

That means players will never have to worry about juggling dlls, and you don't have to worry about writing a help article instructing them how to do it and answering support questions of:

```
Error("Your Discord RPC plugin is out of date, please update it and try again.");

what does this mean
```

Does that seam reasonable?

**Comment by Fireboyd78** [comment]
Currently, the only build process involved is using AppVeyor to compile the latest changes made to the repository. I am not aware of the ability to include a 3rd party dependency with the build artifacts it generates.

The error message was just a simple, straight-forward example. I include more in-depth instructions on my repo, and regularly keep everyone updated via our Discord channel. There is no updater for the mod (other than the AppVeyor builds). The amount of users is very small, maybe a handful of people use it at the most. Just a small side hobby, really.

I only suggested this idea because, as mentioned, there is no way to verify that the dynamic version being loaded is compiled against the header file used in the mod. It's a very, very minor thing, and I doubt it'll be utilized by a lot of people. But it would be there if needed!

I don't think there's much more that I can say. I feel it's a harmless thing to implement and keep maintained, just for that extra degree of security. Developers may use it however they deem necessary, if even at all.

**Comment by msciotti** [comment]
Moved to [Feedback Site](https://support-dev.discordapp.com/hc/en-us/community/posts/360043426111-Version-Number-to-check-against) as per #290
