### ISSUE TITLE
[Suggestion] Add a callback/handler to the presence update

### ISSUE THREAD

**Issue by kkirigaya** [discordapp/discord-rpc#85]
As originally brought up in [Minn's Java wrapper repo](https://github.com/MinnDevelopment/Java-DiscordRPC/issues/10) but applies to the core repo, it would be nice to know when the client receives the presence payload and updates the rich presence to avoid "ghost games." The most fitting place I can think of would be the handlers that fire on things like join requests, spectate requests, etc.

**Comment by msciotti** [comment]
I'm not really sure what you mean here by "ghost games". There is a 1 update per 15 second rate limit on `UpdatePresence()` messages sent from a local Discord client to the server, as outlined in the documentation.

Our intent is to make it so you don't need to worry about handling this limit, as the client will automatically queue up the last sent `UpdatePresence()` call and send it to the server once it's allowed to.

If you're talking about this race condition bug (https://github.com/MinnDevelopment/Java-DiscordRPC/issues/10), that is indeed a bug that needs to be fixed.

**Comment by msciotti** [comment]
Oh, hey we can close this now. Due to our recent changes that monitor games by websocket connection and not pid, "ghost games" are a thing of the past! Sorry for the necro on the issue, but hey, it's a good news necro!
