### ISSUE TITLE
"Error opening Steam key" when calling Discord_Initialize

### ISSUE THREAD

**Issue by JoshuaDoes** [discordapp/discord-rpc#86]
I've attempted to get this error to not appear, but to no avail. The game I am working with is not in the Steam Store and I do not have Steam installed. I've attempted to not include this parameter in the call, pass a blank string, pass a pointer to 0, pass "0" as a string, etc and all has failed.

I'm creating a function set that wraps around the discord-rpc DLL library for a Windows scripting language known as AutoIt, and I can't seem to get the initialization to succeed due to this error. Is there something specific I should be passing as a parameter? I can't seem to figure it out by studying the source.

Thanks in advance!

**Comment by msciotti** [comment]
You should be able to pass `null`. If you pass a value:

```
""
" "
0
"0"
```

The code will interpret those as steam app ids, and attempt to register your game to a steam protocol.

So your two options should be:

`Discord_Initialize(appId, ref handlers, true, null);`

or, you can manually call the proper registration function sometime on startup or installation:

https://github.com/discordapp/discord-rpc/blob/master/src/discord_register.h#L7

And then omit the autoRegistration parameter in the `Init()` like:

`Discord_Initialize(appId, ref handlers, false, null);`

**Comment by JoshuaDoes** [comment]
Thank you for the help, using null worked just fine!
