### ISSUE TITLE
Segmentation Fault

### ISSUE THREAD

**Issue by ZoroSC** [discordapp/discord-rpc#87]
When I try to start my app. it just crashes. And says `Segmentation Fault` The code can be found here https://pastebin.com/TVLjbT9k

**Comment by SEAPUNK** [comment]
Looks like you're using node.js and the [npm discord-rpc module](https://www.npmjs.com/package/discord-rpc), which isn't maintained by us. This would be a question for the owner of the module, not us.

**Comment by msciotti** [comment]
As seapunk mentioned, the `discord-rpc` module is not maintained by us. Similarly, if you're experiencing a segmentation fault, it's either an error in other code that you have somewhere, or in the library.
