### ISSUE TITLE
[Feature Request] Fix build script for UE4

### ISSUE THREAD

**Issue by msciotti** [discordapp/discord-rpc#89]
We do some magic in the build script to automatically compile and move the DLLs for the unity example so that it works out of the box.

We should do the same for Unreal.

https://github.com/discordapp/discord-rpc/blob/master/build.py#L89-L92

**Comment by snowyote** [comment]
I'm partway there on this (`python build.py unreal` will move the dll/lib/h file to the correct position for development) but I see discussion about changes needing to be made for packaged builds, so I gotta learn a little more about unreal for that!

**Comment by msciotti** [comment]
Fixed in #112, closing here 👍
