### ISSUE TITLE
Crash in UE4 when using DiscordRPC

### ISSUE THREAD

**Issue by Mootjuh** [discordapp/discord-rpc#92]
It's a bit vague on why this is happening, but I get this error as soon as I construct the DiscordRPC class.

LogStreaming: Error: Couldn't find file for package /Script/discordrpc requested by async loading code. NameToLoad: /Script/discordrpc

Seems to have happened after I've upgraded to version 2.1. Tested on versions 4.17.2 & 4.18.1

**Comment by oreyg** [comment]
I'm experiencing this issue right now. How did you solve it?

**Comment by Mootjuh** [comment]
In the .uplugin you need to change the "type" from "development" to "runtime"
