### ISSUE TITLE
[Request] Launch applications using launch options.

### ISSUE THREAD

**Issue by GamerUntouch** [discordapp/discord-rpc#94]
For compatibility reasons, the way secrets work shouldnt be totally replaced, but I feel that handling join/spectate/match secrets through launch options would be a lot easier than the setup we have now.

This is how the steamworks matchmaking system works, and it's a lot easier to deal with, since I can get the lobby ID right away, unlike discord where I need to wait for the callback. 

Unless there's a reason for this not working like this, of course.

**Comment by fr500** [comment]
For practical reasons a user may want to append command line options too (custom config file in RetroArch is the use case here)

**Comment by msciotti** [comment]
If there is a custom config file that is consistent across every launch of the application, launch options could be set at protocol registration. You could pass `Discord_Register()` a command to run your game with the proper launch option.

We do not currently support _dynamic_ launch options, as this issue asks for.

**Comment by fr500** [comment]
@msciotti yeah I managed to get it going passing argv as a command.
One more question/request

In some cases it may be desirable to set a working folder. Think that's possible at all?

**Comment by msciotti** [comment]
Though not _exactly_ the same as this feature request, I'm going to close this in reference to this documentation: https://discordapp.com/developers/docs/dispatch/branches-and-builds#launch-options

It's true that we do not support easily-customizable launch options (outside of `argv` stuff that fr500 mentioned) or working directory setting for RPC-only applications. We have that functionality for games that are launched via Discord and are registered in a user's game library. For right now, that's the extent to which we'll be supporting it.

Feel free to open a request in the support center linked in #290 if you'd still like to see this!
