### ISSUE TITLE
[Feature request] Python

### ISSUE THREAD

**Issue by iCrazyBlaze** [discordapp/discord-rpc#98]
I would love to be able to use Rich Presence with the discord.py API. Unless there is some way of doing it already, which in that case please tell me, because it would be SO useful!

**Comment by MinnDevelopment** [comment]
If you want to make feature requests for discord.py you should do so on the [discord.py repository](https://github.com/Rapptz/discord.py)

**Comment by msciotti** [comment]
Yes. As Minn said, discord.py is a community driven library. So it would be best to ask there for support.

That being said, Rich Presence can't be used by bots, so unless they pull out/refactor a subset of the library to work outside of bot use, it wouldn't really fit.
